"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams,useRouter,useSearchParams} from "next/navigation";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {DAMASIO_SYNC_EVENT,getActivityLogs,getAssignableWorkers,getEstimates,getExpenses,getInvoices,getLeads,getServiceRequests,getWorkflowEvents,type ActivityLog,type Lead} from "@/lib/storage";
type Row={id:string;title:string;subtitle:string;meta:string;status:string;amount?:number};
const labels:Record<string,{title:string;subtitle:string;eyebrow:string;icon:string}>={command:{title:"Command",subtitle:"Live operation",eyebrow:"OPERATIONS NOW",icon:"⌁"},customers:{title:"Customers",subtitle:"Homes and contacts",eyebrow:"CUSTOMER RECORDS",icon:"◎"},estimates:{title:"Estimates",subtitle:"Quotes and approvals",eyebrow:"SALES PIPELINE",icon:"▤"},invoices:{title:"Invoices",subtitle:"Billing status",eyebrow:"ACCOUNTS RECEIVABLE",icon:"$"},requests:{title:"Requests",subtitle:"Customer needs",eyebrow:"SERVICE INBOX",icon:"＋"},employees:{title:"Employees",subtitle:"People and crews",eyebrow:"FIELD TEAM",icon:"♧"},finance:{title:"Finance",subtitle:"Revenue and costs",eyebrow:"BUSINESS HEALTH",icon:"◈"},reports:{title:"Reports",subtitle:"Operational activity",eyebrow:"PERFORMANCE",icon:"▥"},settings:{title:"Settings",subtitle:"Company preferences",eyebrow:"CONFIGURATION",icon:"⚙"}};
export default function MobileAdminSection(){
 const section=String(useParams().section||"");const router=useRouter();const config=labels[section]||labels.settings;const search=useSearchParams();const[tick,setTick]=useState(0);const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[selectedLead,setSelectedLead]=useState<Lead|null>(null);const[selectedLog,setSelectedLog]=useState<ActivityLog|null>(null);
 useEffect(()=>{const update=()=>setTick(v=>v+1);window.addEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.addEventListener("storage",update);return()=>{window.removeEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.removeEventListener("storage",update)}},[]);
 const leads=useMemo(()=>{tick;return getLeads()},[tick]);
 useEffect(()=>{const id=search.get("property");if(section==="customers"&&id)router.replace(`/mobile/admin/customers/${id}`)},[section,search,router]);
 const logs=useMemo(()=>{tick;return getActivityLogs().slice(0,100)},[tick]);
 const rows=useMemo<Row[]>(()=>{if(section==="customers")return leads.map(i=>({id:i.id,title:i.name,subtitle:i.address,meta:i.service,status:i.status,amount:i.total}));if(section==="estimates")return getEstimates().map(i=>({id:i.id,title:i.customer,subtitle:i.title,meta:i.number,status:i.status,amount:i.total}));if(section==="invoices")return getInvoices().map(i=>({id:i.id,title:i.customer,subtitle:i.service,meta:i.number,status:i.status,amount:i.total}));if(section==="requests")return getServiceRequests().map(i=>({id:i.id,title:i.customerName,subtitle:i.service,meta:i.address,status:i.status}));if(section==="employees")return getAssignableWorkers().filter(n=>!["Admin","Unassigned"].includes(n)).map((n,i)=>({id:`worker-${i}`,title:n,subtitle:n.includes("Crew")?"Field crew":"Employee",meta:"Available for assignment",status:"active"}));if(section==="finance")return getExpenses().map(i=>({id:i.id,title:i.vendor,subtitle:i.notes||i.category,meta:i.date,status:"expense",amount:i.amount}));if(section==="reports"||section==="command")return logs.map(i=>({id:i.id,title:i.action,subtitle:i.target,meta:new Date(i.createdAt).toLocaleString("en-CA"),status:i.actor||"activity"}));return [{id:"company",title:"Company profile",subtitle:"Business name, contact and service area",meta:"General",status:"ready"},{id:"mobile",title:"Mobile application",subtitle:"Updates, navigation and notifications",meta:"Application",status:"ready"}]},[section,leads,logs]);
 const statuses=Array.from(new Set(rows.map(r=>r.status)));const visible=rows.filter(r=>(status==="all"||r.status===status)&&`${r.title} ${r.subtitle} ${r.meta}`.toLowerCase().includes(query.toLowerCase()));const total=rows.reduce((s,r)=>s+(r.amount||0),0);
 function openRow(row:Row){if(section==="customers")router.push(`/mobile/admin/customers/${row.id}`);if(section==="command"||section==="reports")setSelectedLog(logs.find(l=>l.id===row.id)||null)}
 return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin/more"/><div><strong>{config.title}</strong><span>{config.subtitle}</span></div><span className="role-mobile-avatar">{config.icon}</span></header><section className="mobile-native-hero"><span>{config.eyebrow}</span><h1>{rows.length} {config.title.toLowerCase()} in one place.</h1><p>{total?`$${total.toLocaleString("en-CA",{maximumFractionDigits:0})} total value`:"Live operational information"}</p></section><div className="mobile-native-search"><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}`}/>{query&&<button onClick={()=>setQuery("")}>×</button>}</div>{statuses.length>1&&<nav className="mobile-filter-strip"><button className={status==="all"?"active":""} onClick={()=>setStatus("all")}>All <b>{rows.length}</b></button>{statuses.map(v=><button className={status===v?"active":""} onClick={()=>setStatus(v)} key={v}><span>{v}</span><b>{rows.filter(r=>r.status===v).length}</b></button>)}</nav>}<section className="mobile-tool-list">{visible.map(row=><button type="button" className="mobile-tool-row" key={row.id} onClick={()=>openRow(row)}><i>{config.icon}</i><div><small>{row.meta}</small><strong>{row.title}</strong><span>{row.subtitle}</span></div><em>{row.status}</em>{row.amount!==undefined&&<b>${row.amount.toLocaleString("en-CA",{maximumFractionDigits:0})}</b>}</button>)}{!visible.length&&<div className="mobile-native-empty"><i>⌕</i><strong>No results</strong><p>Try another search or filter.</p></div>}</section>{selectedLead&&<CustomerSheet lead={selectedLead} close={()=>setSelectedLead(null)}/>} {selectedLog&&<LogSheet log={selectedLog} leads={leads} close={()=>setSelectedLog(null)}/>}<MobileAdminNav active="more"/></main></MobileRoleGuard>
}
function CustomerSheet({lead,close}:{lead:Lead;close:()=>void}){return <div className="mobile-native-modal mobile-detail-sheet"><button className="mobile-native-scrim" onClick={close}/><section><header><div><span>CUSTOMER & PROPERTY</span><h2>{lead.name}</h2></div><button onClick={close}>×</button></header><dl className="mobile-property-dl"><div><dt>Address</dt><dd>{lead.address}</dd></div><div><dt>Service</dt><dd>{lead.service}</dd></div><div><dt>Price</dt><dd>${lead.total.toFixed(2)}</dd></div><div><dt>Frequency</dt><dd>{lead.serviceFrequency||"Not set"}</dd></div><div><dt>Schedule</dt><dd>{lead.scheduledDate||lead.nextVisitDate||"Not scheduled"}</dd></div><div><dt>Crew</dt><dd>{lead.assignedCrew||"Unassigned"}</dd></div><div><dt>Phone</dt><dd>{lead.phone||"Not available"}</dd></div><div><dt>Email</dt><dd>{lead.email||"Not available"}</dd></div><div><dt>Property</dt><dd>{lead.propertyDetails?.lawnSize||"Size not set"} · {lead.propertyDetails?.backyard?"Backyard":"No backyard"}</dd></div><div><dt>Notes</dt><dd>{lead.notes||"No notes"}</dd></div></dl><button className="mobile-native-submit" onClick={close}>Close</button></section></div>}
function LogSheet({log,leads,close}:{log:ActivityLog;leads:Lead[];close:()=>void}){const lead=leads.find(l=>log.target===l.id||log.target===l.name||log.details.includes(l.name)||log.details.includes(l.address));const workflow=getWorkflowEvents().filter(e=>e.entityId===(lead?.id||log.target)).sort((a,b)=>Math.abs(Date.parse(a.createdAt)-Date.parse(log.createdAt))-Math.abs(Date.parse(b.createdAt)-Date.parse(log.createdAt)))[0];return <div className="mobile-native-modal mobile-detail-sheet"><button className="mobile-native-scrim" onClick={close}/><section><header><div><span>CHANGE DETAILS</span><h2>{log.action}</h2></div><button onClick={close}>×</button></header><dl className="mobile-property-dl"><div><dt>Changed by</dt><dd>{log.actor}</dd></div><div><dt>Date</dt><dd>{new Date(log.createdAt).toLocaleString()}</dd></div><div><dt>Record</dt><dd>{lead?.name||log.target}</dd></div>{lead&&<div><dt>Property</dt><dd>{lead.address}</dd></div>}<div><dt>Change</dt><dd>{log.details}</dd></div>{workflow&&<div><dt>Workflow</dt><dd>{workflow.fromStage||"Not recorded"} → {workflow.toStage}</dd></div>}</dl><button className="mobile-native-submit" onClick={close}>Close</button></section></div>}
