"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {DAMASIO_SYNC_EVENT,getActivityLogs,getAssignableWorkers,getEstimates,getExpenses,getInvoices,getLeads,getServiceRequests} from "@/lib/storage";

type MobileRow={id:string;title:string;subtitle:string;meta:string;status:string;amount?:number};
const labels:Record<string,{title:string;subtitle:string;eyebrow:string;icon:string}>={
 command:{title:"Command",subtitle:"Live operation",eyebrow:"OPERATIONS NOW",icon:"⌁"},customers:{title:"Customers",subtitle:"Homes and contacts",eyebrow:"CUSTOMER RECORDS",icon:"◎"},estimates:{title:"Estimates",subtitle:"Quotes and approvals",eyebrow:"SALES PIPELINE",icon:"▤"},invoices:{title:"Invoices",subtitle:"Billing status",eyebrow:"ACCOUNTS RECEIVABLE",icon:"$"},requests:{title:"Requests",subtitle:"Customer needs",eyebrow:"SERVICE INBOX",icon:"＋"},employees:{title:"Employees",subtitle:"People and crews",eyebrow:"FIELD TEAM",icon:"♧"},finance:{title:"Finance",subtitle:"Revenue and costs",eyebrow:"BUSINESS HEALTH",icon:"◈"},reports:{title:"Reports",subtitle:"Operational activity",eyebrow:"PERFORMANCE",icon:"▥"},settings:{title:"Settings",subtitle:"Company preferences",eyebrow:"CONFIGURATION",icon:"⚙"}
};
export default function MobileAdminSection(){
 const section=String(useParams().section||"");const config=labels[section]||labels.settings;const[tick,setTick]=useState(0);const[query,setQuery]=useState("");const[status,setStatus]=useState("all");
 useEffect(()=>{const update=()=>setTick(value=>value+1);window.addEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.addEventListener("storage",update);return()=>{window.removeEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.removeEventListener("storage",update)}},[]);
 const rows=useMemo<MobileRow[]>(()=>{tick;try{
  if(section==="customers")return getLeads().map(item=>({id:item.id,title:item.name,subtitle:item.address,meta:item.service,status:item.status,amount:item.total}));
  if(section==="estimates")return getEstimates().map(item=>({id:item.id,title:item.customer,subtitle:item.title,meta:item.number,status:item.status,amount:item.total}));
  if(section==="invoices")return getInvoices().map(item=>({id:item.id,title:item.customer,subtitle:item.service,meta:item.number,status:item.status,amount:item.total}));
  if(section==="requests")return getServiceRequests().map(item=>({id:item.id,title:item.customerName,subtitle:item.service,meta:item.address,status:item.status}));
  if(section==="employees")return getAssignableWorkers().filter(name=>!['Admin','Unassigned'].includes(name)).map((name,index)=>({id:`worker-${index}`,title:name,subtitle:name.includes("Crew")?"Field crew":"Employee",meta:"Available for assignment",status:"active"}));
  if(section==="finance")return getExpenses().map(item=>({id:item.id,title:item.vendor,subtitle:item.notes||item.category,meta:item.date,status:"expense",amount:item.amount}));
  if(section==="reports"||section==="command")return getActivityLogs().slice(0,100).map(item=>({id:item.id,title:item.action,subtitle:item.target,meta:new Date(item.createdAt).toLocaleDateString("en-CA"),status:item.actor||"activity"}));
  return [{id:"company",title:"Company profile",subtitle:"Business name, contact and service area",meta:"General",status:"ready"},{id:"mobile",title:"Mobile application",subtitle:"Updates, navigation and notifications",meta:"Application",status:"ready"},{id:"permissions",title:"Roles and permissions",subtitle:"Admin, Manager and Employee access",meta:"Security",status:"ready"}]
 }catch{return[]}},[section,tick]);
 const statuses=Array.from(new Set(rows.map(row=>row.status)));const visible=rows.filter(row=>(status==="all"||row.status===status)&&`${row.title} ${row.subtitle} ${row.meta}`.toLowerCase().includes(query.toLowerCase()));const total=rows.reduce((sum,row)=>sum+(row.amount||0),0);
 return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin/more"/><div><strong>{config.title}</strong><span>{config.subtitle}</span></div><span className="role-mobile-avatar">{config.icon}</span></header><section className="mobile-native-hero"><span>{config.eyebrow}</span><h1>{rows.length} {config.title.toLowerCase()} in one place.</h1><p>{total?`$${total.toLocaleString("en-CA",{maximumFractionDigits:0})} total value`:"Live operational information"}</p></section><div className="mobile-native-search"><i>⌕</i><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`Search ${config.title.toLowerCase()}`}/>{query&&<button onClick={()=>setQuery("")}>×</button>}</div>{statuses.length>1&&<nav className="mobile-filter-strip"><button className={status==="all"?"active":""} onClick={()=>setStatus("all")}>All <b>{rows.length}</b></button>{statuses.map(value=><button className={status===value?"active":""} onClick={()=>setStatus(value)} key={value}><span>{value}</span><b>{rows.filter(row=>row.status===value).length}</b></button>)}</nav>}<section className="mobile-tool-list">{visible.map(row=><article key={row.id}><i>{config.icon}</i><div><small>{row.meta}</small><strong>{row.title}</strong><span>{row.subtitle}</span></div><em>{row.status}</em>{row.amount!==undefined&&<b>${row.amount.toLocaleString("en-CA",{maximumFractionDigits:0})}</b>}</article>)}{!visible.length&&<div className="mobile-native-empty"><i>⌕</i><strong>No results</strong><p>Try another search or filter.</p></div>}</section><MobileAdminNav active="more"/></main></MobileRoleGuard>
}
