"use client";
import{useEffect,useState}from"react";
import{AdminShell}from"@/components/admin/AdminShell";
import{basePrices,memberships,serviceLabels}from"@/lib/pricing";
import{getSupabaseBrowserClient,isSupabaseConfigured}from"@/lib/supabase/client";

export default function Settings(){
  const rows=Object.entries(basePrices).filter(([k])=>k!=="extra_service");const[code,setCode]=useState("");const[company,setCompany]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function token(){const supabase=getSupabaseBrowserClient()as any;const{data}=await supabase.auth.getSession();return data.session?.access_token as string|undefined}
  useEffect(()=>{if(!isSupabaseConfigured())return;void(async()=>{const access=await token();if(!access)return;const response=await fetch("/api/admin/company",{headers:{authorization:`Bearer ${access}`},cache:"no-store"});const result=await response.json();if(response.ok){setCode(result.company.referral_code||"");setCompany(result.company.name||"")}else setMessage(result.error||"Company settings could not be loaded.")})()},[]);
  async function saveCode(){setBusy(true);setMessage("");try{const access=await token();if(!access)throw new Error("Your session expired. Sign in again.");const response=await fetch("/api/admin/company",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${access}`},body:JSON.stringify({referralCode:code})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Code could not be changed.");setCode(result.company.referral_code);setMessage(result.message)}catch(error){setMessage(error instanceof Error?error.message:"Code could not be changed.")}finally{setBusy(false)}}
  return <AdminShell active="Settings"><div className="app-top"><div><span className="eyebrow">Configuration</span><h1>Settings</h1><p className="section-intro">Company identity, referral code, prices and memberships.</p></div></div><div className="settings-grid"><div className="settings-nav"><a>Company</a><a>Pricing</a><a>Taxes</a><a>Memberships</a><a>Payments</a></div><div className="stack"><section className="card profile-card"><h2>Company referral code</h2><p className="section-intro">Share this code with clients. Quotes using it are routed directly to {company||"your company"}.</p><div className="form-grid"><div className="field"><label>Custom code</label><input className="input" value={code} minLength={4} maxLength={12} onChange={event=>setCode(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="GREENLAWN"/></div></div><small>Use 4–12 letters or numbers. Codes must be unique across the platform.</small><div style={{marginTop:16}}><button className="btn btn-primary" disabled={busy||code.length<4} onClick={()=>void saveCode()}>{busy?"Saving…":"Save company code"}</button></div>{message&&<div className="payment-message" style={{marginTop:16}}>{message}</div>}</section><section className="card profile-card"><h2>Base Prices</h2>{rows.map(([k,v])=><div className="price-row" key={k}><strong>{serviceLabels[k as keyof typeof serviceLabels]}</strong><span>${v}</span><button className="btn btn-outline">Edit</button></div>)}<h2>Memberships</h2>{memberships.map(p=><div className="price-row" key={p.name}><strong>{p.name}</strong><span>${p.price}/mo</span><button className="btn btn-outline">Edit</button></div>)}</section></div></div></AdminShell>
}
