"use client";
import{useEffect,useState}from"react";
import{MobileRoleGuard}from"@/components/mobile/MobileRoleGuard";
import{MobileBackButton}from"@/components/mobile/MobileBackButton";
import{MobileAdminNav}from"@/components/mobile/MobileAdminNav";
import{getSupabaseBrowserClient}from"@/lib/supabase/client";
type Crew={id:string;name:string};type Employee={id:string;full_name:string;email:string;phone?:string|null;active:boolean;crew_id?:string|null};
async function api(options?:RequestInit){const client=getSupabaseBrowserClient()as any;const{data}=await client.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Sign in as Admin to manage employees.");const response=await fetch("/api/admin/users",{...options,headers:{"content-type":"application/json",authorization:`Bearer ${token}`,...(options?.headers||{})}});const result=await response.json();if(!response.ok)throw new Error(result.error||"Employee operation failed.");return result}
export default function MobileEmployees(){
 const[employees,setEmployees]=useState<Employee[]>([]);const[crews,setCrews]=useState<Crew[]>([]);const[selected,setSelected]=useState<Employee|null>(null);const[form,setForm]=useState({fullName:"",email:"",phone:"",crewId:""});const[message,setMessage]=useState("Loading employees...");const[busy,setBusy]=useState(false);
 async function refresh(){try{const result=await api();setEmployees((result.users||[]).filter((user:{role:string})=>user.role==="employee"));setCrews(result.crews||[]);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Employees could not be loaded.")}}
 useEffect(()=>{void refresh()},[]);function open(employee:Employee){setSelected(employee);setForm({fullName:employee.full_name,email:employee.email,phone:employee.phone||"",crewId:employee.crew_id||""})}
 async function save(){if(!selected)return;setBusy(true);try{const result=await api({method:"PATCH",body:JSON.stringify({id:selected.id,...form})});const updated={...selected,...result.user,crew_id:form.crewId};setEmployees(rows=>rows.map(row=>row.id===selected.id?updated:row));setSelected(updated);setMessage("Employee profile saved and synchronized.")}catch(error){setMessage(error instanceof Error?error.message:"Profile could not be saved.")}finally{setBusy(false)}}
 async function toggle(){if(!selected)return;setBusy(true);try{const result=await api({method:"PATCH",body:JSON.stringify({id:selected.id,active:!selected.active})});const updated={...selected,active:result.user.active};setEmployees(rows=>rows.map(row=>row.id===selected.id?updated:row));setSelected(updated);setMessage(`Employee access ${updated.active?"activated":"deactivated"}.`)}catch(error){setMessage(error instanceof Error?error.message:"Access could not be changed.")}finally{setBusy(false)}}
 async function remove(){if(!selected||!window.confirm(`Delete ${selected.full_name}'s access? Completed work and history will remain.`))return;setBusy(true);try{const result=await api({method:"DELETE",body:JSON.stringify({id:selected.id})});setEmployees(rows=>rows.filter(row=>row.id!==selected.id));setSelected(null);setMessage(result.message)}catch(error){setMessage(error instanceof Error?error.message:"Employee could not be deleted.")}finally{setBusy(false)}}
 return <MobileRoleGuard allowed={["admin"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin/more"/><div><strong>Employees</strong><span>Profiles and access</span></div><button className="mobile-native-add mobile-native-check" onClick={()=>void refresh()}>↻</button></header><section className="mobile-native-hero"><span>WORKFORCE</span><h1>{employees.filter(employee=>employee.active).length} active employees.</h1><p>Tap a worker to edit the profile, crew or account access.</p></section>{message&&<div className="mobile-native-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}<section className="mobile-native-route-list">{employees.map((employee,index)=><button type="button" key={employee.id} onClick={()=>open(employee)}><b>{index+1}</b><div><strong>{employee.full_name}</strong><span>{employee.email} · {employee.phone||"No phone"}</span><small>{crews.find(crew=>crew.id===employee.crew_id)?.name||"Unassigned crew"}</small></div><i className={employee.active?"done":""}>{employee.active?"Active":"Inactive"}</i></button>)}{!employees.length&&!message&&<div className="mobile-native-empty"><i>♧</i><strong>No employees</strong><p>Invite an Employee from company users.</p></div>}</section>{selected&&<div className="mobile-native-modal"><button className="mobile-native-scrim" onClick={()=>setSelected(null)}/><section><header><div><span>EMPLOYEE PROFILE</span><h2>{selected.full_name}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><label>Full name<input value={form.fullName} onChange={event=>setForm({...form,fullName:event.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Phone<input value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></label><label>Crew<select value={form.crewId} onChange={event=>setForm({...form,crewId:event.target.value})}><option value="">Unassigned</option>{crews.map(crew=><option value={crew.id} key={crew.id}>{crew.name}</option>)}</select></label><button className="mobile-native-submit" disabled={busy} onClick={()=>void save()}>Save profile</button><div className="mobile-return-actions"><button disabled={busy} onClick={()=>void toggle()}>{selected.active?"Deactivate":"Activate"}</button><button disabled={busy} onClick={()=>void remove()}>Delete employee</button></div></section></div>}<MobileAdminNav active="more"/></main></MobileRoleGuard>
}
