import {readDemoSession} from "@/lib/auth/demoAuth";
import {getEmployeeTasks,getLeads} from "@/lib/storage";
import {getSupabaseBrowserClient,isSupabaseConfigured} from "@/lib/supabase/client";

export type DailyVisit={id:string;propertyId:string;customerId:string;scheduledDate:string;status:string;startedAt:string|null;finishedAt:string|null;durationSeconds:number|null;employeeNotes:string|null;customerVisibleSummary:string|null;customerName:string;address:string;city:string;province:string;serviceName:string;assignedTo:string};
export type DailyTask={id:string;propertyId:string;scheduledDate:string|null;status:string;priority:string;title:string;customerIssue:string;createdAt:string;workStartedAt:string|null;workFinishedAt:string|null;completionSummary:string|null;customerName:string;address:string;city:string;province:string;assignedTo:string};
export type DailyOperations={date:string;summary:{homesTotal:number;homesOpen:number;homesInProgress:number;homesDone:number;homesMissed:number;tasksOpen:number;tasksInProgress:number;tasksDone:number;urgentTasks:number;unassignedHomes:number;unassignedTasks:number};visits:DailyVisit[];tasks:DailyTask[];cities:Array<{city:string;total:number;completed:number;remaining:number}>;assignees:Array<{name:string;total:number;completed:number;inProgress:number;remaining:number}>};

function cityOf(address:string){const parts=address.split(",").map(value=>value.trim()).filter(Boolean);return parts.length>2?parts[parts.length-3]:parts[1]||"Other Ontario"}
function localFallback(date?:string):DailyOperations{
  const day=date||new Date().toISOString().slice(0,10);const leads=getLeads().filter(lead=>(lead.scheduledDate||lead.nextVisitDate)===day);const tasks=getEmployeeTasks().filter(task=>task.scheduledDate===day||!task.scheduledDate);
  const visits:DailyVisit[]=leads.map(lead=>({id:lead.id,propertyId:lead.id,customerId:lead.id,scheduledDate:day,status:lead.status==="completed"?"completed":"scheduled",startedAt:lead.visitStartedAt||null,finishedAt:lead.visitFinishedAt||null,durationSeconds:lead.visitDurationSeconds||null,employeeNotes:lead.notes||null,customerVisibleSummary:null,customerName:lead.name,address:lead.address,city:cityOf(lead.address),province:"ON",serviceName:lead.service,assignedTo:lead.assignedCrew||"Unassigned"}));
  const taskRows:DailyTask[]=tasks.map(task=>({id:task.id,propertyId:task.leadId,scheduledDate:task.scheduledDate||null,status:task.status,priority:task.priority,title:task.title,customerIssue:task.description,createdAt:task.createdAt,workStartedAt:task.workStartedAt||null,workFinishedAt:task.workFinishedAt||null,completionSummary:task.completionSummary||null,customerName:task.customer,address:task.address,city:cityOf(task.address),province:"ON",assignedTo:task.assignedTo||"Unassigned"}));
  const cities=Object.values(visits.reduce<Record<string,{city:string;total:number;completed:number;remaining:number}>>((all,visit)=>{const row=all[visit.city]??={city:visit.city,total:0,completed:0,remaining:0};row.total++;if(visit.status==="completed")row.completed++;else row.remaining++;return all},{}));
  const assignees=Object.values(visits.reduce<Record<string,{name:string;total:number;completed:number;inProgress:number;remaining:number}>>((all,visit)=>{const row=all[visit.assignedTo]??={name:visit.assignedTo,total:0,completed:0,inProgress:0,remaining:0};row.total++;if(visit.status==="completed")row.completed++;else row.remaining++;if(visit.status==="in_progress")row.inProgress++;return all},{}));
  return{date:day,summary:{homesTotal:visits.length,homesOpen:visits.filter(v=>v.status!=="completed").length,homesInProgress:visits.filter(v=>v.status==="in_progress").length,homesDone:visits.filter(v=>v.status==="completed").length,homesMissed:0,tasksOpen:taskRows.filter(t=>["open","assigned","in_progress"].includes(t.status)).length,tasksInProgress:taskRows.filter(t=>t.status==="in_progress").length,tasksDone:taskRows.filter(t=>["completed","resolved"].includes(t.status)).length,urgentTasks:taskRows.filter(t=>t.priority==="urgent"&&!['completed','resolved'].includes(t.status)).length,unassignedHomes:visits.filter(v=>v.assignedTo==="Unassigned"&&v.status!=="completed").length,unassignedTasks:taskRows.filter(t=>t.assignedTo==="Unassigned"&&!['completed','resolved'].includes(t.status)).length},visits,tasks:taskRows,cities,assignees};
}

export function usesLiveDailyOperations(){return isSupabaseConfigured()&&!readDemoSession()}
export async function loadDailyOperations(date?:string):Promise<DailyOperations>{if(!usesLiveDailyOperations())return localFallback(date);const{data,error}=await getSupabaseBrowserClient().rpc("get_live_daily_operations" as never,{p_date:date||null} as never);if(error)throw new Error(error.message);return data as unknown as DailyOperations}
