import {getSupabaseBrowserClient,isSupabaseConfigured} from "@/lib/supabase/client";
import {getLead,getSessionForLead,setPropertyPhoto} from "@/lib/storage";
import {readDemoSession} from "@/lib/auth/demoAuth";

type StoredPhoto={bucket:string;storagePath:string};
type HistoryPhoto=StoredPhoto&{id:string;url:string;type:string;caption:string|null;sortOrder:number;createdAt:string};
export type PropertyPhotoHistory={profilePhotoUrl:string|null;visits:Array<{id:string;scheduled_date:string;status:string;started_at:string|null;finished_at:string|null;duration_seconds:number|null;employee_notes:string|null;customer_visible_summary:string|null;service_name:string;crew_name?:string;rating?:number|null;feedback_comment?:string|null;photos:HistoryPhoto[]}>};

function extension(file:File){const value=file.name.split(".").pop()?.toLowerCase();return value&&/^(avif|heic|heif|jpe?g|png|webp)$/.test(value)?value:"jpg"}
async function signedUrl(bucket:string,path:string){const supabase=getSupabaseBrowserClient();const{data,error}=await supabase.storage.from(bucket).createSignedUrl(path,3600);if(error||!data?.signedUrl)throw new Error(error?.message||"Photo access could not be authorized.");return data.signedUrl}

export async function uploadPropertyProfilePhoto(propertyId:string,file:File){
 if(readDemoSession()||!isSupabaseConfigured()){const url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});if(getLead(propertyId))setPropertyPhoto(propertyId,url);return url}
 const supabase=getSupabaseBrowserClient() as any;const{data:property,error:propertyError}=await supabase.from("properties").select("company_id").eq("id",propertyId).single();if(propertyError)throw new Error(propertyError.message);
 const path=`${property.company_id}/${propertyId}/profile.${extension(file)}`;const{error:uploadError}=await supabase.storage.from("property-photos").upload(path,file,{upsert:true,contentType:file.type||"image/jpeg"});if(uploadError)throw new Error(uploadError.message);
 const{data:user}=await supabase.auth.getUser();await supabase.from("photos").delete().eq("property_id",propertyId).eq("is_profile",true);const{error:photoError}=await supabase.from("photos").insert({organization_id:property.company_id,company_id:property.company_id,property_id:propertyId,uploaded_by:user.user?.id||null,storage_path:path,storage_bucket:"property-photos",public_url:null,photo_type:"property",is_profile:true});if(photoError)throw new Error(photoError.message);
 const{error:updateError}=await supabase.from("properties").update({official_photo_url:null}).eq("id",propertyId);if(updateError)throw new Error(updateError.message);return signedUrl("property-photos",path)
}

export async function getPropertyPhotoHistory(propertyId:string):Promise<PropertyPhotoHistory>{
 if(readDemoSession()||!isSupabaseConfigured()){const lead=getLead(propertyId);const session=getSessionForLead(propertyId);const completed=lead&&(lead.status==="completed"||session?.status==="finished");return{profilePhotoUrl:lead?.propertyPhoto||null,visits:completed?[{id:session?.id||lead.id,scheduled_date:lead.scheduledDate||new Date().toISOString().slice(0,10),status:"completed",started_at:session?.startedAt||lead.visitStartedAt||null,finished_at:session?.finishedAt||lead.visitFinishedAt||null,duration_seconds:session?.durationSeconds||lead.visitDurationSeconds||0,employee_notes:session?.completionComment||null,customer_visible_summary:session?.completionComment||null,service_name:lead.service,crew_name:session?.crew||lead.assignedCrew||"Crew",rating:lead.feedback?.rating||null,feedback_comment:lead.feedback?.comment||null,photos:(lead.photos||[]).map((url,index)=>({id:`${lead.id}-photo-${index}`,bucket:"demo",storagePath:"",url,type:"completion",caption:`Service photo ${index+1}`,sortOrder:index,createdAt:session?.finishedAt||new Date().toISOString()}))}]:[]}}
 const supabase=getSupabaseBrowserClient() as any;const{data:session}=await supabase.auth.getSession();if(!session.session)throw new Error("Your Supabase session expired. Sign in again to view this property history.");const{data,error}=await supabase.rpc("get_property_photo_history",{p_property_id:propertyId});if(error)throw new Error(error.message);
 const raw=data as{profilePhoto:StoredPhoto|null;visits:Array<Omit<PropertyPhotoHistory["visits"][number],"photos">&{photos:Array<Omit<HistoryPhoto,"url">>}>};const profilePhotoUrl=raw.profilePhoto?await signedUrl(raw.profilePhoto.bucket,raw.profilePhoto.storagePath):null;const visits=await Promise.all((raw.visits||[]).map(async visit=>({...visit,photos:await Promise.all((visit.photos||[]).map(async photo=>({...photo,url:await signedUrl(photo.bucket,photo.storagePath)})))})));return{profilePhotoUrl,visits}
}

export async function uploadVisitServicePhotos(visitId:string,files:File[]){const supabase=getSupabaseBrowserClient() as any;const{data:visit,error:visitError}=await supabase.from("visits").select("company_id,property_id").eq("id",visitId).single();if(visitError)throw new Error(visitError.message);const{data:user}=await supabase.auth.getUser();const urls:string[]=[];for(let index=0;index<Math.min(files.length,5);index++){const file=files[index];const path=`${visit.company_id}/${visit.property_id}/${visitId}/${crypto.randomUUID()}.${extension(file)}`;const{error:uploadError}=await supabase.storage.from("work-photos").upload(path,file,{contentType:file.type||"image/jpeg"});if(uploadError)throw new Error(uploadError.message);const{error:rowError}=await supabase.from("photos").insert({organization_id:visit.company_id,company_id:visit.company_id,property_id:visit.property_id,visit_id:visitId,uploaded_by:user.user?.id||null,storage_path:path,storage_bucket:"work-photos",public_url:null,photo_type:"completion",is_profile:false,sort_order:index});if(rowError)throw new Error(rowError.message);urls.push(await signedUrl("work-photos",path))}return urls}
