import {getSupabaseBrowserClient,isSupabaseConfigured} from "@/lib/supabase/client";
import {getLead,setPropertyPhoto} from "@/lib/storage";

export type PropertyPhotoHistory={profilePhotoUrl:string|null;visits:Array<{id:string;scheduled_date:string;status:string;started_at:string|null;finished_at:string|null;duration_seconds:number|null;employee_notes:string|null;customer_visible_summary:string|null;service_name:string;crew_name?:string;photos:Array<{id:string;url:string;type:string;caption:string|null;sortOrder:number;createdAt:string}>}>};

function extension(file:File){const value=file.name.split(".").pop()?.toLowerCase();return value&&/^[a-z0-9]+$/.test(value)?value:"jpg"}
export async function uploadPropertyProfilePhoto(propertyId:string,file:File){
 if(!isSupabaseConfigured()){const url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});if(getLead(propertyId))setPropertyPhoto(propertyId,url);return url}
 const supabase=getSupabaseBrowserClient() as any;const{data:property,error:propertyError}=await supabase.from("properties").select("company_id").eq("id",propertyId).single();if(propertyError)throw new Error(propertyError.message);
 const path=`${property.company_id}/${propertyId}/profile.${extension(file)}`;const{error:uploadError}=await supabase.storage.from("property-photos").upload(path,file,{upsert:true,contentType:file.type||"image/jpeg"});if(uploadError)throw new Error(uploadError.message);
 const{data:urlData}=supabase.storage.from("property-photos").getPublicUrl(path);const url=urlData.publicUrl;
 const{data:user}=await supabase.auth.getUser();await supabase.from("photos").delete().eq("property_id",propertyId).eq("is_profile",true);const{error:photoError}=await supabase.from("photos").insert({organization_id:property.company_id,company_id:property.company_id,property_id:propertyId,uploaded_by:user.user?.id||null,storage_path:path,public_url:url,photo_type:"property",is_profile:true});if(photoError)throw new Error(photoError.message);
 const{error:updateError}=await supabase.from("properties").update({official_photo_url:url}).eq("id",propertyId);if(updateError)throw new Error(updateError.message);return url;
}
export async function getPropertyPhotoHistory(propertyId:string):Promise<PropertyPhotoHistory>{if(!isSupabaseConfigured()){const lead=getLead(propertyId);return{profilePhotoUrl:lead?.propertyPhoto||null,visits:[]}}const supabase=getSupabaseBrowserClient() as any;const{data,error}=await supabase.rpc("get_property_photo_history",{p_property_id:propertyId});if(error)throw new Error(error.message);return data as PropertyPhotoHistory}
export async function uploadVisitServicePhotos(visitId:string,files:File[]){const supabase=getSupabaseBrowserClient() as any;const{data:visit,error:visitError}=await supabase.from("visits").select("company_id,property_id").eq("id",visitId).single();if(visitError)throw new Error(visitError.message);const{data:user}=await supabase.auth.getUser();const urls:string[]=[];for(let index=0;index<Math.min(files.length,5);index++){const file=files[index];const path=`${visit.company_id}/${visit.property_id}/${visitId}/${crypto.randomUUID()}.${extension(file)}`;const{error:uploadError}=await supabase.storage.from("work-photos").upload(path,file,{contentType:file.type||"image/jpeg"});if(uploadError)throw new Error(uploadError.message);const{data:urlData}=supabase.storage.from("work-photos").getPublicUrl(path);const url=urlData.publicUrl;const{error:rowError}=await supabase.from("photos").insert({organization_id:visit.company_id,company_id:visit.company_id,property_id:visit.property_id,visit_id:visitId,uploaded_by:user.user?.id||null,storage_path:path,public_url:url,photo_type:"completion",is_profile:false,sort_order:index});if(rowError)throw new Error(rowError.message);urls.push(url)}return urls}
