"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {PortalShell} from "@/components/admin/PortalShell";
import {EmployeeRouteMap} from "@/components/mobile/EmployeeRouteMap";
import {DAMASIO_SYNC_EVENT,Lead,dayNameFromDate,getEmployeeProfile,getEmployeeTasks,getLeads,hasChecklistToday,seedDemoLeads,updateEmployeeTaskStatus,returnEmployeeTaskToAdmin,simulateCustomerServiceComplete} from "@/lib/storage";
import {loadEmployeeOperationalIdentity} from "@/lib/services/employeeIdentityService";
import {applyEmployeeRouteMapContext,loadEmployeeRouteMapContext,routeDateForWeekday,type EmployeeRouteMapContext} from "@/lib/services/routeMapService";
import {readDemoSession} from "@/lib/auth/demoAuth";
import {isSupabaseConfigured} from "@/lib/supabase/client";
import {changeVisitStatus} from "@/lib/services/schedulingService";
function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function mondayKey(date:Date){const value=new Date(date);value.setDate(value.getDate()-(value.getDay()+6)%7);return dateKey(value)}
function shift(value:string,days:number){const date=new Date(`${value}T12:00:00`);date.setDate(date.getDate()+days);return dateKey(date)}

export default function Employee(){
  const router=useRouter();
  const profile=getEmployeeProfile();const[done,setDone]=useState(true);const[leads,setLeads]=useState<Lead[]>([]);const[crew,setCrew]=useState(profile.crew||"");const[employeeName,setEmployeeName]=useState(profile.name);const[identityError,setIdentityError]=useState("");const[sync,setSync]=useState("");const[filter,setFilter]=useState<"assigned"|"pending"|"completed"|"issues">("assigned");const[notificationOpen,setNotificationOpen]=useState(false);const[notificationSeen,setNotificationSeen]=useState(false);const[mapContext,setMapContext]=useState<EmployeeRouteMapContext>({routeId:null,stops:[]});const[selectedDate,setSelectedDate]=useState(()=>dateKey(new Date()));const[weekStart,setWeekStart]=useState(()=>mondayKey(new Date()));
  function refresh(){const demo=Boolean(readDemoSession())||!isSupabaseConfigured();setDone(demo?hasChecklistToday(employeeName):true);setLeads(demo?getLeads():[]);const raw=demo&&typeof window!=="undefined"?window.localStorage.getItem("damasio_os_last_sync"):"";try{setSync(raw?String(JSON.parse(raw)?.message||""):"")}catch{setSync("")}}
  useEffect(()=>{const demo=Boolean(readDemoSession())||!isSupabaseConfigured();if(demo)seedDemoLeads();refresh();void loadEmployeeOperationalIdentity().then(identity=>{setCrew(identity.crew);setEmployeeName(identity.name);setIdentityError("")}).catch(error=>{setCrew("");setMapContext({routeId:null,stops:[]});setIdentityError(error instanceof Error?error.message:"Employee identity could not be loaded.")});const onSync=()=>refresh();window.addEventListener(DAMASIO_SYNC_EVENT,onSync as EventListener);window.addEventListener("storage",onSync);const t=demo?setInterval(refresh,2500):undefined;return()=>{window.removeEventListener(DAMASIO_SYNC_EVENT,onSync as EventListener);window.removeEventListener("storage",onSync);if(t)clearInterval(t)}},[]);
  const selectedDay=dayNameFromDate(selectedDate);const todayKey=dateKey(new Date());
  const localJobs=useMemo(()=>leads.filter(l=>l.assignedCrew===crew&&(l.scheduledDate===selectedDate||l.nextVisitDate===selectedDate||l.serviceDay===selectedDay)).sort((a,b)=>(a.routeOrder??9999)-(b.routeOrder??9999)||a.address.localeCompare(b.address)),[leads,crew,selectedDate,selectedDay]);
  useEffect(()=>{let cancelled=false;void loadEmployeeRouteMapContext(selectedDate||routeDateForWeekday(selectedDay),crew).then(context=>{if(!cancelled)setMapContext(context)});return()=>{cancelled=true}},[crew,selectedDate,selectedDay]);
  const jobs=useMemo(()=>applyEmployeeRouteMapContext(localJobs,mapContext),[localJobs,mapContext]);
  const demoMode=Boolean(readDemoSession())||!isSupabaseConfigured();
  const tasks=demoMode?getEmployeeTasks().filter(t=>(t.status==="assigned"||t.status==="in_progress")&&(t.assignedTo===employeeName||t.assignedTo===crew)):[];
  const pending=jobs.filter(j=>j.status!=="completed");
  const completed=jobs.filter(j=>j.status==="completed");
  const visible=filter==="pending"?pending:filter==="completed"?completed:jobs;
  const mapVisible=visible;
  const todayLabel=new Date(`${selectedDate}T12:00:00`).toLocaleDateString([],{weekday:"long",month:"long",day:"numeric",year:"numeric"});
  const dayOptions=useMemo(()=>Array.from({length:7},(_,index)=>{const date=new Date(`${weekStart}T12:00:00`);date.setDate(date.getDate()+index);return{key:dateKey(date),weekday:date.toLocaleDateString("en-CA",{weekday:"short"}),day:date.getDate()}}),[weekStart]);
  const weekLabel=`${new Date(`${weekStart}T12:00:00`).toLocaleDateString("en-CA",{month:"short",day:"numeric"})} – ${new Date(`${shift(weekStart,6)}T12:00:00`).toLocaleDateString("en-CA",{month:"short",day:"numeric"})}`;
  function moveWeek(days:-7|7){setWeekStart(value=>shift(value,days));setSelectedDate(value=>shift(value,days))}
  const unreadIssues=notificationSeen?0:tasks.length;
  return <PortalShell type="Employee" active="Today">
    {identityError&&<div className="notice" style={{marginBottom:20}}><strong>Employee access blocked.</strong> {identityError}</div>}
    <div className="neo-hero employee-hero"><div><span className="eyebrow">Field App</span><h1>{todayLabel}</h1><p>{crew} private route. Employees only see their assigned homes and service issues — no other crews, prices, invoices, payments or financial reports.</p></div><div className="row"><Link className="btn btn-primary" href="/employee/route">Open Route</Link><Link className="btn btn-outline" href="/employee/route?view=map">Open Map</Link></div></div>
    <section className="employee-desktop-week employee-week-picker"><div><button type="button" onClick={()=>moveWeek(-7)} aria-label="Previous week">‹</button><strong>{weekLabel}</strong><button type="button" onClick={()=>moveWeek(7)} aria-label="Next week">›</button></div><nav className="employee-day-strip">{dayOptions.map(item=><button key={item.key} className={selectedDate===item.key?"active":item.key<todayKey?"past":""} onClick={()=>setSelectedDate(item.key)}><span>{item.weekday}</span><strong>{item.day}</strong>{item.key===todayKey&&<i>Today</i>}</button>)}</nav></section>
    <div className="employee-inline-notifications"><button className="btn btn-outline" onClick={()=>{setNotificationOpen(!notificationOpen);setNotificationSeen(true)}}>Notifications {unreadIssues>0&&<span className="notification-badge inline">{unreadIssues}</span>}</button>{notificationOpen&&<div className="notification-popover"><strong>Current notifications</strong>{tasks.length===0?<p>No notifications right now.</p>:tasks.map(t=><p key={t.id}>• {t.title} — {t.customer}</p>)}</div>}</div>
    {!done&&<div className="notice" style={{marginBottom:20}}>Daily checklist required before route. <Link href="/employee/checklist"><strong>Open Checklist</strong></Link></div>}
    <section className="status-action-grid">
      <button className={filter==="assigned"?"status-action blue active":"status-action blue"} onClick={()=>setFilter("assigned")}><i>⌘</i><b>{jobs.length}</b><div><strong>Assigned</strong><span>{crew}</span></div><em>›</em></button>
      <button className={filter==="pending"?"status-action yellow active":"status-action yellow"} onClick={()=>setFilter("pending")}><i>!</i><b>{pending.length}</b><div><strong>Pending</strong><span>Route order only</span></div><em>›</em></button>
      <button className={filter==="completed"?"status-action green active":"status-action green"} onClick={()=>setFilter("completed")}><i>✓</i><b>{completed.length}</b><div><strong>Completed</strong><span>Good job</span></div><em>›</em></button>
      <button className={filter==="issues"?"status-action red active":"status-action red"} onClick={()=>setFilter("issues")}><i>♢</i><b>{tasks.length}</b><div><strong>Issues</strong><span>Need return</span></div><em>›</em></button>
    </section>
    <section className="card calendar-work-card"><div className="calendar-work-head"><div><h2>{filter==="issues"?"Service Issues":`${crew} ${filter}`}</h2><span>{todayLabel}</span></div><div className="row"><span className="privacy-pill">Private route</span><Link className="btn btn-outline" href="/employee/photos">Add Photos</Link></div></div>{filter==="issues"?<div className="task-list">{tasks.length===0?<div className="empty-state"><strong>No open issues.</strong><p>Return tasks will appear here.</p></div>:tasks.map(t=><div className="task-card" key={t.id}><h3>{t.title}</h3><p><strong>{t.customer}</strong><br/>{t.address}</p><p>{t.description}</p><div className="row"><Link className="btn btn-primary" href={`/employee/property/${t.leadId}`}>Open Property</Link><button className="btn btn-outline" onClick={()=>{if(window.confirm("Return this task to Admin so it can be reassigned?")){returnEmployeeTaskToAdmin(t.id);refresh()}}}>Return for Admin</button><button className="btn btn-outline" onClick={()=>{if(window.confirm("Are you sure this task is complete? It will be removed from your list and sent to Admin for final Resolve.")){const note=window.prompt("What did you complete at this property?", "Return visit completed and customer issue fixed."); if(note!==null){updateEmployeeTaskStatus(t.id,"completed",note,"Employee");refresh()}}}}>Mark Completed</button></div></div>)}</div>:<div className="pro-route-list">{visible.length===0?<div className="empty-state"><strong>No homes in this view.</strong><p>When Admin publishes or changes your route, it appears here automatically.</p></div>:visible.map((j,i)=><div className="pro-route-row" key={j.id}><span className="route-number">{i+1}</span><div className="home-thumb"><div></div></div><div className="home-info"><strong>{j.name}</strong><p>{j.address}</p><span className={j.serviceFrequency==="biweekly"?"freq bi":"freq"}>{j.serviceFrequency||"weekly"}</span></div><div className="crew-cell"><div className="crew-faces"><i></i><i></i></div><strong>{crew}</strong><p>No fixed visit hours</p></div><div className="booking-cell"><span className="dot booked"></span><strong>{j.status}</strong><p>Next: {j.nextVisitDate||j.scheduledDate||"—"}</p></div><Link className="open-btn" href={`/employee/property/${j.id}`}>Open</Link><button className="dots" onClick={()=>{if(window.confirm("Are you sure you want to mark this service as completed?")){simulateCustomerServiceComplete(j.id);refresh()}}}>✓</button></div>)}</div>}</section>
    {filter!=="issues"&&<section className="card employee-browser-map-card"><div className="calendar-work-head"><div><h2>My Route Map</h2><span>{employeeName} · {crew} · {jobs.length} visits</span></div><span className="privacy-pill">My route only</span></div><EmployeeRouteMap route={mapVisible} routeId={mapContext.routeId||undefined} desktop onOpenVisit={lead=>router.push(`/employee/route?property=${lead.id}`)}/></section>}
    <p className="section-intro" style={{marginTop:16}}>Last Admin update: {sync||"No changes yet"}</p>
  </PortalShell>
}
