"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {PortalShell} from "@/components/admin/PortalShell";
import {DAMASIO_SYNC_EVENT,Lead,getEmployeeTasks,getLeads,hasChecklistToday,seedDemoLeads,updateEmployeeTaskStatus,returnEmployeeTaskToAdmin,simulateCustomerServiceComplete} from "@/lib/storage";

export default function Employee(){
  const[done,setDone]=useState(true);const[leads,setLeads]=useState<Lead[]>([]);const[crew]=useState("Crew A");const[sync,setSync]=useState("");const[filter,setFilter]=useState<"assigned"|"pending"|"completed"|"issues">("assigned");const[notificationOpen,setNotificationOpen]=useState(false);const[notificationSeen,setNotificationSeen]=useState(false);
  function refresh(){setDone(hasChecklistToday("Filipe"));setLeads(getLeads());const raw=typeof window!=="undefined"?window.localStorage.getItem("damasio_os_last_sync"):"";setSync(raw?JSON.parse(raw).message:"")}
  useEffect(()=>{seedDemoLeads();refresh();const onSync=()=>refresh();window.addEventListener(DAMASIO_SYNC_EVENT,onSync as EventListener);window.addEventListener("storage",onSync);const t=setInterval(refresh,2500);return()=>{window.removeEventListener(DAMASIO_SYNC_EVENT,onSync as EventListener);window.removeEventListener("storage",onSync);clearInterval(t)}},[]);
  const jobs=useMemo(()=>leads.filter(l=>l.assignedCrew===crew).sort((a,b)=>(a.serviceDay||"").localeCompare(b.serviceDay||"")||a.address.localeCompare(b.address)),[leads,crew]);
  const tasks=getEmployeeTasks().filter(t=>(t.status==="assigned"||t.status==="in_progress")&&(t.assignedTo==="Filipe"||t.assignedTo===crew));
  const pending=jobs.filter(j=>j.status!=="completed");
  const completed=jobs.filter(j=>j.status==="completed");
  const visible=filter==="pending"?pending:filter==="completed"?completed:jobs;
  const currentDay=jobs[0]?.serviceDay||new Date().toLocaleDateString([], {weekday:"long"});
  function dateForDay(day:string){const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];const now=new Date();const current=(now.getDay()+6)%7;const target=days.indexOf(day);const d=new Date(now);if(target>=0)d.setDate(now.getDate()+target-current);return d.toLocaleDateString([], {weekday:"long", month:"long", day:"numeric", year:"numeric"});}
  const todayLabel=dateForDay(currentDay);
  const unreadIssues=notificationSeen?0:tasks.length;
  return <PortalShell type="Employee" active="Today">
    <div className="neo-hero employee-hero"><div><span className="eyebrow">Field App</span><h1>{todayLabel}</h1><p>{crew} private route. Employees only see their assigned homes and service issues — no other crews, prices, invoices, payments or financial reports.</p></div><Link className="btn btn-primary" href="/employee/route">Open Route</Link></div>
    <div className="employee-inline-notifications"><button className="btn btn-outline" onClick={()=>{setNotificationOpen(!notificationOpen);setNotificationSeen(true)}}>Notifications {unreadIssues>0&&<span className="notification-badge inline">{unreadIssues}</span>}</button>{notificationOpen&&<div className="notification-popover"><strong>Current notifications</strong>{tasks.length===0?<p>No notifications right now.</p>:tasks.map(t=><p key={t.id}>• {t.title} — {t.customer}</p>)}</div>}</div>
    {!done&&<div className="notice" style={{marginBottom:20}}>Daily checklist required before route. <Link href="/employee/checklist"><strong>Open Checklist</strong></Link></div>}
    <section className="status-action-grid">
      <button className={filter==="assigned"?"status-action blue active":"status-action blue"} onClick={()=>setFilter("assigned")}><i>⌘</i><b>{jobs.length}</b><div><strong>Assigned</strong><span>{crew}</span></div><em>›</em></button>
      <button className={filter==="pending"?"status-action yellow active":"status-action yellow"} onClick={()=>setFilter("pending")}><i>!</i><b>{pending.length}</b><div><strong>Pending</strong><span>Route order only</span></div><em>›</em></button>
      <button className={filter==="completed"?"status-action green active":"status-action green"} onClick={()=>setFilter("completed")}><i>✓</i><b>{completed.length}</b><div><strong>Completed</strong><span>Good job</span></div><em>›</em></button>
      <button className={filter==="issues"?"status-action red active":"status-action red"} onClick={()=>setFilter("issues")}><i>♢</i><b>{tasks.length}</b><div><strong>Issues</strong><span>Need return</span></div><em>›</em></button>
    </section>
    <section className="card calendar-work-card"><div className="calendar-work-head"><div><h2>{filter==="issues"?"Service Issues":`${crew} ${filter}`}</h2><span>{todayLabel}</span></div><div className="row"><span className="privacy-pill">Private route</span><Link className="btn btn-outline" href="/employee/photos">Add Photos</Link></div></div>{filter==="issues"?<div className="task-list">{tasks.length===0?<div className="empty-state"><strong>No open issues.</strong><p>Return tasks will appear here.</p></div>:tasks.map(t=><div className="task-card" key={t.id}><h3>{t.title}</h3><p><strong>{t.customer}</strong><br/>{t.address}</p><p>{t.description}</p><div className="row"><Link className="btn btn-primary" href={`/employee/property/${t.leadId}`}>Open Property</Link><button className="btn btn-outline" onClick={()=>{if(window.confirm("Return this task to Admin so it can be reassigned?")){returnEmployeeTaskToAdmin(t.id);refresh()}}}>Return for Admin</button><button className="btn btn-outline" onClick={()=>{if(window.confirm("Are you sure this task is complete? It will be removed from your list and sent to Admin for final Resolve.")){const note=window.prompt("What did you complete at this property?", "Return visit completed and customer issue fixed."); if(note!==null){updateEmployeeTaskStatus(t.id,"completed",note,"Employee");refresh()}}}}>Mark Completed</button></div></div>)}</div>:<div className="pro-route-list">{visible.length===0?<div className="empty-state"><strong>No homes in this view.</strong><p>When Admin publishes or changes your route, it appears here automatically.</p></div>:visible.map((j,i)=><div className="pro-route-row" key={j.id}><span className="route-number">{i+1}</span><div className="home-thumb"><div></div></div><div className="home-info"><strong>{j.name}</strong><p>{j.address}</p><span className={j.serviceFrequency==="biweekly"?"freq bi":"freq"}>{j.serviceFrequency||"weekly"}</span></div><div className="crew-cell"><div className="crew-faces"><i></i><i></i></div><strong>{crew}</strong><p>No fixed visit hours</p></div><div className="booking-cell"><span className="dot booked"></span><strong>{j.status}</strong><p>Next: {j.nextVisitDate||j.scheduledDate||"—"}</p></div><Link className="open-btn" href={`/employee/property/${j.id}`}>Open</Link><button className="dots" onClick={()=>{if(window.confirm("Are you sure you want to mark this service as completed?")){simulateCustomerServiceComplete(j.id);refresh()}}}>✓</button></div>)}</div>}</section>
    <p className="section-intro" style={{marginTop:16}}>Last Admin update: {sync||"No changes yet"}</p>
  </PortalShell>
}
