"use client";
import {useEffect,useState} from "react";
import {PortalShell} from "@/components/admin/PortalShell";
import {CustomerPaymentProfile,getCustomerPaymentProfile,getInvoices,saveCustomerPaymentProfile} from "@/lib/storage";

export default function CustomerPayments(){
  const[profile,setProfile]=useState<CustomerPaymentProfile|null>(null);const[message,setMessage]=useState("");
  useEffect(()=>setProfile(getCustomerPaymentProfile()),[]);if(!profile)return <PortalShell type="Customer" active="Payments"><div className="card profile-card">Loading payments…</div></PortalShell>;
  const due=getInvoices().filter(invoice=>invoice.status!=="paid").reduce((sum,invoice)=>sum+invoice.total,0);
  function save(patch:Partial<CustomerPaymentProfile>){setProfile(saveCustomerPaymentProfile(patch));setMessage("Payment preference saved.")}
  return <PortalShell type="Customer" active="Payments"><div className="app-top"><div><span className="eyebrow">Billing setup</span><h1>Payments</h1><p className="section-intro">Choose the preferred source for approved invoices. Charging remains disabled until secure Stripe confirmation, webhooks and the service contract are finalized.</p></div></div><div className="stats"><div className="card dash-card"><div className="mini-label">Verified balance</div><div className="mini-value">${profile.balance.toFixed(2)}</div></div><div className="card dash-card"><div className="mini-label">Open invoices</div><div className="mini-value">${due.toFixed(2)}</div></div></div><section className="card profile-card" style={{marginTop:20}}><h2>Preferred payment source</h2><div className="payment-grid"><button className={profile.primaryMethod==="stripe"?"payment-option active":"payment-option"} onClick={()=>save({primaryMethod:"stripe"})}><strong>Stripe card / bank</strong><small>Preference only. Card details will be collected by Stripe when checkout is enabled.</small></button><button className={profile.primaryMethod==="account_balance"?"payment-option active":"payment-option"} onClick={()=>save({primaryMethod:"account_balance"})}><strong>Account balance</strong><small>Use verified deposited funds first.</small></button></div><label className="check-card" style={{marginTop:16}}><input type="checkbox" checked={profile.automaticPayments} onChange={e=>save({automaticPayments:e.target.checked})}/> Save automatic-payment preference (charging is not active)</label></section><section className="card profile-card" style={{marginTop:20}}><h2>Account balance deposits</h2><p className="section-intro">Deposits are unavailable until identity checks and the payment provider are connected. The system will never create a test balance on a real account.</p><button className="btn btn-outline" disabled>Deposits not yet available</button></section>{message&&<div className="payment-message" style={{marginTop:16}}>{message}</div>}</PortalShell>
}
