"use client";
import {useEffect,useState} from "react";
import {PortalShell} from "@/components/admin/PortalShell";
import {CustomerPaymentProfile,getCustomerPaymentProfile,getInvoices,saveCustomerPaymentProfile} from "@/lib/storage";

export default function CustomerPayments(){
  const[profile,setProfile]=useState<CustomerPaymentProfile|null>(null);const[deposit,setDeposit]=useState("100");const[message,setMessage]=useState("");
  useEffect(()=>setProfile(getCustomerPaymentProfile()),[]);if(!profile)return <PortalShell type="Customer" active="Payments"><div className="card profile-card">Loading payments…</div></PortalShell>;
  const due=getInvoices().filter(invoice=>invoice.status!=="paid").reduce((sum,invoice)=>sum+invoice.total,0);
  function save(patch:Partial<CustomerPaymentProfile>){setProfile(saveCustomerPaymentProfile(patch));setMessage("Payment preference saved.")}
  function addBalance(){const amount=Math.max(0,Number(deposit||0));if(!amount)return;const current=getCustomerPaymentProfile();setProfile(saveCustomerPaymentProfile({balance:current.balance+amount}));setMessage(`Test deposit of $${amount.toFixed(2)} added. A real deposit provider will be connected before launch.`)}
  return <PortalShell type="Customer" active="Payments"><div className="app-top"><div><span className="eyebrow">Billing setup</span><h1>Payments</h1><p className="section-intro">Choose the primary source for approved invoices. Automatic charging remains disabled until the service contract and payment authorization are finalized.</p></div></div><div className="stats"><div className="card dash-card"><div className="mini-label">Account balance</div><div className="mini-value">${profile.balance.toFixed(2)}</div></div><div className="card dash-card"><div className="mini-label">Open invoices</div><div className="mini-value">${due.toFixed(2)}</div></div></div><section className="card profile-card" style={{marginTop:20}}><h2>Primary payment source</h2><div className="payment-grid"><button className={profile.primaryMethod==="stripe"?"payment-option active":"payment-option"} onClick={()=>save({primaryMethod:"stripe"})}><strong>Stripe card / bank</strong><small>Tokenized checkout; no card number stored by Damasio OS.</small></button><button className={profile.primaryMethod==="account_balance"?"payment-option active":"payment-option"} onClick={()=>save({primaryMethod:"account_balance"})}><strong>Account balance</strong><small>Use deposited funds first.</small></button></div><label className="check-card" style={{marginTop:16}}><input type="checkbox" checked={profile.automaticPayments} onChange={e=>save({automaticPayments:e.target.checked})}/> Remember automatic payment authorization (structure only; charging disabled)</label></section><section className="card profile-card" style={{marginTop:20}}><h2>Add account balance</h2><div className="row"><input className="input" type="number" min="1" value={deposit} onChange={e=>setDeposit(e.target.value)}/><button className="btn btn-primary" onClick={addBalance}>Test deposit</button></div></section>{message&&<div className="payment-message" style={{marginTop:16}}>{message}</div>}</PortalShell>
}
