"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Dispute={id:string;message?:string;status:string;created_at:string;response_due_at?:string|null;company_response?:string|null;company_responded_at?:string|null;customer_decision?:string|null;master_resolution?:string|null};
async function token(){const client=getSupabaseBrowserClient() as any;const{data}=await client.auth.getSession();const value=data.session?.access_token;if(!value)throw new Error("Your Customer session expired.");return value;}
function nice(value?:string|null){return value?new Date(value).toLocaleString("en-CA",{dateStyle:"medium",timeStyle:"short"}):"—";}

export function CustomerPaymentDisputeBox({visitId}:{visitId:string}){
 const[dispute,setDispute]=useState<Dispute|null>(null);const[open,setOpen]=useState(false);const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 async function refresh(){try{const access=await token();const response=await fetch(`/api/customer/payment-disputes?visitId=${encodeURIComponent(visitId)}`,{headers:{authorization:`Bearer ${access}`},cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Dispute status could not be loaded.");setDispute(result.dispute||null);}catch(error){setMessage(error instanceof Error?error.message:"Dispute status could not be loaded.");}}
 useEffect(()=>{void refresh();},[visitId]);
 async function submit(){if(reason.trim().length<5){setMessage("Please explain what is wrong with this payment.");return;}setBusy(true);try{const access=await token();const response=await fetch("/api/customer/payment-disputes",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${access}`},body:JSON.stringify({action:"open",visitId,reason})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Payment dispute could not be opened.");setOpen(false);setReason("");setMessage(result.duplicate?"A dispute for this payment is already open.":"Payment dispute opened. The company has 3 days to respond, and the platform can see the case.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Payment dispute could not be opened.");}finally{setBusy(false);}}
 async function decide(decision:"accepted"|"insist"){if(!dispute)return;setBusy(true);try{const access=await token();const response=await fetch("/api/customer/payment-disputes",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${access}`},body:JSON.stringify({action:"decision",disputeId:dispute.id,decision})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Decision could not be saved.");setMessage(decision==="insist"?"The dispute was escalated to the platform for Master review.":"The company response was accepted and the dispute was closed.");await refresh();}catch(error){setMessage(error instanceof Error?error.message:"Decision could not be saved.");}finally{setBusy(false);}}
 const overdue=Boolean(dispute?.status==="pending"&&dispute.response_due_at&&new Date(dispute.response_due_at).getTime()<Date.now());
 return <section className="customer-payment-dispute-box">
   {!dispute?<><button type="button" className="customer-dispute-toggle" onClick={()=>setOpen(v=>!v)}>Contest payment</button>{open&&<div className="customer-dispute-form"><strong>Payment issue</strong><p>Use this only for a charge connected to this completed service. The company must respond within 3 days.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what happened…"/><button disabled={busy} onClick={()=>void submit()}>{busy?"Sending…":"Submit dispute"}</button></div>}</>:<div className={`customer-dispute-status ${overdue||dispute.status==="escalated"?"urgent":""}`}><header><strong>Payment dispute</strong><span>{dispute.status==="company_responded"?"Waiting for your decision":dispute.status==="escalated"?"Master review":dispute.status==="resolved"?"Resolved":overdue?"Company response overdue":"Pending company response"}</span></header><p>{dispute.message}</p><small>Opened {nice(dispute.created_at)} · Company deadline {nice(dispute.response_due_at)}</small>{dispute.company_response&&<div className="customer-company-response"><b>Company response</b><p>{dispute.company_response}</p><small>{nice(dispute.company_responded_at)}</small></div>}{dispute.status==="company_responded"&&<div className="customer-dispute-actions"><button disabled={busy} onClick={()=>void decide("accepted")}>Accept response</button><button className="danger" disabled={busy} onClick={()=>void decide("insist")}>I still dispute this payment</button></div>}{dispute.status==="escalated"&&<div className="customer-master-note">The platform has been alerted and can review the case.</div>}</div>}
   {message&&<div className="customer-dispute-message">{message}</div>}
   <style jsx global>{`.customer-payment-dispute-box{display:grid;gap:9px}.customer-dispute-toggle{justify-self:start;border:1px solid #d0ddd6;border-radius:11px;background:#fff;padding:9px 12px;color:#8a2c24;font-weight:850;cursor:pointer}.customer-dispute-form,.customer-dispute-status{display:grid;gap:8px;padding:13px;border:1px solid #dce7e1;border-radius:14px;background:#fff}.customer-dispute-form p,.customer-dispute-status p{margin:0;color:#596d63;font-size:12px;line-height:1.5}.customer-dispute-form textarea{min-height:82px;border:1px solid #cadbd2;border-radius:10px;padding:9px}.customer-dispute-form>button{min-height:42px;border:0;border-radius:10px;background:#0b7046;color:#fff;font-weight:900}.customer-dispute-status.urgent{border-color:#e49a94;background:#fffafa}.customer-dispute-status>header{display:flex;justify-content:space-between;gap:10px}.customer-dispute-status>header span{font-size:10px;font-weight:900;color:#8a2c24}.customer-dispute-status>small,.customer-company-response small{color:#718078;font-size:10px}.customer-company-response{padding:10px;border-left:3px solid #0b7046;background:#f4f9f6}.customer-company-response p{margin:4px 0}.customer-dispute-actions{display:flex;gap:8px;flex-wrap:wrap}.customer-dispute-actions button{min-height:40px;border:1px solid #bfd4c9;border-radius:10px;background:#edf8f2;color:#0b684c;font-weight:850;padding:0 12px}.customer-dispute-actions button.danger{border-color:#efb4ad;background:#fff0f0;color:#a62a20}.customer-master-note,.customer-dispute-message{padding:9px 10px;border-radius:10px;background:#fff5df;color:#78510a;font-size:11px}@media(max-width:640px){.customer-dispute-actions{display:grid}.customer-dispute-status>header{flex-direction:column}}`}</style>
 </section>;
}
