"use client";
import {useMemo} from "react";
import Link from "next/link";
import {AdminShell} from "@/components/admin/AdminShell";
import {getLeads,getEmployeeTasks,getInvoices,getExpenses} from "@/lib/storage";
function money(n:number){return `$${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
export default function SaaSPage(){
  const data=useMemo(()=>{const leads=getLeads();const invoices=getInvoices();const expenses=getExpenses();const tasks=getEmployeeTasks();const active=leads.filter(l=>l.status!=="lost").length;const revenue=leads.filter(l=>l.paymentStatus==="paid"||l.status==="completed").reduce((s,l)=>s+(l.total||0),0)+invoices.filter(i=>i.status==="paid").reduce((s,i)=>s+(i.total||0),0);const cost=expenses.reduce((s,e)=>s+e.amount,0);return{active,revenue,cost,profit:revenue-cost,openTasks:tasks.filter(t=>t.status!=="resolved").length,health:active>0?Math.max(72,Math.min(98,Math.round(100-(tasks.filter(t=>t.status!=="resolved").length/active*8)))):100}},[]);
  const plans=[{name:"Starter",price:149,for:"Solo operator",features:"CRM, schedule, customer portal"},{name:"Growth",price:299,for:"Small crew",features:"Dispatch, routes, feedback, tasks"},{name:"Pro",price:599,for:"Multi-crew company",features:"Finance, AI, audit, advanced reports"}];
  return <AdminShell active="SaaS"><div className="app-top"><div><span className="eyebrow">V46 SaaS Foundation</span><h1>SaaS Control Center</h1><p className="section-intro">Base comercial para planos, empresas, limites e prontidão multiempresa.</p></div><Link className="btn btn-primary" href="/admin/settings">Company Settings</Link></div>
  <section className="business-metrics"><div className="business-metric"><span>Readiness</span><strong>{data.health}%</strong><small>operational quality score</small></div><div className="business-metric"><span>Active Customers</span><strong>{data.active}</strong><small>eligible for subscription value</small></div><div className="business-metric"><span>MRR Target</span><strong>{money(299)}</strong><small>default Growth plan</small></div><div className="business-metric warn"><span>Open Issues</span><strong>{data.openTasks}</strong><small>fix before onboarding companies</small></div></section>
  <div className="grid-2" style={{marginTop:20}}><section className="card table-card"><div className="table-head"><div><h2>Subscription Plans</h2><p className="section-intro">Commercial packaging draft for the Canadian landscaping market.</p></div></div><div className="table-wrap"><table><thead><tr><th>Plan</th><th>Monthly</th><th>Best for</th><th>Included</th></tr></thead><tbody>{plans.map(p=><tr key={p.name}><td><strong>{p.name}</strong></td><td>{money(p.price)}</td><td>{p.for}</td><td>{p.features}</td></tr>)}</tbody></table></div></section>
  <section className="card table-card"><div className="table-head"><div><h2>Multi-company Checklist</h2><p className="section-intro">These rules protect the product before SaaS expansion.</p></div></div><div className="stack"><div className="visit-row"><span className="dot booked"></span><div><strong>Company data isolation</strong><p>Every record must belong to one company account.</p></div><span className="pill">Required</span></div><div className="visit-row"><span className="dot booked"></span><div><strong>Role-based permissions</strong><p>Admin, dispatcher, employee and customer access stay separated.</p></div><span className="pill">Required</span></div><div className="visit-row"><span className="dot upcoming"></span><div><strong>Plan limits</strong><p>Employees, customers, AI and storage can be limited by plan.</p></div><span className="pill">Draft</span></div></div></section></div></AdminShell>
}
