import type {Metadata} from "next";
import {Header} from "@/components/layout/Header";
import {Footer} from "@/components/layout/Footer";

export const metadata:Metadata={title:"Privacy Policy | 4Ever Seasons",description:"Privacy information for the 4Ever Seasons website, quote forms and customer portal."};

export default function PrivacyPage(){return <><Header/><main className="public-page"><section className="public-page-hero"><div className="public-page-shell"><span className="public-page-kicker">Privacy Policy</span><h1>How we handle information you share with us.</h1><p className="public-page-lead">Last updated August 22, 2026. This policy is a practical summary for our website, quote requests and account features.</p></div></section><section><div className="public-page-shell legal-copy">
<section><h2>1. Information we collect</h2><p>Depending on how you use 4Ever Seasons, we may collect your name, email address, phone number, service address, property details, service preferences, quote information, messages, account details and records connected to scheduled or completed services.</p></section>
<section><h2>2. How we use information</h2><p>We use information to respond to inquiries, prepare quotes, organize property and service details, schedule and deliver services, operate customer and staff account features, provide support, maintain records and protect the security and reliability of our systems.</p></section>
<section><h2>3. Payments</h2><p>When online payment features are used, payment information may be processed by a payment service provider rather than stored directly by 4Ever Seasons. We may retain transaction references, amounts, invoice status and related service records needed to operate the account.</p></section>
<section><h2>4. Service providers</h2><p>We may use trusted providers for website hosting, authentication, email delivery, database services, mapping, payment processing and other technical functions. They receive only the information reasonably needed to provide those services.</p></section>
<section><h2>5. Cookies and local device data</h2><p>Our site and portals may use essential cookies, browser storage or similar technologies to keep you signed in, remember interface state, protect sessions and operate core features. If additional analytics or measurement tools are introduced, this policy should be updated to describe them.</p></section>
<section><h2>6. Retention and security</h2><p>We keep information for as long as reasonably needed for service delivery, account administration, recordkeeping, security and legal or operational requirements. We use reasonable technical and organizational safeguards, but no internet service can guarantee absolute security.</p></section>
<section><h2>7. Your choices</h2><p>You may contact us to ask about information associated with you, request corrections or discuss deletion where appropriate and permitted. Some records may need to be retained for legitimate business, security, payment or legal reasons.</p></section>
<section><h2>8. Contact</h2><p>Questions about privacy can be sent to <a href="mailto:support@4everseasons.com"><strong>support@4everseasons.com</strong></a>.</p></section>
<section><h2>9. Updates</h2><p>We may update this policy as our services or website change. The date at the top of this page will be revised when material changes are published.</p></section>
</div></section></main><Footer/></>}
