"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Scope = "company" | "master";
type Dispute = {
  id:string; company_id?:string; customer_id?:string; visit_id?:string; invoice_id?:string; payment_id?:string;
  message?:string; status:string; created_at:string; response_due_at?:string|null; company_response?:string|null;
  company_responded_at?:string|null; customer_decision?:string|null; customer_decision_at?:string|null;
  master_resolution?:string|null; overdue?:boolean;
  company?:{name?:string;contact_email?:string}|null; customer?:{full_name?:string;email?:string}|null;
  invoice?:{invoice_number?:string;total?:number}|null; payment?:{amount?:number;paid_at?:string}|null;
};

async function accessToken(){const client=getSupabaseBrowserClient() as any;const{data}=await client.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Your session expired. Sign in again.");return token;}
function money(value?:number){return new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(Number(value||0));}
function deadline(value?:string|null){if(!value)return"—";return new Date(value).toLocaleString("en-CA",{dateStyle:"medium",timeStyle:"short"});}
function statusLabel(row:Dispute){if(row.status==="pending"&&row.response_due_at&&new Date(row.response_due_at).getTime()<Date.now())return"Overdue";if(row.status==="company_responded")return"Waiting customer";if(row.status==="escalated")return"Master review";if(row.status==="resolved")return"Resolved";return"Pending company";}

export function PaymentDisputeWorkspace({scope}:{scope:Scope}){
  const[rows,setRows]=useState<Dispute[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[reply,setReply]=useState<Record<string,string>>({});const[busy,setBusy]=useState("");
  const endpoint=scope==="master"?"/api/master/payment-disputes":"/api/admin/payment-disputes";
  async function refresh(){try{setLoading(true);const token=await accessToken();const response=await fetch(endpoint,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Payment disputes could not be loaded.");setRows(result.disputes||[]);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Payment disputes could not be loaded.");}finally{setLoading(false);}}
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),30000);return()=>window.clearInterval(timer);},[scope]);
  const openCount=useMemo(()=>rows.filter(row=>!["resolved","cancelled"].includes(row.status)).length,[rows]);
  const urgentCount=useMemo(()=>rows.filter(row=>row.status==="escalated"||(row.status==="pending"&&row.response_due_at&&new Date(row.response_due_at).getTime()<Date.now())).length,[rows]);
  async function respond(row:Dispute){const text=String(reply[row.id]||"").trim();if(text.length<5){setMessage("Write a response of at least 5 characters.");return;}setBusy(row.id);try{const token=await accessToken();const response=await fetch("/api/admin/payment-disputes",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({disputeId:row.id,response:text})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Response could not be saved.");setReply(current=>({...current,[row.id]:""}));await refresh();setMessage("Company response saved. The customer can now accept it or escalate the dispute to Master.");}catch(error){setMessage(error instanceof Error?error.message:"Response could not be saved.");}finally{setBusy("");}}
  return <section className="payment-disputes-workspace">
    <header className="pdw-head"><div><span>PAYMENT DISPUTES</span><h2>{scope==="master"?"Platform oversight":"Customer payment disputes"}</h2><p>{scope==="master"?"Every dispute is visible to Master. Overdue or customer-escalated cases require platform attention.":"Respond within 3 days. The payout stays held while the dispute remains open."}</p></div><div className="pdw-kpis"><b>{openCount}<small>open</small></b><b className={urgentCount?"urgent":""}>{urgentCount}<small>urgent</small></b></div></header>
    {message&&<div className="pdw-message">{message}</div>}
    <div className="pdw-list">{loading?<div className="pdw-empty">Loading payment disputes…</div>:rows.length===0?<div className="pdw-empty">No payment disputes.</div>:rows.map(row=>{const overdue=row.status==="pending"&&row.response_due_at&&new Date(row.response_due_at).getTime()<Date.now();return <article key={row.id} className={overdue||row.status==="escalated"?"urgent":""}>
      <header><div><strong>{row.invoice?.invoice_number||"Paid invoice"} · {money(row.invoice?.total||row.payment?.amount)}</strong><span>{scope==="master"?`${row.company?.name||"Company"} · `:""}{row.customer?.full_name||"Customer"}</span></div><em>{statusLabel(row)}</em></header>
      <p className="pdw-reason">“{row.message||"No reason supplied."}”</p>
      <div className="pdw-meta"><span>Opened <b>{deadline(row.created_at)}</b></span><span>Company deadline <b>{deadline(row.response_due_at)}</b></span>{overdue&&<span className="danger">3-day response window expired</span>}</div>
      {row.company_response&&<div className="pdw-response"><span>Company response</span><p>{row.company_response}</p><small>{deadline(row.company_responded_at)}</small></div>}
      {row.customer_decision&&<div className="pdw-response"><span>Customer decision</span><p>{row.customer_decision==="insist"?"Customer rejected the company response and requested Master review.":"Customer accepted the company response."}</p></div>}
      {scope==="company"&&!["company_responded","escalated","resolved"].includes(row.status)&&<div className="pdw-reply"><textarea value={reply[row.id]||""} onChange={event=>setReply(current=>({...current,[row.id]:event.target.value}))} placeholder="Explain what happened and how the company will resolve it."/><button disabled={busy===row.id} onClick={()=>void respond(row)}>{busy===row.id?"Saving…":"Send response"}</button></div>}
      {scope==="master"&&(overdue||row.status==="escalated")&&<div className="pdw-master-alert"><b>Master attention required</b><span>{overdue?"Company did not respond within 3 days.":"Customer insists after the company response."}</span></div>}
    </article>})}</div>
    <style jsx global>{`.payment-disputes-workspace{display:grid;gap:12px;margin-top:18px}.pdw-head{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:18px;border:1px solid #dce7e1;border-radius:20px;background:#fff}.pdw-head span{color:#0b7655;font-size:10px;font-weight:950;letter-spacing:.12em}.pdw-head h2{margin:4px 0;color:#173a2c}.pdw-head p{margin:0;color:#6b7c73;font-size:13px}.pdw-kpis{display:flex;gap:8px}.pdw-kpis>b{display:grid;min-width:70px;padding:10px;border-radius:14px;background:#edf8f2;color:#0b684c;text-align:center;font-size:22px}.pdw-kpis>b.urgent{background:#fff0f0;color:#b42318}.pdw-kpis small{font-size:9px;text-transform:uppercase}.pdw-message{padding:11px 13px;border-radius:12px;background:#edf8f2;color:#176344}.pdw-list{display:grid;gap:10px}.pdw-list>article{display:grid;gap:10px;padding:15px;border:1px solid #dce7e1;border-radius:18px;background:#fff}.pdw-list>article.urgent{border-color:#ef9a9a;box-shadow:0 0 0 2px rgba(196,45,45,.06)}.pdw-list article>header{display:flex;justify-content:space-between;gap:12px}.pdw-list article>header strong,.pdw-list article>header span{display:block}.pdw-list article>header span{margin-top:3px;color:#718078;font-size:12px}.pdw-list article>header em{align-self:start;padding:6px 9px;border-radius:999px;background:#f0f5f2;color:#315848;font-style:normal;font-size:10px;font-weight:900}.pdw-reason{margin:0;padding:10px 12px;border-radius:11px;background:#f7faf8;color:#3f594d}.pdw-meta{display:flex;gap:12px;flex-wrap:wrap;color:#718078;font-size:11px}.pdw-meta b{color:#2e4e40}.pdw-meta .danger{color:#b42318;font-weight:900}.pdw-response{padding:11px;border-left:3px solid #0b7655;background:#f5faf7}.pdw-response span{font-size:9px;font-weight:950;color:#0b7655;text-transform:uppercase}.pdw-response p{margin:4px 0;color:#345144}.pdw-response small{color:#718078}.pdw-reply{display:grid;grid-template-columns:1fr auto;gap:8px}.pdw-reply textarea{min-height:76px;resize:vertical;border:1px solid #cadbd2;border-radius:12px;padding:10px;color:#173a2c}.pdw-reply button{min-width:140px;border:0;border-radius:12px;background:#0b7046;color:#fff;font-weight:900}.pdw-master-alert{display:grid;gap:2px;padding:10px 12px;border-radius:12px;background:#fff0f0;color:#9f261e}.pdw-empty{padding:24px;border:1px dashed #cbdad2;border-radius:16px;text-align:center;color:#718078}@media(max-width:680px){.pdw-head,.pdw-list article>header{align-items:stretch;flex-direction:column}.pdw-kpis{width:100%}.pdw-kpis>b{flex:1}.pdw-reply{grid-template-columns:1fr}.pdw-reply button{min-height:48px}}`}</style>
  </section>;
}
