"use client";
import{useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{AdminShell}from"@/components/admin/AdminShell";
import{Lead,LeadStatus,getLeads,seedDemoLeads,updateLeadStatus,createManualCustomer,broadcastOperationsChange}from"@/lib/storage";

const cols:[LeadStatus,string][]=[["new","NEW"],["booked","BOOKED"],["quoted","QUOTED"],["lost","LOST"],["completed","COMPLETED"]];
const nextStep:Record<LeadStatus,LeadStatus>={new:"booked",booked:"quoted",quoted:"completed",lost:"new",completed:"booked"};
const stepLabel:Record<LeadStatus,string>={new:"Book",booked:"Quote",quoted:"Complete",lost:"Reopen",completed:"Rebook"};

export default function Leads(){
  const[leads,setLeads]=useState<Lead[]>([]);
  const[active,setActive]=useState<LeadStatus|"all">("all");
  const[form,setForm]=useState({name:"",phone:"",email:"",address:"",service:"Lawn Maintenance",source:"Google"});
  const[msg,setMsg]=useState("");
  function r(){setLeads(getLeads())}
  useEffect(()=>{seedDemoLeads();r()},[]);
  const counts=useMemo(()=>cols.map(([c,label])=>({status:c,label,count:leads.filter(l=>l.status===c).length})),[leads]);
  const visible=useMemo(()=>active==="all"?leads:leads.filter(l=>l.status===active),[leads,active]);
  function add(){if(!form.name||!form.address){setMsg("Add at least name and address.");return}createManualCustomer({name:form.name,phone:form.phone,email:form.email,address:form.address,service:form.service,subtotal:0,tax:0,total:0,notes:`Lead source: ${form.source}`});setForm({name:"",phone:"",email:"",address:"",service:"Lawn Maintenance",source:"Google"});setMsg("Lead added to NEW.");r()}
  function move(id:string,status:LeadStatus){updateLeadStatus(id,status);broadcastOperationsChange(`Lead moved to ${status}.`);setMsg(`Lead moved to ${status.toUpperCase()}.`);r()}
  return <AdminShell active="CRM">
    <div className="app-top"><div><span className="eyebrow">CRM & Sales</span><h1>Lead Pipeline</h1><p className="section-intro">Functional pipeline buttons: NEW, BOOKED, QUOTED, LOST and COMPLETED. Click a status to filter, then move leads with one click.</p></div><Link className="btn btn-primary" href="/admin/estimates/new">Create Estimate</Link></div>
    <section className="card profile-card"><h2>Quick Add Lead</h2><div className="form-grid"><input className="input" placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" placeholder="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><select className="input" value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option>Lawn Maintenance</option><option>Mulch Installation</option><option>Spring Cleanup</option><option>Fall Cleanup</option><option>Snow Removal</option></select><select className="input" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option>Google</option><option>Facebook</option><option>Referral</option><option>Door Hanger</option><option>Website</option></select></div><button className="btn btn-primary" style={{marginTop:14}} onClick={add}>Add Lead</button>{msg&&<div className="payment-message">{msg}</div>}</section>
    <div className="pipeline-stats functional-tabs"><button className={active==="all"?"pipeline-stat active":"pipeline-stat"} onClick={()=>setActive("all")}><strong>{leads.length}</strong><span>ALL</span></button>{counts.map(c=><button className={active===c.status?"pipeline-stat active":"pipeline-stat"} key={c.status} onClick={()=>setActive(c.status)}><strong>{c.count}</strong><span>{c.label}</span></button>)}</div>
    <section className="card table-card" style={{marginBottom:18}}><div className="table-head"><div><h2>{active==="all"?"All Pipeline Items":`${active.toUpperCase()} Items`}</h2><p className="section-intro">Every action updates local data immediately and syncs the rest of the dashboard.</p></div><span className="pill">{visible.length} item(s)</span></div><div className="table-wrap"><table><thead><tr><th>Lead</th><th>Service</th><th>Status</th><th>Move</th><th>Open</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan={5}>No leads in this status.</td></tr>:visible.map(l=><tr key={l.id}><td><strong>{l.name}</strong><br/><small>{l.address}</small></td><td>{l.service}</td><td><span className="status">{l.status.toUpperCase()}</span></td><td><div className="row wrap">{cols.map(([s,label])=><button key={s} className={l.status===s?"btn btn-primary btn-small":"btn btn-outline btn-small"} onClick={()=>move(l.id,s)}>{label}</button>)}</div></td><td><Link className="btn btn-outline" href={`/admin/customers/${l.id}`}>Open</Link></td></tr>)}</tbody></table></div></section>
    <div className="kanban business-kanban">{cols.map(([c,label])=><div className="kanban-col" key={c}><div className="kanban-title">{label}</div>{leads.filter(l=>l.status===c).map(l=><div className="lead-card lead-card-pro" key={l.id}><div className="lead-top"><strong>{l.name}</strong><span>{l.notes?.includes("Lead source")?l.notes.replace("Lead source: ",""):"Customer"}</span></div><small>{l.service}</small><p>{l.address}</p><div className="row wrap"><button className="btn btn-primary btn-small" onClick={()=>move(l.id,nextStep[l.status])}>{stepLabel[l.status]}</button><select className="input" value={l.status} onChange={e=>move(l.id,e.target.value as LeadStatus)}><option value="new">New</option><option value="booked">Booked</option><option value="quoted">Quoted</option><option value="lost">Lost</option><option value="completed">Completed</option></select><Link className="btn btn-outline btn-small" href={`/admin/customers/${l.id}`}>Open</Link></div></div>)}</div>)}</div>
  </AdminShell>
}
