"use client";
import { createId } from "@/lib/id";
import { useMemo, useState } from "react";
import { calculateQuote, serviceLabels, ServiceKey, type QuoteSizeKey } from "@/lib/pricing";
import { saveLead } from "@/lib/storage";
const services: { key: ServiceKey; note?: string }[] = [{key:"weekly_lawn"},{key:"biweekly_lawn"},{key:"one_time_lawn"},{key:"spring_cleanup",note:"Seasonal extra charge"},{key:"fall_cleanup",note:"Seasonal extra charge"},{key:"snow_removal"},{key:"extra_service",note:"Custom quote later"}];
type Size = QuoteSizeKey;
export function QuoteWizard(){
 const [step,setStep]=useState(1); const [service,setService]=useState<ServiceKey>("weekly_lawn"); const [size,setSize]=useState<Size>("medium"); const [annual,setAnnual]=useState(false); const [backyard,setBackyard]=useState(true); const [gated,setGated]=useState(false); const [lead,setLead]=useState({name:"",phone:"",email:"",address:"",notes:""});
 const isExtra=service==="extra_service"; const quote=useMemo(()=>calculateQuote({service,size,annual,backyard,gated}),[service,size,annual,backyard,gated]);
 function submitLead(){saveLead({id:createId(),createdAt:new Date().toISOString(),...lead,service:serviceLabels[service],status:isExtra?"new":"quoted",subtotal:isExtra?0:quote.subtotal,tax:isExtra?0:quote.tax,total:isExtra?0:quote.total});setStep(4)}
 return <div className="card quote-card"><div className="quote-head"><h2>Instant Quote</h2><span className="pill">Step {step}/4</span></div>
 {step===1&&<div className="stack"><strong>What service do you need?</strong><div className="option-grid">{services.map(item=><button key={item.key} className={service===item.key?"option active":"option"} onClick={()=>setService(item.key)}><strong>{serviceLabels[item.key]}</strong>{item.note&&<small>{item.note}</small>}</button>)}</div><button className="btn btn-primary" onClick={()=>setStep(2)}>Next</button></div>}
 {step===2&&<div className="stack"><div className="field"><label>Property address</label><input className="input" value={lead.address} onChange={e=>setLead({...lead,address:e.target.value})} placeholder="123 Main St, Hamilton, ON"/></div>{!isExtra?<><div className="field"><label>Property size</label><select className="input" value={size} onChange={e=>setSize(e.target.value as Size)}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option><option value="xlarge">Extra Large</option></select></div><div className="row"><button className="btn btn-outline" onClick={()=>setBackyard(!backyard)}>Backyard: {backyard?"Yes":"No"}</button><button className="btn btn-outline" onClick={()=>setGated(!gated)}>Gate: {gated?"Yes":"No"}</button><button className="btn btn-outline" onClick={()=>setAnnual(!annual)}>Annual: {annual?"Yes":"No"}</button></div></>:<div className="field"><label>Tell us what you need</label><textarea className="input" style={{minHeight:120}} value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})} placeholder="Describe the extra service. We will send a custom quote."/></div>}<div className="row"><button className="btn btn-outline" onClick={()=>setStep(1)}>Back</button><button className="btn btn-primary" onClick={()=>setStep(3)}>Next</button></div></div>}
 {step===3&&<div className="stack"><strong>Almost done. Where should we send your quote?</strong><input className="input" placeholder="Full name" value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})}/><input className="input" placeholder="Phone" value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/><input className="input" placeholder="Email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/><div className="row"><button className="btn btn-outline" onClick={()=>setStep(2)}>Back</button><button className="btn btn-primary" onClick={submitLead}>Show Quote</button></div></div>}
 {step===4&&<div className="stack">{isExtra?<div className="quote-result"><small>Request received</small><div className="quote-price">Saved</div><p>We will review the request and send a custom quote.</p></div>:<div className="quote-result"><small>Your estimated quote</small><div className="quote-price">${quote.total.toFixed(2)}</div><p>Subtotal ${quote.subtotal.toFixed(2)} + HST ${quote.tax.toFixed(2)}</p></div>}<div className="row"><button className="btn btn-primary">Credit / Debit</button><button className="btn btn-outline">e-Transfer</button><button className="btn btn-outline">Cash / Cheque</button></div></div>}</div>
}
