import type {Metadata} from "next";
import {Header} from "@/components/layout/Header";
import {Footer} from "@/components/layout/Footer";

export const metadata:Metadata={title:"Terms | 4 Ever Seasons",description:"Terms for use of the 4 Ever Seasons website, quote tools and customer portal."};

export default function TermsPage(){return <><Header/><main className="public-page"><section className="public-page-hero"><div className="public-page-shell"><span className="public-page-kicker">Terms</span><h1>Website and service terms.</h1><p className="public-page-lead">Last updated August 22, 2026. These terms provide a basic framework for use of our website, quote tools and account features. Specific service agreements or approved quotes may contain additional terms.</p></div></section><section><div className="public-page-shell legal-copy">
<section><h2>1. Using this website</h2><p>You may use the 4 Ever Seasons website and portals for lawful purposes related to quotes, property care, account access, scheduling, service information and support. Do not attempt to interfere with the site, access another customer&apos;s information or misuse account features.</p></section>
<section><h2>2. Quotes and estimates</h2><p>Online quote tools and preliminary estimates are intended to help organize service scope and expected pricing. A quote may require review, confirmation of property details or an on-site assessment before it becomes a final service commitment.</p></section>
<section><h2>3. Scheduling and weather</h2><p>Property-care work can be affected by weather, site conditions, access, safety and seasonal demand. Scheduled dates or arrival windows may need to change when conditions make the planned work impractical or unsafe. When possible, updated scheduling information will be communicated through the normal service channels.</p></section>
<section><h2>4. Customer responsibilities</h2><p>Customers are responsible for providing accurate property and contact information, identifying access restrictions or known hazards, and ensuring we can reasonably access the areas included in the agreed service scope.</p></section>
<section><h2>5. Payments</h2><p>Where payment features are available, charges and invoice details should match the applicable quote, service record or account statement. Third-party payment providers may apply their own terms to payment processing. Any service-specific deposit, cancellation or refund rules should be confirmed in the applicable quote or agreement rather than assumed from this general website page.</p></section>
<section><h2>6. Accounts and access</h2><p>You are responsible for keeping your login information secure and for activity performed through your account. Contact us promptly if you believe your account or email access has been compromised.</p></section>
<section><h2>7. Website content</h2><p>The text, branding, interface and original materials on this website are provided for use with 4 Ever Seasons services and may not be copied or used in a misleading way without permission. Third-party names, maps, payment tools and other external services remain subject to their respective owners&apos; rights.</p></section>
<section><h2>8. Availability and limitations</h2><p>We work to keep the website and portals reliable, but online services can experience maintenance, provider outages or technical errors. The site is provided on a reasonable-efforts basis and should not be treated as an emergency communication channel.</p></section>
<section><h2>9. Changes</h2><p>We may update these terms as website features or service processes change. Material updates will be reflected by the date shown at the top of this page.</p></section>
<section><h2>10. Contact</h2><p>Questions about these terms can be sent to <a href="mailto:support@4everseasons.com"><strong>support@4everseasons.com</strong></a>.</p></section>
</div></section></main><Footer/></>}
