"use client";
import {createId} from "@/lib/id";
import {useEffect,useMemo,useState} from "react";
import {AdminShell} from "@/components/admin/AdminShell";
import {getSupabaseBrowserClient,isSupabaseConfigured} from "@/lib/supabase/client";

type Role="admin"|"manager"|"employee"|"customer";
type AccessLevel="none"|"view"|"manage";
type ManagerModule="customers"|"properties"|"quotes"|"jobs"|"schedule"|"dispatch"|"routes"|"employees"|"tasks"|"feedback"|"reports"|"finance"|"settings";
type ManagerPermissions=Record<ManagerModule,AccessLevel>;
type LocalUser={id:string;full_name:string;email:string;role:Role;phone?:string;active:boolean;created_at:string;manager_permissions?:ManagerPermissions};
const KEY="damasio_os_v411_users";
const modules:ManagerModule[]=["customers","properties","quotes","jobs","schedule","dispatch","routes","employees","tasks","feedback","reports","finance","settings"];
const defaultManagerPermissions=Object.fromEntries(modules.map(m=>[m,m==="finance"||m==="settings"?"none":"view"])) as ManagerPermissions;
const demo:LocalUser[]=[
 {id:"u1",full_name:"Filipe Damasio",email:"admin@damasioos.demo",role:"admin",active:true,created_at:new Date().toISOString()},
 {id:"u2",full_name:"Field Employee",email:"employee@damasioos.demo",role:"employee",active:true,created_at:new Date().toISOString()},
 {id:"u3",full_name:"Customer Demo",email:"customer@damasioos.demo",role:"customer",active:true,created_at:new Date().toISOString()}
];
function loadUsers(){if(typeof window==="undefined")return demo;const raw=localStorage.getItem(KEY);if(!raw){localStorage.setItem(KEY,JSON.stringify(demo));return demo}try{return JSON.parse(raw) as LocalUser[]}catch{return demo}}
function saveUsers(users:LocalUser[]){localStorage.setItem(KEY,JSON.stringify(users))}

export default function UsersPage(){
 const[users,setUsers]=useState<LocalUser[]>([]);const[fullName,setFullName]=useState("");const[email,setEmail]=useState("");const[phone,setPhone]=useState("");const[role,setRole]=useState<Role>("employee");const[msg,setMsg]=useState("");const[managerPermissions,setManagerPermissions]=useState<ManagerPermissions>(defaultManagerPermissions);const[editing,setEditing]=useState<string>("");
 useEffect(()=>{setUsers(loadUsers())},[]);
 const counts=useMemo(()=>({admins:users.filter(u=>u.role==="admin").length,managers:users.filter(u=>u.role==="manager").length,employees:users.filter(u=>u.role==="employee").length,customers:users.filter(u=>u.role==="customer").length}),[users]);
 function setPermission(module:ManagerModule,level:AccessLevel){setManagerPermissions({...managerPermissions,[module]:level})}
 async function createUser(){if(!fullName||!email){setMsg("Full name and email are required.");return}if(role==="admin"&&users.some(u=>u.role==="admin"&&u.active)){setMsg("Each company can have only one active Admin. Add this person as Manager instead.");return}const row:LocalUser={id:createId(),full_name:fullName,email,phone,role,active:true,created_at:new Date().toISOString(),manager_permissions:role==="manager"?managerPermissions:undefined};const next=[row,...users];setUsers(next);saveUsers(next);setFullName("");setEmail("");setPhone("");setRole("employee");setManagerPermissions(defaultManagerPermissions);if(isSupabaseConfigured()){try{const supabase=getSupabaseBrowserClient() as any;const {error}=await supabase.from("profiles").insert({full_name:row.full_name,email:row.email,phone:row.phone,role:row.role,active:true,manager_permissions:row.manager_permissions});setMsg(error?`Saved locally. Supabase profile insert needs auth user id: ${error.message}`:"User saved to Supabase profile table.")}catch(err){setMsg(err instanceof Error?`Saved locally. Supabase: ${err.message}`:"Saved locally. Supabase insert failed.")}}else setMsg("User saved in local demo mode. Configure Supabase to save real users.")}
 function toggle(id:string){const next=users.map(u=>u.id===id?{...u,active:!u.active}:u);setUsers(next);saveUsers(next)}
 function saveExistingManager(user:LocalUser){const next=users.map(u=>u.id===user.id?{...u,manager_permissions:managerPermissions}:u);setUsers(next);saveUsers(next);setEditing("");setMsg(`Permissions saved for ${user.full_name}.`)}
 function startEdit(user:LocalUser){setEditing(user.id);setManagerPermissions(user.manager_permissions||defaultManagerPermissions)}
 const editor=(onSave:()=>void)=><div className="manager-permissions"><div className="table-head"><div><h3>Manager Access</h3><p className="section-intro">Choose No Access, View Only or Manage for every area.</p></div><button className="btn btn-primary" onClick={onSave}>Save Permissions</button></div>{modules.map(module=><div className="manager-permission-row" key={module}><strong>{module[0].toUpperCase()+module.slice(1)}</strong><div className="segmented-access">{(["none","view","manage"] as AccessLevel[]).map(level=><button type="button" key={level} className={managerPermissions[module]===level?"active":""} onClick={()=>setPermission(module,level)}>{level==="none"?"No Access":level==="view"?"View Only":"Manage"}</button>)}</div></div>)}</div>;
 return <AdminShell active="Users"><div className="business-hero"><div><span className="eyebrow">V51.2 Roles & Permissions</span><h1>Company users and access</h1><p>Each company has one Admin. Managers receive only the modules and access levels selected by that Admin.</p></div></div><section className="business-metrics"><div className="business-metric"><span>Admin</span><strong>{counts.admins}</strong><small>One company owner</small></div><div className="business-metric"><span>Managers</span><strong>{counts.managers}</strong><small>Custom permissions</small></div><div className="business-metric"><span>Employees</span><strong>{counts.employees}</strong><small>Field access only</small></div><div className="business-metric"><span>Customers</span><strong>{counts.customers}</strong><small>Own properties only</small></div></section><section className="card table-card" style={{marginTop:20}}><div className="table-head"><div><h2>Create user</h2><p className="section-intro">Select Manager to configure exactly what this person can see or manage.</p></div></div><div className="form-grid four"><label>Full name<input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Name"/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@company.com"/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="905..."/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="admin">Admin</option><option value="manager">Manager</option><option value="employee">Employee</option><option value="customer">Customer</option></select></label></div>{role==="manager"&&editor(()=>setMsg("Choose permissions, then click Create User."))}<button className="btn btn-primary" onClick={createUser}>Create User</button>{msg&&<p className="auth-message inline">{msg}</p>}</section><section className="card table-card" style={{marginTop:20}}><div className="table-head"><div><h2>Workspace users</h2><p className="section-intro">Managers cannot promote themselves, remove the Admin or access hidden modules.</p></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td><span className="pill">{u.role}</span></td><td>{u.active?"Active":"Inactive"}</td><td><div className="row">{u.role==="manager"&&<button className="btn btn-outline dark-safe" onClick={()=>startEdit(u)}>Permissions</button>}<button className="btn btn-outline dark-safe" onClick={()=>toggle(u.id)}>{u.active?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table></div>{editing&&<div style={{marginTop:18}}>{editor(()=>saveExistingManager(users.find(u=>u.id===editing)!))}</div>}</section></AdminShell>
}
