"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {loadDailyOperations,type DailyOperations,type DailyVisit} from "@/lib/services/dailyOperationsService";

function visitStatus(status:string){return status==="completed"?"Done":status==="in_progress"?"In progress":status==="missed"?"Needs reschedule":"Open"}
function workerInitial(name:string){return (name||"E").trim().slice(0,1).toUpperCase()}

export default function MobileCommandCenter(){
  const[board,setBoard]=useState<DailyOperations|null>(null);const[error,setError]=useState("");const[selectedWorker,setSelectedWorker]=useState("");
  useEffect(()=>{let active=true;const refresh=()=>void loadDailyOperations().then(data=>{if(active){setBoard(data);setError("");setSelectedWorker(current=>data.assignees.some(item=>item.name===current)?current:"")}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Today overview could not be loaded."));refresh();const timer=window.setInterval(refresh,5000);return()=>{active=false;window.clearInterval(timer)}},[]);
  const summary=board?.summary;
  const visitsByWorker=useMemo(()=>{const map=new Map<string,DailyVisit[]>();for(const visit of board?.visits||[]){const key=visit.assignedTo||"Unassigned";const list=map.get(key)||[];list.push(visit);map.set(key,list)}return map},[board]);
  return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage mobile-command-live"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>Today</strong><span>Team and route progress</span></div><span className="role-mobile-avatar">⌁</span></header><section className="mobile-native-hero"><span>LIVE · {board?.date||"TODAY"}</span><h1>{summary?.homesOpen||0} houses still need attention.</h1><p>{board?.assignees.length||0} workers · {summary?.homesDone||0} completed · {summary?.homesInProgress||0} in progress</p></section>{error&&<div className="mobile-native-message">{error}</div>}
    <section className="mobile-command-metrics"><Link href="/mobile/admin/status/open"><span>Open homes</span><strong>{summary?.homesOpen||0}</strong><small>{summary?.unassignedHomes||0} unassigned</small></Link><Link href="/mobile/admin/status/done"><span>Completed</span><strong>{summary?.homesDone||0}</strong><small>of {summary?.homesTotal||0} today</small></Link><Link href="/mobile/admin/tasks"><span>Open tasks</span><strong>{summary?.tasksOpen||0}</strong><small>{summary?.urgentTasks||0} urgent</small></Link><Link href="/mobile/admin/routes"><span>Workers</span><strong>{board?.assignees.length||0}</strong><small>active routes today</small></Link></section>
    <div className="customer-section-head"><div><span>TEAM TODAY</span><h2>Daily progress</h2></div><small>Tap a worker</small></div><section className="mobile-command-progress mobile-command-workers">{board?.assignees.map(item=>{const visits=visitsByWorker.get(item.name)||[];const percent=item.total?Math.round(item.completed/item.total*100):0;const open=selectedWorker===item.name;return <article key={item.name} className={open?"open":""}><button type="button" className="mobile-command-worker-toggle" onClick={()=>setSelectedWorker(current=>current===item.name?"":item.name)}><span className="mobile-command-worker-avatar">{workerInitial(item.name)}</span><span className="mobile-command-worker-copy"><strong>{item.name}</strong><small>{item.completed}/{item.total} done · {item.remaining} remaining</small></span><b>{percent}%</b><i>{open?"⌃":"⌄"}</i></button><div className="mobile-command-worker-bar"><i style={{width:`${percent}%`}}/></div>{open&&<div className="mobile-command-worker-detail"><div className="mobile-command-worker-actions"><Link href={`/mobile/admin/employees?employee=${encodeURIComponent(item.name)}`}>Open profile</Link><Link href="/mobile/admin/routes">Adjust route</Link></div><div className="mobile-command-worker-houses">{visits.map((visit,index)=><Link href={`/mobile/admin/customers/${visit.propertyId}`} key={visit.id}><b>{index+1}</b><span><strong>{visit.address||"Property"}</strong><small>{visit.customerName} · {visit.serviceName}</small></span><em className={visit.status==="completed"?"done":visit.status==="in_progress"?"active":""}>{visitStatus(visit.status)}</em></Link>)}{!visits.length&&<p>No houses assigned to this worker today.</p>}</div></div>}</article>})}{!board?.assignees.length&&<div className="mobile-native-empty"><i>⌁</i><strong>No visits today</strong><p>Scheduled work will appear here.</p></div>}</section>
    <div className="customer-section-head"><div><span>ONTARIO</span><h2>Progress by city</h2></div></div><section className="mobile-command-cities">{board?.cities.map(city=><article key={city.city}><div><strong>{city.city}</strong><span>{city.total} houses</span></div><b>{city.completed} done</b><em>{city.remaining} open</em></article>)}</section>
    <div className="customer-section-head"><div><span>ATTENTION</span><h2>Urgent tasks</h2></div><Link href="/mobile/admin/tasks">See all</Link></div><section className="mobile-command-tasks">{board?.tasks.filter(task=>task.priority==="urgent"&&!['completed','resolved'].includes(task.status)).slice(0,5).map(task=><Link href="/mobile/admin/tasks" key={task.id}><i>!</i><div><strong>{task.title}</strong><span>{task.customerName} · {task.city}</span><small>{task.assignedTo} · {task.status}</small></div><b>›</b></Link>)}{!summary?.urgentTasks&&<div className="role-mobile-clear"><i>✓</i><span><strong>No urgent tasks</strong><small>The priority list is clear.</small></span></div>}</section><MobileAdminNav active="home"/></main></MobileRoleGuard>
}
