"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {loadDailyOperations,type DailyOperations} from "@/lib/services/dailyOperationsService";

export default function MobileCommandCenter(){
  const[board,setBoard]=useState<DailyOperations|null>(null);const[error,setError]=useState("");
  useEffect(()=>{let active=true;const refresh=()=>void loadDailyOperations().then(data=>{if(active){setBoard(data);setError("")}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Command Center could not be loaded."));refresh();const timer=window.setInterval(refresh,5000);return()=>{active=false;window.clearInterval(timer)}},[]);
  const summary=board?.summary;
  return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage mobile-command-live"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>Command</strong><span>Live daily operation</span></div><span className="role-mobile-avatar">⌁</span></header><section className="mobile-native-hero"><span>LIVE · {board?.date||"TODAY"}</span><h1>{summary?.homesOpen||0} houses still need attention.</h1><p>{summary?.homesDone||0} completed · {summary?.homesInProgress||0} in progress · {summary?.tasksOpen||0} tasks open</p></section>{error&&<div className="mobile-native-message">{error}</div>}
    <section className="mobile-command-metrics"><Link href="/mobile/admin/status/open"><span>Open homes</span><strong>{summary?.homesOpen||0}</strong><small>{summary?.unassignedHomes||0} unassigned</small></Link><Link href="/mobile/admin/status/done"><span>Completed</span><strong>{summary?.homesDone||0}</strong><small>of {summary?.homesTotal||0} today</small></Link><Link href="/mobile/admin/tasks"><span>Open tasks</span><strong>{summary?.tasksOpen||0}</strong><small>{summary?.urgentTasks||0} urgent</small></Link><Link href="/mobile/admin/tasks"><span>Tasks done</span><strong>{summary?.tasksDone||0}</strong><small>{summary?.tasksInProgress||0} in progress</small></Link></section>
    <div className="customer-section-head"><div><span>BY WORKER / CREW</span><h2>Daily progress</h2></div></div><section className="mobile-command-progress">{board?.assignees.map(item=><article key={item.name}><header><strong>{item.name}</strong><span>{item.completed}/{item.total} done</span></header><div><i style={{width:`${item.total?Math.round(item.completed/item.total*100):0}%`}}/></div><small>{item.inProgress} in progress · {item.remaining} remaining</small></article>)}{!board?.assignees.length&&<div className="mobile-native-empty"><i>⌁</i><strong>No visits today</strong><p>Scheduled work will appear here.</p></div>}</section>
    <div className="customer-section-head"><div><span>ONTARIO</span><h2>Progress by city</h2></div></div><section className="mobile-command-cities">{board?.cities.map(city=><article key={city.city}><div><strong>{city.city}</strong><span>{city.total} houses</span></div><b>{city.completed} done</b><em>{city.remaining} open</em></article>)}</section>
    <div className="customer-section-head"><div><span>ATTENTION</span><h2>Urgent tasks</h2></div><Link href="/mobile/admin/tasks">See all</Link></div><section className="mobile-command-tasks">{board?.tasks.filter(task=>task.priority==="urgent"&&!['completed','resolved'].includes(task.status)).slice(0,5).map(task=><Link href="/mobile/admin/tasks" key={task.id}><i>!</i><div><strong>{task.title}</strong><span>{task.customerName} · {task.city}</span><small>{task.assignedTo} · {task.status}</small></div><b>›</b></Link>)}{!summary?.urgentTasks&&<div className="role-mobile-clear"><i>✓</i><span><strong>No urgent tasks</strong><small>The priority list is clear.</small></span></div>}</section><MobileAdminNav active="home"/></main></MobileRoleGuard>
}
