import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";

export const dynamic = "force-dynamic";

const bodySchema=z.object({fullName:z.string().trim().min(2).max(120),phone:z.string().trim().max(40).nullable().optional(),addressLine1:z.string().trim().max(240).nullable().optional(),city:z.string().trim().max(120).nullable().optional(),province:z.string().trim().max(40).nullable().optional(),postalCode:z.string().trim().max(20).nullable().optional(),routeStartAddress:z.string().trim().max(400).nullable().optional(),avatarUrl:z.string().trim().url().nullable().optional()}).strict();
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Employee profile is not configured.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})as any}
async function employee(request:NextRequest){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)throw new Error("Sign in as Employee.");const supabase=client();const{data:auth,error:authError}=await supabase.auth.getUser(token);if(authError||!auth.user)throw new Error("Your session expired.");const{data:profile,error}=await supabase.from("profiles").select("*").eq("id",auth.user.id).eq("role","employee").single();if(error||!profile?.active)throw new Error("Active Employee profile not found.");return{supabase,profile}}
export async function GET(request:NextRequest){try{const{profile}=await employee(request);return NextResponse.json({profile})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Profile could not be loaded."},{status:400})}}
export async function PATCH(request:NextRequest){try{const body=bodySchema.parse(await request.json());const{supabase,profile}=await employee(request);const updates={full_name:body.fullName,phone:body.phone||null,address_line1:body.addressLine1||null,city:body.city||null,province:body.province||"ON",postal_code:body.postalCode||null,route_start_address:body.routeStartAddress||body.addressLine1||null,avatar_url:body.avatarUrl||null,invite_status:"accepted"};const{data,error}=await supabase.from("profiles").update(updates).eq("id",profile.id).select().single();if(error)throw new Error(error.message);const employeeUpdate=await supabase.from("employees").update(updates).eq("profile_id",profile.id);if(employeeUpdate.error)throw new Error(employeeUpdate.error.message);return NextResponse.json({profile:data,message:"Profile saved."})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Profile could not be saved."},{status:400})}}