"use client";
import {ChangeEvent,useEffect,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {Lead,getLeads,updateEmployeeTaskStatus,getEmployeeTasks,setPropertyPhoto} from "@/lib/storage";
import {loadEmployeeOperationalIdentity} from "@/lib/services/employeeIdentityService";
function hasValidAddress(address?: string){return Boolean(address && address.trim().length>5)}
function mapsHref(address:string){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address)}&travelmode=driving`}
function grassLabel(value?: string){if(value==="mulched")return "Mulched";if(value==="bag_green_bin")return "Bag to green bin";if(value==="bag_leave_property")return "Bag and leave";return "No preference"}
function fileToDataUrl(file: File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});}
export default function EmployeeProperty(){
  const params=useParams<{id:string}>();
  const[lead,setLead]=useState<Lead|null>(null);const[message,setMessage]=useState("");const[identity,setIdentity]=useState<{name:string;crew:string}|null>(null);
  useEffect(()=>{let active=true;void loadEmployeeOperationalIdentity().then(value=>{if(!active)return;setIdentity(value);setLead(getLeads().find(item=>item.id===params?.id&&item.assignedCrew===value.crew)||null)});return()=>{active=false}},[params?.id]);
  async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!lead)return;const data=await fileToDataUrl(file);setPropertyPhoto(lead.id,data);setLead(getLeads().find(l=>l.id===lead.id)||lead);setMessage("Official property photo saved.")}
  if(!lead)return <div className="field-shell"><div className="field-topbar"><Link className="btn btn-outline" href="/employee/route">Back Route</Link></div><main className="field-container"><div className="field-card" style={{padding:24}}><h1>{identity?"Property not assigned to your crew":"Loading property..."}</h1></div></main></div>;
  const details=lead.propertyDetails;const openTasks=getEmployeeTasks().filter(t=>t.leadId===lead.id&&(t.status==="assigned"||t.status==="in_progress")&&(t.assignedTo===identity?.name||t.assignedTo===identity?.crew));
  return <div className="field-shell"><div className="field-topbar"><div className="field-brand-mini"><div className="field-brand-mark">D</div><div>Damasio Field</div></div><Link className="btn btn-outline" href="/employee/route">Back to Route</Link></div>
    <main className="field-container"><div className="house-image">{lead.propertyPhoto?<img src={lead.propertyPhoto} alt="Official property"/>:<div className="house-placeholder">🏠</div>}{hasValidAddress(lead.address)?<a className="direction-btn" href={mapsHref(lead.address)} target="_blank" rel="noopener noreferrer">Get directions</a>:<span className="direction-btn disabled">Address missing</span>}</div>
    <div className="field-card" style={{padding:16,marginBottom:18}}><strong>Official property photo</strong><p className="section-intro">On the first visit, upload the front photo of the house. It becomes the default property photo for this address.</p><input className="input" type="file" accept="image/*" onChange={upload}/></div>
    <h1 className="field-title">{lead.address||"Property address missing"}</h1><p className="section-intro">Private property profile for your crew only. Customer data is connected to this property.</p>
    <div className="details-table"><div className="details-row"><span>Client</span><span>{lead.name}</span></div><div className="details-row"><span>Phone</span><span>{lead.phone||"-"}</span></div><div className="details-row"><span>Email</span><span>{lead.email||"-"}</span></div><div className="details-row"><span>Address</span><span>{lead.address||"Address not set"}</span></div><div className="details-row"><span>Service</span><span>{lead.service}</span></div><div className="details-row"><span>Route day</span><span>{lead.serviceDay||"Not set"}</span></div></div>
    {openTasks.length>0&&<div className="info-blue"><strong>Open task for this exact property</strong>{openTasks.map(t=><div key={t.id} style={{marginTop:8}}><p>{t.title}: {t.description}</p><button className="btn btn-outline" onClick={()=>{if(window.confirm("Are you sure this task is resolved?")){updateEmployeeTaskStatus(t.id,"completed","Return visit completed and customer issue fixed.","Employee");setMessage("Task completed. It was removed from Employee and sent to Admin review.")}}}>Mark Task Completed</button></div>)}</div>}
    <h2>Service Profile</h2><div className="details-table"><div className="details-row"><span>Grass height</span><span>{details?.grassHeight||"3in"}</span></div><div className="details-row"><span>Grass clippings</span><span>{grassLabel(details?.grassHandling)}</span></div><div className="details-row"><span>Lot Size</span><span>{details?.lawnSize?.toUpperCase()||"SMALL"}</span></div><div className="details-row"><span>Backyard</span><span>{details?.backyard?"Yes":"No"}</span></div><div className="details-row"><span>Gate</span><span>{details?.gated?"Yes":"No"}</span></div><div className="details-row"><span>Access</span><span>{details?.accessNotes||"-"}</span></div></div>
    {details?.propertyAlerts&&<div className="info-blue">⚠️ {details.propertyAlerts}</div>}
    <div className="row" style={{marginTop:20}}><Link className="btn btn-primary" href={`/employee/route?property=${lead.id}`}>Open Service Screen</Link>{hasValidAddress(lead.address)?<a className="btn btn-outline" href={mapsHref(lead.address)} target="_blank" rel="noopener noreferrer">Get Directions</a>:<button className="btn btn-outline" disabled>Address missing</button>}</div>{message&&<div className="payment-message" style={{marginTop:16}}>{message}</div>}</main></div>
}
