"use client";
import {ChangeEvent,useEffect,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {Lead,formatDuration,getLeads,getSessionForLead,updateEmployeeTaskStatus,getEmployeeTasks,setPropertyPhoto} from "@/lib/storage";
import {loadEmployeeOperationalIdentity} from "@/lib/services/employeeIdentityService";
function hasValidAddress(address?: string){return Boolean(address && address.trim().length>5)}
function mapsHref(address:string){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address)}&travelmode=driving`}
function grassLabel(value?: string){if(value==="mulched")return "Mulched";if(value==="bag_green_bin")return "Bag to green bin";if(value==="bag_leave_property")return "Bag and leave";return "No preference"}
function fileToDataUrl(file: File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});}
export default function EmployeeProperty(){
  const params=useParams<{id:string}>();
  const[lead,setLead]=useState<Lead|null>(null);const[message,setMessage]=useState("");const[identity,setIdentity]=useState<{name:string;crew:string}|null>(null);
  useEffect(()=>{let active=true;void loadEmployeeOperationalIdentity().then(value=>{if(!active)return;setIdentity(value);setLead(getLeads().find(item=>item.id===params?.id&&item.assignedCrew===value.crew)||null)});return()=>{active=false}},[params?.id]);
  async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!lead)return;const data=await fileToDataUrl(file);setPropertyPhoto(lead.id,data);setLead(getLeads().find(l=>l.id===lead.id)||lead);setMessage("Official property photo saved.")}
  if(!lead)return <div className="field-shell"><div className="field-topbar"><Link className="btn btn-outline" href="/employee/route">Back Route</Link></div><main className="field-container"><div className="field-card" style={{padding:24}}><h1>{identity?"Property not assigned to your crew":"Loading property..."}</h1></div></main></div>;
  const details=lead.propertyDetails;const session=getSessionForLead(lead.id);const openTasks=getEmployeeTasks().filter(t=>t.leadId===lead.id&&(t.status==="assigned"||t.status==="in_progress")&&(t.assignedTo===identity?.name||t.assignedTo===identity?.crew));
  const clock=(value?:string)=>value?new Date(value).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—";
  return <div className="field-shell"><div className="field-topbar"><div className="field-brand-mini"><div className="field-brand-mark">4</div><div>4Ever Seasons Field</div></div><Link className="btn btn-outline" href="/employee/route">Back to Route</Link></div>
    <main className="field-container employee-property-reference"><div className="house-image">{lead.propertyPhoto?<img src={lead.propertyPhoto} alt="Official property"/>:<div className="house-placeholder">🏠</div>}{hasValidAddress(lead.address)?<a className="direction-btn" href={mapsHref(lead.address)} target="_blank" rel="noopener noreferrer">Get directions</a>:<span className="direction-btn disabled">Address missing</span>}</div>
    <h1 className="field-title">{lead.address||"Property address missing"}</h1><p className="section-intro">{lead.name} · Private to {identity?.crew||"your crew"}</p>
    <section className="employee-contract-card"><div className="employee-contract-service"><i>✂</i><div><strong>{lead.service}</strong><small>{lead.serviceFrequency||"one time"} · {lead.scheduledDate||lead.serviceDay||"Route pending"}</small></div></div>{(details?.accessNotes||details?.propertyAlerts)&&<div className="employee-access-note">ⓘ {details.accessNotes||details.propertyAlerts}</div>}<div className="mobile-detail-list compact employee-contract-details"><div><span>Cut height</span><strong>{details?.grassHeight||"3in"}</strong></div><div><span>Grass clippings</span><strong>{grassLabel(details?.grassHandling)}</strong></div><div><span>Lot size</span><strong>{details?.lawnSize?.toUpperCase()||"SMALL"}</strong></div><div><span>Backyard / gate</span><strong>{details?.backyard?"Yes":"No"} · {details?.gated?"Gated":"Open"}</strong></div></div></section>
    <div className="employee-visit-date">{lead.scheduledDate?new Date(`${lead.scheduledDate}T12:00:00`).toLocaleDateString([],{month:"short",day:"numeric"}):"Latest visit"}</div><div className="employee-time-grid"><div><span>Started</span><strong>{clock(session?.startedAt||lead.visitStartedAt)}</strong></div><div><span>Duration</span><strong>{formatDuration(session?.durationSeconds||lead.visitDurationSeconds||0)}</strong></div><div><span>Finished</span><strong>{clock(session?.finishedAt||lead.visitFinishedAt)}</strong></div></div>
    <div className="field-card employee-property-upload"><strong>Official property photo</strong><p className="section-intro">Upload the front photo once; it becomes the default image for this address.</p><input className="input" type="file" accept="image/*" onChange={upload}/></div>
    {openTasks.length>0&&<div className="info-blue"><strong>Open task for this exact property</strong>{openTasks.map(t=><div key={t.id} style={{marginTop:8}}><p>{t.title}: {t.description}</p><button className="btn btn-outline" onClick={()=>{if(window.confirm("Are you sure this task is resolved?")){updateEmployeeTaskStatus(t.id,"completed","Return visit completed and customer issue fixed.","Employee");setMessage("Task completed. It was removed from Employee and sent to Admin review.")}}}>Mark Task Completed</button></div>)}</div>}
    {details?.propertyAlerts&&<div className="info-blue">⚠️ {details.propertyAlerts}</div>}
    <div className="row" style={{marginTop:20}}><Link className="btn btn-primary" href={`/employee/route?property=${lead.id}`}>Open Service Screen</Link>{hasValidAddress(lead.address)?<a className="btn btn-outline" href={mapsHref(lead.address)} target="_blank" rel="noopener noreferrer">Get Directions</a>:<button className="btn btn-outline" disabled>Address missing</button>}</div>{message&&<div className="payment-message" style={{marginTop:16}}>{message}</div>}</main></div>
}
