"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {DAMASIO_SYNC_EVENT,getLeads,type Lead} from "@/lib/storage";

function cityOf(address:string){const parts=address.split(",").map(part=>part.trim()).filter(Boolean);const ontario=parts.findIndex(part=>/^(ON|Ontario)(\s|$)/i.test(part));return (ontario>0?parts[ontario-1]:parts.length>1?parts[parts.length-2]:"Other Ontario")||"Other Ontario"}
export default function MobileHomesByStatus(){
 const state=String(useParams().state||"open");const done=state==="done";const[tick,setTick]=useState(0);const[selected,setSelected]=useState<Lead|null>(null);
 useEffect(()=>{const update=()=>setTick(v=>v+1);window.addEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.addEventListener("storage",update);return()=>{window.removeEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.removeEventListener("storage",update)}},[]);
 const groups=useMemo(()=>{tick;const rows=getLeads().filter(lead=>done?lead.status==="completed":lead.status!=="completed");return Object.entries(rows.reduce<Record<string,Lead[]>>((all,lead)=>{const city=cityOf(lead.address);(all[city]??=[]).push(lead);return all},{})).sort(([a],[b])=>a.localeCompare(b))},[done,tick]);
 const count=groups.reduce((sum,[,rows])=>sum+rows.length,0);
 return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>{done?"Done":"Open"} homes</strong><span>Grouped by Ontario city</span></div><span className="role-mobile-avatar">{count}</span></header><section className="mobile-native-hero"><span>ONTARIO OPERATIONS</span><h1>{count} {done?"completed":"remaining"} houses.</h1><p>Open any property without entering the employee workflow.</p></section><section className="mobile-city-groups">{groups.map(([city,rows])=><section key={city}><header><h2>{city}</h2><span>{rows.length} homes</span></header>{rows.map(lead=><button key={lead.id} onClick={()=>setSelected(lead)}><i>{done?"✓":"⌂"}</i><div><strong>{lead.name}</strong><span>{lead.address}</span><small>{lead.service} · {lead.assignedCrew||"Unassigned"}</small></div><b>›</b></button>)}</section>)}{!count&&<div className="mobile-native-empty"><i>✓</i><strong>No homes</strong><p>There are no houses in this status.</p></div>}</section>{selected&&<PropertySheet lead={selected} close={()=>setSelected(null)}/>}<MobileAdminNav active="home"/></main></MobileRoleGuard>
}
function PropertySheet({lead,close}:{lead:Lead;close:()=>void}){return <div className="mobile-native-modal mobile-detail-sheet"><button className="mobile-native-scrim" onClick={close} aria-label="Close"/><section><header><div><span>PROPERTY DETAILS</span><h2>{lead.name}</h2></div><button onClick={close}>×</button></header><dl className="mobile-property-dl"><div><dt>Address</dt><dd>{lead.address}</dd></div><div><dt>Service</dt><dd>{lead.service}</dd></div><div><dt>Value</dt><dd>${lead.total.toFixed(2)}</dd></div><div><dt>Status</dt><dd>{lead.status}</dd></div><div><dt>Schedule</dt><dd>{lead.scheduledDate||lead.nextVisitDate||"Not scheduled"}</dd></div><div><dt>Crew</dt><dd>{lead.assignedCrew||"Unassigned"}</dd></div><div><dt>Phone</dt><dd>{lead.phone||"Not available"}</dd></div><div><dt>Notes</dt><dd>{lead.notes||"No notes"}</dd></div></dl><a className="mobile-native-submit mobile-directions-link" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lead.address)}&travelmode=driving`} target="_blank" rel="noreferrer">Get directions</a><Link className="mobile-native-submit" href={`/mobile/admin/customers?property=${lead.id}`}>See complete customer record</Link></section></div>}
