"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {loadDailyOperations,type DailyOperations,type DailyVisit} from "@/lib/services/dailyOperationsService";

export default function MobileHomesByStatus(){
  const state=String(useParams().state||"open");const done=state==="done";const[board,setBoard]=useState<DailyOperations|null>(null);const[selected,setSelected]=useState<DailyVisit|null>(null);const[error,setError]=useState("");
  useEffect(()=>{let active=true;const refresh=()=>void loadDailyOperations().then(data=>{if(active){setBoard(data);setError("")}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:"Daily operations could not be loaded."));refresh();const timer=window.setInterval(refresh,5000);return()=>{active=false;window.clearInterval(timer)}},[]);
  const groups=useMemo(()=>{const rows=(board?.visits||[]).filter(visit=>done?visit.status==="completed":!["completed","cancelled","missed"].includes(visit.status));return Object.entries(rows.reduce<Record<string,DailyVisit[]>>((all,visit)=>{(all[visit.city||"Other Ontario"]??=[]).push(visit);return all},{})).sort(([a],[b])=>a.localeCompare(b))},[board,done]);
  const count=groups.reduce((sum,[,rows])=>sum+rows.length,0);
  return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>{done?"Done":"Open"} homes</strong><span>Grouped by Ontario city</span></div><span className="role-mobile-avatar">{count}</span></header><section className="mobile-native-hero"><span>ONTARIO OPERATIONS</span><h1>{count} {done?"completed":"remaining"} houses.</h1><p>Live data for {board?.date||"today"}. Open any property for details.</p></section>{error&&<div className="mobile-native-message">{error}</div>}<section className="mobile-city-groups">{groups.map(([city,rows])=><section key={city}><header><h2>{city}</h2><span>{rows.length} homes</span></header>{rows.map(visit=><button key={visit.id} onClick={()=>setSelected(visit)}><i>{done?"✓":"⌂"}</i><div><strong>{visit.customerName}</strong><span>{visit.address}</span><small>{visit.serviceName} · {visit.assignedTo}</small></div><b>›</b></button>)}</section>)}{!count&&!error&&<div className="mobile-native-empty"><i>✓</i><strong>No homes</strong><p>There are no houses in this status today.</p></div>}</section>{selected&&<PropertySheet visit={selected} close={()=>setSelected(null)}/>}<MobileAdminNav active="home"/></main></MobileRoleGuard>
}

function PropertySheet({visit,close}:{visit:DailyVisit;close:()=>void}){return <div className="mobile-native-modal mobile-detail-sheet"><button className="mobile-native-scrim" onClick={close} aria-label="Close"/><section><header><div><span>PROPERTY DETAILS</span><h2>{visit.customerName}</h2></div><button onClick={close}>×</button></header><dl className="mobile-property-dl"><div><dt>Address</dt><dd>{visit.address}</dd></div><div><dt>Service</dt><dd>{visit.serviceName}</dd></div><div><dt>Status</dt><dd>{visit.status}</dd></div><div><dt>Schedule</dt><dd>{visit.scheduledDate}</dd></div><div><dt>Worker / Crew</dt><dd>{visit.assignedTo}</dd></div><div><dt>Started</dt><dd>{visit.startedAt?new Date(visit.startedAt).toLocaleTimeString():"Not started"}</dd></div><div><dt>Finished</dt><dd>{visit.finishedAt?new Date(visit.finishedAt).toLocaleTimeString():"Not finished"}</dd></div><div><dt>Notes</dt><dd>{visit.customerVisibleSummary||visit.employeeNotes||"No notes"}</dd></div></dl><a className="mobile-native-submit mobile-directions-link" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(visit.address)}&travelmode=driving`} target="_blank" rel="noreferrer">Get directions</a><Link className="mobile-native-submit" href={`/mobile/admin/customers/${visit.propertyId}`}>See complete customer record</Link></section></div>}
