"use client";
import {useEffect,useMemo,useState} from "react";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileAdminNav} from "@/components/mobile/MobileAdminNav";
import {EmployeeRouteMap} from "@/components/mobile/EmployeeRouteMap";
import {AddressAutocomplete} from "@/components/home/AddressAutocomplete";
import {DAMASIO_CREWS,Lead} from "@/lib/storage";
import {loadSchedulingDispatchBoard,publishJobRoutePattern,rescheduleVisit,schedulingBoardToLeads} from "@/lib/services/schedulingService";
import type {DispatchCrew} from "@/lib/repositories/schedulingRepository";

type Mode="view"|"build"|"move";const today=()=>new Date().toISOString().slice(0,10);
export default function MobileAdminRoutes(){
 const[leads,setLeads]=useState<Lead[]>([]);const[crews,setCrews]=useState<DispatchCrew[]>([]);const[crew,setCrew]=useState(DAMASIO_CREWS[0]);const[date,setDate]=useState(today());const[mode,setMode]=useState<Mode>("view");const[mapView,setMapView]=useState(true);const[message,setMessage]=useState("Loading routes...");const[busy,setBusy]=useState(false);
 const[selected,setSelected]=useState<string[]>([]);const[query,setQuery]=useState("");const[startAddress,setStartAddress]=useState("");const[draft,setDraft]=useState<Lead[]>([]);const[targetCrew,setTargetCrew]=useState(DAMASIO_CREWS[0]);const[targetDate,setTargetDate]=useState(today());
 async function refresh(){try{const board=await loadSchedulingDispatchBoard({force:true});setLeads(schedulingBoardToLeads(board));setCrews(board.crews);if(board.crews.length&&!board.crews.some(item=>item.name===crew)){setCrew(board.crews[0].name);setTargetCrew(board.crews[0].name)}setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Routes could not be loaded.")}}
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(timer)},[]);
 const route=useMemo(()=>{const visits=leads.filter(item=>item.canonicalVisitId&&item.assignedCrew===crew&&item.scheduledDate===date);const ids=new Set(visits.map(item=>item.canonicalJobId).filter(Boolean));const templates=leads.filter(item=>!item.canonicalVisitId&&item.assignedCrew===crew&&item.scheduledDate===date&&!ids.has(item.canonicalJobId));return[...visits,...templates].sort((a,b)=>(a.routeOrder??9999)-(b.routeOrder??9999)||a.address.localeCompare(b.address))},[leads,crew,date]);
 const jobs=useMemo(()=>leads.filter(item=>!item.canonicalVisitId),[leads]);const candidates=jobs.filter(home=>`${home.name} ${home.address} ${home.assignedCrew||""}`.toLowerCase().includes(query.toLowerCase()));const selectedHomes=jobs.filter(home=>selected.includes(home.id));const done=route.filter(item=>item.status==="completed").length;const crewNames=crews.length?crews.map(item=>item.name):DAMASIO_CREWS;
 function switchMode(next:Mode){setMode(next);setSelected([]);setDraft([]);setMessage("");if(next==="move")setTargetCrew(crewNames.find(name=>name!==crew)||crew)}
 function toggle(id:string){setDraft([]);setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id])}
 function smartSelect(){const available=candidates.filter(home=>!home.assignedCrew);const pool=available.length?available:candidates.filter(home=>home.assignedCrew===crew);const city=(address:string)=>address.split(",").slice(-2,-1)[0]?.trim()||address.split(",").pop()?.trim()||"Other";const counts=pool.reduce<Record<string,number>>((result,home)=>{const key=city(home.address);result[key]=(result[key]||0)+1;return result},{});const region=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0];const source=region?pool.filter(home=>city(home.address)===region):pool;setSelected(source.map(home=>home.id));setDraft([]);setMessage(`${source.length} ${region||"available"} houses grouped for a practical route.`)}
 async function buildPreview(){if(!selectedHomes.length){setMessage("Select at least one house.");return}setBusy(true);setMessage("Mapping houses and calculating the smartest order...");try{const mapped=await Promise.all(selectedHomes.map(async home=>{if(Number.isFinite(home.latitude)&&Number.isFinite(home.longitude))return home;const response=await fetch(`/api/map/geocode?address=${encodeURIComponent(home.address)}`,{cache:"no-store"});return response.ok?{...home,...await response.json() as {latitude:number;longitude:number}}:home}));const located=mapped.filter(home=>Number.isFinite(home.latitude)&&Number.isFinite(home.longitude));let ordered=[...mapped].sort((a,b)=>a.address.localeCompare(b.address));if(located.length>1){let start:[number,number]=[Number(located[0].longitude),Number(located[0].latitude)];if(startAddress.trim()){const response=await fetch(`/api/map/geocode?address=${encodeURIComponent(startAddress.trim())}`,{cache:"no-store"});if(response.ok){const point=await response.json() as {latitude:number;longitude:number};start=[point.longitude,point.latitude]}}const response=await fetch("/api/map/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({start,coordinates:located.map(home=>[Number(home.longitude),Number(home.latitude)])})});if(response.ok){const result=await response.json() as {order:number[]};ordered=[...result.order.map(index=>located[index]).filter(Boolean),...mapped.filter(home=>!located.some(item=>item.id===home.id))]}}setDraft(ordered);setMessage("Preview ready. Check the map and confirm.")}catch{setDraft([...selectedHomes].sort((a,b)=>a.address.localeCompare(b.address)));setMessage("Safe address order created for review.")}finally{setBusy(false)}}
 async function publish(){const crewId=crews.find(item=>item.name===crew)?.id;if(!crewId||!draft.length){setMessage("Choose an Employee and generate the preview first.");return}if(!window.confirm(`Send ${draft.length} houses to ${crew} on ${date}?`))return;setBusy(true);try{for(let index=0;index<draft.length;index++)await publishJobRoutePattern({jobId:draft[index].canonicalJobId||draft[index].id,crewId,routeDate:date,routeOrder:index+1});setMessage("Route published and synchronized with the Employee map.");setSelected([]);setDraft([]);setMode("view");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Route could not be published.")}finally{setBusy(false)}}
 async function moveHomes(){const targetId=crews.find(item=>item.name===targetCrew)?.id;const homes=route.filter(home=>selected.includes(home.id));if(!targetId||!homes.length){setMessage("Select houses and the destination Employee.");return}if(!window.confirm(`Move ${homes.length} houses to ${targetCrew} on ${targetDate}?`))return;setBusy(true);try{for(let index=0;index<homes.length;index++){const home=homes[index];if(home.canonicalVisitId)await rescheduleVisit({visitId:home.canonicalVisitId,crewId:targetId,routeDate:targetDate,routeOrder:index+1});else await publishJobRoutePattern({jobId:home.canonicalJobId||home.id,crewId:targetId,routeDate:targetDate,routeOrder:index+1})}setMessage("Houses moved. Both Employee routes were updated.");setSelected([]);setMode("view");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"Houses could not be moved.")}finally{setBusy(false)}}
 return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage mobile-route-builder"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>Routes</strong><span>Build, view and move</span></div><button className="mobile-native-add mobile-native-check" onClick={()=>void refresh()} aria-label="Refresh">↻</button></header><section className="mobile-native-hero routes"><span>SMART DISPATCH</span><h1>{mode==="build"?"Build a route in seconds.":mode==="move"?"Move houses without rebuilding.":`${route.length} stops for ${crew}.`}</h1><p>{mode==="view"?`${done} completed · ${route.length-done} remaining`:"Select → preview → confirm"}</p></section><nav className="mobile-route-modes"><button className={mode==="view"?"active":""} onClick={()=>switchMode("view")}>View</button><button className={mode==="build"?"active":""} onClick={()=>switchMode("build")}>＋ Build</button><button className={mode==="move"?"active":""} onClick={()=>switchMode("move")}>⇄ Move</button></nav><section className="mobile-route-pickers"><label><span>Employee / Crew</span><div><select value={crew} onChange={e=>{setCrew(e.target.value);setSelected([]);setDraft([])}}>{crewNames.map(name=><option key={name}>{name}</option>)}</select><b>⌄</b></div></label><label><span>Day</span><div><input type="date" value={date} onChange={e=>{setDate(e.target.value);setSelected([]);setDraft([])}}/><b>⌄</b></div></label></section>{message&&<div className="mobile-native-message">{message}</div>}
 {mode==="view"&&<><div className="mobile-native-toggle"><button className={mapView?"active":""} onClick={()=>setMapView(true)}>Map</button><button className={!mapView?"active":""} onClick={()=>setMapView(false)}>List <b>{route.length}</b></button></div>{mapView?<EmployeeRouteMap route={route} actionLabel="Show in list" onOpenVisit={()=>setMapView(false)}/>:<RouteList homes={route} selected={selected} onToggle={toggle} selectable={false}/>}</>}
 {mode==="build"&&<><div className="mobile-native-search"><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, address or Employee"/><button onClick={smartSelect}>Smart</button></div><div className="mobile-selection-head"><span>{selected.length} selected</span><button onClick={()=>setSelected(selected.length?[]:candidates.map(home=>home.id))}>{selected.length?"Clear":"Select all"}</button></div><RouteList homes={candidates} selected={selected} onToggle={toggle} selectable/><section className="mobile-route-origin"><label>Start address <small>Optional</small></label><AddressAutocomplete value={startAddress} onChange={value=>{setStartAddress(value);setDraft([])}} placeholder="Employee location or manual address" ariaLabel="Route start"/><button disabled={busy||!selected.length} onClick={()=>void buildPreview()}>{busy?"Optimizing…":"Generate Smart Route"}</button></section>{draft.length>0&&<section className="mobile-route-preview"><header><div><strong>Preview</strong><span>{draft.length} stops · {crew}</span></div><button disabled={busy} onClick={()=>void publish()}>Confirm & Send</button></header><EmployeeRouteMap route={draft} actionLabel="Select stop" onOpenVisit={()=>{}}/><RouteList homes={draft} selected={[]} onToggle={()=>{}} selectable={false}/></section>}</>}
 {mode==="move"&&<><p className="mobile-route-help">Select houses from {crew} on {date}, then choose where they should go.</p><RouteList homes={route} selected={selected} onToggle={toggle} selectable/><section className="mobile-move-panel"><label><span>Move to Employee</span><div><select value={targetCrew} onChange={e=>setTargetCrew(e.target.value)}>{crewNames.filter(name=>name!==crew).map(name=><option key={name}>{name}</option>)}</select><b>⌄</b></div></label><label><span>Move to day</span><div><input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/><b>⌄</b></div></label><button disabled={busy||!selected.length} onClick={()=>void moveHomes()}>{busy?"Moving…":`Move ${selected.length} house${selected.length===1?"":"s"}`}</button></section></>}
 <MobileAdminNav active="routes"/></main></MobileRoleGuard>
}
function RouteList({homes,selected,onToggle,selectable}:{homes:Lead[];selected:string[];onToggle:(id:string)=>void;selectable:boolean}){return <section className="mobile-native-route-list selectable">{homes.map((home,index)=><button className={selected.includes(home.id)?"selected":""} onClick={()=>selectable&&onToggle(home.id)} type="button" key={home.id}><b>{selectable?(selected.includes(home.id)?"✓":""):index+1}</b><div><strong>{home.name}</strong><span>{home.address}</span><small>{home.service} · {home.assignedCrew||"Unassigned"}</small></div><i className={home.status==="completed"?"done":""}>{home.status==="completed"?"Done":home.assignedCrew||"Open"}</i></button>)}{!homes.length&&<div className="mobile-native-empty"><i>⌖</i><strong>No houses found</strong><p>Change the Employee, day or search.</p></div>}</section>}
