"use client";

import { useEffect, useMemo, useState } from "react";
import { MobileRoleGuard } from "@/components/mobile/MobileRoleGuard";
import { MobileBackButton } from "@/components/mobile/MobileBackButton";
import { MobileAdminNav } from "@/components/mobile/MobileAdminNav";
import { EmployeeRouteMap } from "@/components/mobile/EmployeeRouteMap";
import { RouteAdvisorWorkspace } from "@/components/admin/RouteAdvisorWorkspace";
import { RouteMoveWorkspace } from "@/components/admin/RouteMoveWorkspace";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { schedulingBoardToLeads, type RouteLead } from "@/lib/services/schedulingService";
import type { SchedulingDispatchBoard } from "@/lib/repositories/schedulingRepository";
import { canonicalRouteLeadsForEmployee } from "@/lib/routes/canonicalRouteIdentity";
import { operationalDateKey } from "@/lib/dates/operationalDate";
import { useCanonicalRouteSnapshot } from "@/lib/hooks/useCanonicalRouteSnapshot";
import { applyEmployeeRouteMapContext, employeeRouteMapContextFromSnapshot } from "@/lib/services/routeMapService";

type Mode="view"|"build"|"advisor"|"move";
type Employee={id:string;employeeId:string;crewId:string;employeeIds?:string[];crewIds?:string[];name:string;routeStartAddress:string|null};
type Origin={latitude:number;longitude:number;label:string};
const jobId=(home:RouteLead)=>home.canonicalJobId||home.id;
async function token(){const client=getSupabaseBrowserClient() as any;const{data}=await client.auth.getSession();const value=data.session?.access_token;if(!value)throw new Error("Your Admin session expired.");return value;}
async function api(path:string,options?:RequestInit){const access=await token();const response=await fetch(path,{...options,headers:{"content-type":"application/json",authorization:`Bearer ${access}`,...(options?.headers||{})},cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Route operation failed.");return result;}

export default function MobileAdminRoutes(){
 const[mode,setMode]=useState<Mode>("view");const[date,setDate]=useState(operationalDateKey());const[employees,setEmployees]=useState<Employee[]>([]);const[leads,setLeads]=useState<RouteLead[]>([]);const[employeeId,setEmployeeId]=useState("");const[selected,setSelected]=useState<string[]>([]);const[query,setQuery]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[mapView,setMapView]=useState(true);const[routeId,setRouteId]=useState<string|null>(null);const[origin,setOrigin]=useState<Origin|null>(null);
 async function refresh(silent=false){if(mode==="advisor"||mode==="move")return;try{const result=await api(`/api/admin/routes?date=${encodeURIComponent(date)}`);const people:Employee[]=result.employees||[];setEmployees(people);setLeads(schedulingBoardToLeads((result.board||{}) as SchedulingDispatchBoard));setEmployeeId(current=>people.some(p=>p.id===current)?current:people[0]?.id||"");if(!silent)setMessage("");}catch(error){if(!silent)setMessage(error instanceof Error?error.message:"Routes could not be loaded.");}}
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(true),15000);return()=>window.clearInterval(timer);},[date,mode]);
 const employee=employees.find(p=>p.id===employeeId)||null;
 useEffect(()=>{let cancelled=false;setRouteId(null);if(!employee?.id||!date||mode!=="view")return()=>{cancelled=true};void(async()=>{try{const result=await api(`/api/admin/canonical-route?profileId=${encodeURIComponent(employee.id)}&date=${encodeURIComponent(date)}`);if(!cancelled)setRouteId(String(result.routeId||"")||null);}catch{if(!cancelled)setRouteId(null);}})();return()=>{cancelled=true};},[employee?.id,date,mode]);
 const{snapshot}=useCanonicalRouteSnapshot(routeId);
 useEffect(()=>{let cancelled=false;setOrigin(null);const address=employee?.routeStartAddress?.trim();if(!address||mode!=="view")return()=>{cancelled=true};void fetch(`/api/map/geocode?address=${encodeURIComponent(address)}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(point=>{if(!cancelled&&Number.isFinite(point.latitude)&&Number.isFinite(point.longitude))setOrigin({latitude:Number(point.latitude),longitude:Number(point.longitude),label:`${employee?.name||"Employee"} start`});}).catch(()=>{});return()=>{cancelled=true};},[employee?.id,employee?.routeStartAddress,mode]);
 const visits=useMemo(()=>leads.filter(x=>x.canonicalVisitId&&x.scheduledDate===date),[leads,date]);const operational=useMemo(()=>employee?canonicalRouteLeadsForEmployee(visits,{id:employee.employeeId||employee.id,crewId:employee.crewId,employeeIds:employee.employeeIds,crewIds:employee.crewIds}).sort((a,b)=>(a.routeOrder??9999)-(b.routeOrder??9999)):[],[visits,employee?.id,employee?.crewId]);const route=useMemo(()=>snapshot&&snapshot.routeId===routeId?applyEmployeeRouteMapContext(operational,employeeRouteMapContextFromSnapshot(snapshot)) as RouteLead[]:[],[operational,snapshot,routeId]);
 const jobs=useMemo(()=>leads.filter(x=>!x.canonicalVisitId&&!x.canonicalCrewId),[leads]);const candidates=useMemo(()=>jobs.filter(home=>`${home.name} ${home.address} ${home.service}`.toLowerCase().includes(query.toLowerCase())),[jobs,query]);
 function switchMode(next:Mode){setMode(next);setSelected([]);setQuery("");setMessage("");}
 function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 async function assign(){if(!employee||!selected.length)return;setBusy(true);try{const result=await api("/api/admin/routes",{method:"POST",body:JSON.stringify({action:"assign",jobIds:selected,crewId:employee.crewId})});setSelected([]);await refresh(true);setMessage(`${result.count} customer${result.count===1?"":"s"} assigned to ${employee.name}. They now leave Build and can be fitted into the week in Route Advisor.`);}catch(error){setMessage(error instanceof Error?error.message:"Customers could not be assigned.");}finally{setBusy(false);}}
 return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage mobile-route-builder"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>Routes</strong><span>Same canonical planning as desktop</span></div><button className="mobile-native-add mobile-native-check" onClick={()=>void refresh()} aria-label="Refresh">↻</button></header>
 <nav className="mobile-route-modes mobile-route-modes-four"><button className={mode==="view"?"active":""} onClick={()=>switchMode("view")}>View</button><button className={mode==="build"?"active":""} onClick={()=>switchMode("build")}>＋ Build</button><button className={mode==="advisor"?"active":""} onClick={()=>switchMode("advisor")}>Advisor</button><button className={mode==="move"?"active":""} onClick={()=>switchMode("move")}>⇄ Move</button></nav>
 {message&&<div className="mobile-native-message">{message}</div>}
 {mode==="view"&&<><section className="mobile-native-hero routes"><span>LIVE DATABASE</span><h1>{route.length} published stops.</h1><p>{employee?.name||"Employee"} · {date}</p></section><section className="mobile-route-pickers"><label><span>Employee</span><div><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><b>⌄</b></div></label><label><span>Day</span><div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><b>⌄</b></div></label></section><div className="mobile-native-toggle"><button className={mapView?"active":""} onClick={()=>setMapView(true)}>Map</button><button className={!mapView?"active":""} onClick={()=>setMapView(false)}>List <b>{route.length}</b></button></div>{mapView?<EmployeeRouteMap route={route} routeId={routeId||undefined} originPoint={origin} actionLabel="Show in list" onOpenVisit={()=>setMapView(false)}/>:<RouteList homes={route} selected={[]} onToggle={()=>{}} selectable={false}/>}</>}
 {mode==="build"&&<><section className="mobile-native-hero routes"><span>BUILD · UNASSIGNED ONLY</span><h1>{jobs.length} customers need an owner.</h1><p>Assign ownership here; create the intelligent weekly route in Advisor.</p></section><section className="mobile-route-pickers mobile-build-employee"><label><span>Permanent Employee</span><div><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><b>⌄</b></div></label></section><div className="mobile-native-search"><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search new customer or address"/></div><div className="mobile-selection-head"><span>{selected.length} selected · {candidates.length} unassigned</span><button onClick={()=>setSelected(selected.length?[]:candidates.map(jobId))}>{selected.length?"Clear":"Select all"}</button></div><RouteList homes={candidates} selected={selected} onToggle={toggle} selectable/><section className="mobile-build-assignment"><div><small>PERMANENT OWNERSHIP</small><strong>{employee?.name||"Choose Employee"}</strong><span>No Visit or route is created here.</span></div><button disabled={busy||!employee||!selected.length} onClick={()=>void assign()}>{busy?"Assigning…":`Assign ${selected.length} customer${selected.length===1?"":"s"}`}</button></section></>}
 {mode==="advisor"&&<section className="mobile-shared-route-workspace"><header><span>INTELLIGENT WEEKLY PLANNING</span><h1>Advanced Planner + Smart Route</h1><p>Same planner, recurrence, preview and manual editor used on desktop.</p></header><RouteAdvisorWorkspace/></section>}
 {mode==="move"&&<section className="mobile-shared-route-workspace"><header><span>TRANSFER & MOVE</span><h1>Ownership or dated service</h1><p>Transfer a client permanently, or move a scheduled Visit temporarily/permanently.</p></header><RouteMoveWorkspace/></section>}
 <style jsx global>{`.mobile-route-modes-four{grid-template-columns:repeat(4,minmax(0,1fr))!important}.mobile-route-modes-four button{min-width:0;padding-left:5px!important;padding-right:5px!important}.mobile-build-employee{grid-template-columns:1fr!important}.mobile-build-assignment{display:grid;gap:12px;margin:14px 0 18px;padding:16px;border:1px solid #d8e7df;border-radius:20px;background:#fff}.mobile-build-assignment div{display:grid;gap:4px}.mobile-build-assignment small{color:#0b7046;font-size:9px;font-weight:950;letter-spacing:.1em}.mobile-build-assignment strong{font-size:20px}.mobile-build-assignment span{color:#66776f;font-size:12px}.mobile-build-assignment>button{min-height:52px;border:0;border-radius:15px;background:#0b7046;color:#fff;font-weight:950}.mobile-shared-route-workspace{display:grid;gap:12px;padding:12px 12px 24px}.mobile-shared-route-workspace>header{padding:18px;border-radius:20px;background:linear-gradient(135deg,#0a3427,#11764b);color:#fff}.mobile-shared-route-workspace>header span{color:#9ee2bc;font-size:9px;font-weight:950;letter-spacing:.12em}.mobile-shared-route-workspace>header h1{margin:5px 0;font-size:27px}.mobile-shared-route-workspace>header p{margin:0;color:rgba(255,255,255,.72);font-size:12px}.mobile-shared-route-workspace .advanced-planner-v6{margin:0;padding:12px;border-radius:18px}.mobile-shared-route-workspace .planner-hero{padding:15px}.mobile-shared-route-workspace .planner-hero h2{font-size:23px}.mobile-shared-route-workspace .single-day-toggle{padding:14px}.mobile-shared-route-workspace .route-move-workspace{margin-top:0}`}</style><MobileAdminNav active="routes"/></main></MobileRoleGuard>;
}

function RouteList({homes,selected,onToggle,selectable}:{homes:RouteLead[];selected:string[];onToggle:(id:string)=>void;selectable:boolean}){return <section className="mobile-native-route-list selectable">{homes.map((home,index)=>{const id=jobId(home);const complete=home.canonicalVisitStatus==="completed"||home.status==="completed";return <button className={selected.includes(id)?"selected":""} onClick={()=>selectable&&onToggle(id)} type="button" key={`${id}-${home.canonicalVisitId||"job"}`}><b>{selectable?(selected.includes(id)?"✓":"+"):home.routeOrder||index+1}</b><div><strong>{home.name}</strong><span>{home.address}</span><small>{home.service} · {home.assignedCrew||"Unassigned"}</small></div><i className={complete?"done":""}>{complete?"Done":home.canonicalRouteId?home.assignedCrew||"Scheduled":"Available"}</i></button>})}{!homes.length&&<div className="mobile-native-empty"><i>⌖</i><strong>No houses found</strong><p>Only canonical Jobs and Visits appear here.</p></div>}</section>}
