"use client";
import{useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{MobileRoleGuard}from"@/components/mobile/MobileRoleGuard";
import{MobileBackButton}from"@/components/mobile/MobileBackButton";
import{MobileAdminNav}from"@/components/mobile/MobileAdminNav";
import{DAMASIO_SYNC_EVENT,Notification,getLeads,getNotifications,markNotificationRead,markNotificationsRead,type Lead}from"@/lib/storage";

function icon(type:Notification["type"]){return type==="payment"?"$":type==="schedule"?"↗":type==="weather"?"☁":"!"}
export default function MobileAdminAlerts(){
 const[items,setItems]=useState<Notification[]>([]);const[leads,setLeads]=useState<Lead[]>([]);const[unreadOnly,setUnreadOnly]=useState(false);const[selected,setSelected]=useState<Notification|null>(null);
 function refresh(){setItems(getNotifications());setLeads(getLeads())}
 useEffect(()=>{refresh();const update=()=>refresh();window.addEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.addEventListener("storage",update);return()=>{window.removeEventListener(DAMASIO_SYNC_EVENT,update as EventListener);window.removeEventListener("storage",update)}},[]);
 const visible=unreadOnly?items.filter(item=>!item.read):items;const unread=items.filter(item=>!item.read).length;
 const property=useMemo(()=>{if(!selected)return null;if(selected.leadId)return leads.find(lead=>lead.id===selected.leadId)||null;const text=`${selected.title} ${selected.message} ${selected.customer||""} ${selected.address||""}`.toLowerCase();return leads.find(lead=>text.includes(lead.name.toLowerCase())||text.includes(lead.address.toLowerCase()))||null},[selected,leads]);
 function open(item:Notification){setSelected(item);if(!item.read){markNotificationRead(item.id);refresh()}}
 return <MobileRoleGuard allowed={["admin","manager"]}><main className="mobile-app-shell role-mobile-shell mobile-native-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/admin"/><div><strong>Alerts</strong><span>Activity and attention</span></div><button className="mobile-native-add mobile-native-check" onClick={()=>{markNotificationsRead();refresh()}} aria-label="Mark all read">✓</button></header><section className="mobile-native-hero alert"><span>LIVE INBOX</span><h1>{unread?`${unread} alert${unread===1?"":"s"} need attention.`:"You are all caught up."}</h1><p>Tap any alert to see the complete message and related house.</p></section><div className="mobile-native-toggle"><button className={!unreadOnly?"active":""} onClick={()=>setUnreadOnly(false)}>All <b>{items.length}</b></button><button className={unreadOnly?"active":""} onClick={()=>setUnreadOnly(true)}>Unread <b>{unread}</b></button></div><section className="mobile-alert-list">{visible.map(item=><button type="button" className={`mobile-alert-item ${item.read?"read":""}`} key={item.id} onClick={()=>open(item)}><i>{icon(item.type)}</i><div><span>{item.type}</span><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString("en-CA",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div>{!item.read&&<b/>}</button>)}{!visible.length&&<div className="mobile-native-empty"><i>✓</i><strong>No alerts</strong><p>Nothing needs attention in this view.</p></div>}</section>{selected&&<div className="mobile-native-modal"><button className="mobile-native-scrim" onClick={()=>setSelected(null)} aria-label="Close alert"/><section><header><div><span>{selected.type.toUpperCase()} ALERT</span><h2>{selected.title}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><div className="mobile-alert-detail"><label>Complete message</label><p>{selected.message}</p><dl><div><dt>Customer</dt><dd>{property?.name||selected.customer||"Not linked"}</dd></div><div><dt>House</dt><dd>{property?.address||selected.address||"No property identified"}</dd></div><div><dt>Service</dt><dd>{property?.service||"Not specified"}</dd></div><div><dt>Status</dt><dd>{property?.status||selected.type}</dd></div><div><dt>Received</dt><dd>{new Date(selected.createdAt).toLocaleString()}</dd></div></dl>{property?<Link className="mobile-native-submit" href={`/admin/customers/${property.id}?tab=service`}>Open property details</Link>:<Link className="mobile-native-submit" href="/admin/alerts">Open Alert Center</Link>}</div></section></div>}<MobileAdminNav active="alerts"/></main></MobileRoleGuard>
}
