import{NextRequest,NextResponse}from"next/server";
import{createClient}from"@supabase/supabase-js";
export const dynamic="force-dynamic";

function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Company settings are not configured on the server.");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function requireAdmin(request:NextRequest){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)throw new Error("Sign in as company Admin.");const db=client();const{data:auth,error:authError}=await db.auth.getUser(token);if(authError||!auth.user)throw new Error("Your login expired. Sign in again.");const{data:profile,error}=await db.from("profiles").select("id,role,active,company_id,organization_id").eq("id",auth.user.id).single();if(error||!profile?.active||profile.role!=="admin")throw new Error("Only the active company Admin can change this code.");const companyId=profile.company_id||profile.organization_id;if(!companyId)throw new Error("Admin is not linked to a company.");return{db,companyId,adminId:profile.id}}
function fail(error:unknown,status=400){return NextResponse.json({error:error instanceof Error?error.message:"Company settings failed."},{status})}

export async function GET(request:NextRequest){try{const{db,companyId}=await requireAdmin(request);const{data,error}=await db.from("organizations").select("id,name,referral_code").eq("id",companyId).is("deleted_at",null).single();if(error)throw error;return NextResponse.json({company:data})}catch(error){return fail(error,401)}}

export async function PATCH(request:NextRequest){try{const{db,companyId,adminId}=await requireAdmin(request);const body=await request.json() as{referralCode?:string};const code=String(body.referralCode||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(!/^[A-Z0-9]{4,12}$/.test(code))throw new Error("Use 4 to 12 letters or numbers, without spaces or symbols.");const{data:used}=await db.from("organizations").select("id").eq("referral_code",code).neq("id",companyId).maybeSingle();if(used)throw new Error("This code is already used by another company.");const{data,error}=await db.from("organizations").update({referral_code:code,updated_at:new Date().toISOString()}).eq("id",companyId).is("deleted_at",null).select("id,name,referral_code").single();if(error||!data)throw new Error(error?.message||"Company code could not be updated.");await db.from("master_audit_log").insert({company_id:companyId,action:"company.referral_code_changed",entity_type:"organization",entity_id:companyId,details:{changed_by_profile_id:adminId,referral_code:code}});return NextResponse.json({company:data,message:`Company code changed to ${code}.`})}catch(error){return fail(error)}}
