from pathlib import Path

employees_path = Path('app/admin/employees/page.tsx')
text = employees_path.read_text()

text = text.replace('import { useEffect, useMemo, useState } from "react";\n', 'import { useEffect, useMemo, useState } from "react";\nimport { useRouter } from "next/navigation";\n')
text = text.replace('  serviceName: string;\n};', '  serviceName: string;\n  customerId: string | null;\n  propertyId: string | null;\n};')
text = text.replace('export default function EmployeesPage() {\n', 'const CONTRACTS_PER_PAGE = 18;\nconst EXPANDED_STORAGE_KEY = "damasio:employee-contracts-expanded";\n\nexport default function EmployeesPage() {\n  const router = useRouter();\n')
text = text.replace('  const [expandedId, setExpandedId] = useState<string | null>(null);\n', '  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());\n  const [contractPages, setContractPages] = useState<Record<string, number>>({});\n')
text = text.replace('              serviceName: String(job.serviceName || "Property Service"),\n', '              serviceName: String(job.serviceName || "Property Service"),\n              customerId: job.customerId ? String(job.customerId) : null,\n              propertyId: job.propertyId ? String(job.propertyId) : null,\n')
text = text.replace('  useEffect(() => { void refresh(); }, []);\n', '''  useEffect(() => { void refresh(); }, []);\n\n  useEffect(() => {\n    try {\n      const saved = JSON.parse(window.localStorage.getItem(EXPANDED_STORAGE_KEY) || "[]");\n      if (Array.isArray(saved)) setExpandedIds(new Set(saved.map(String)));\n    } catch {\n      setExpandedIds(new Set());\n    }\n  }, []);\n\n  useEffect(() => {\n    window.localStorage.setItem(\n      EXPANDED_STORAGE_KEY,\n      JSON.stringify([...expandedIds]),\n    );\n  }, [expandedIds]);\n\n  function toggleContracts(employeeId: string) {\n    setExpandedIds(current => {\n      const next = new Set(current);\n      if (next.has(employeeId)) next.delete(employeeId);\n      else next.add(employeeId);\n      return next;\n    });\n  }\n\n  function openContract(contract: EmployeeContract) {\n    if (contract.customerId) {\n      router.push(`/admin/customers/${contract.customerId}`);\n    }\n  }\n''')
text = text.replace('      const expanded = expandedId === employee.id;\n      const contracts = employee.contracts || [];\n', '''      const expanded = expandedIds.has(employee.id);\n      const contracts = employee.contracts || [];\n      const pageCount = Math.max(1, Math.ceil(contracts.length / CONTRACTS_PER_PAGE));\n      const page = Math.min(contractPages[employee.id] || 1, pageCount);\n      const pageContracts = contracts.slice(\n        (page - 1) * CONTRACTS_PER_PAGE,\n        page * CONTRACTS_PER_PAGE,\n      );\n''')
text = text.replace('onClick={() => setExpandedId(expanded ? null : employee.id)}', 'onClick={() => toggleContracts(employee.id)}')
old = '''expanded ? <tr key={`${employee.id}-contracts`} className="employee-contract-row"><td colSpan={7}><div className="employee-contract-list">{contracts.length ? contracts.map(contract => <article key={contract.id}><strong>{contract.customerName}</strong><span>{contract.address}</span><small>{contract.serviceName}</small></article>) : <p>No canonical contracts assigned to this Employee.</p>}</div></td></tr> : null,'''
new = '''expanded ? <tr key={`${employee.id}-contracts`} className="employee-contract-row"><td colSpan={7}><div className="employee-contract-list">{contracts.length ? pageContracts.map(contract => <button type="button" key={contract.id} onClick={() => openContract(contract)}><strong>{contract.customerName}</strong><span>{contract.address}</span><small>{contract.serviceName}</small></button>) : <p>No canonical contracts assigned to this Employee.</p>}</div>{pageCount > 1 && <nav className="employee-contract-pagination" aria-label={`${employee.full_name} contract pages`}><button type="button" disabled={page === 1} onClick={() => setContractPages(current => ({ ...current, [employee.id]: Math.max(1, page - 1) }))}>Previous</button>{Array.from({ length: pageCount }, (_, index) => index + 1).map(number => <button type="button" key={number} className={number === page ? "active" : ""} aria-current={number === page ? "page" : undefined} onClick={() => setContractPages(current => ({ ...current, [employee.id]: number }))}>{number}</button>)}<button type="button" disabled={page === pageCount} onClick={() => setContractPages(current => ({ ...current, [employee.id]: Math.min(pageCount, page + 1) }))}>Next</button></nav>}</td></tr> : null,'''
if old not in text:
    raise SystemExit('employee contract row pattern not found')
text = text.replace(old, new)
text = text.replace('.employee-contract-list article{display:grid;gap:3px;padding:11px 13px;border:1px solid #dce9e2;border-radius:12px;background:#fff}.employee-contract-list article span,.employee-contract-list article small{color:#63766c}.employee-contract-list p{margin:0;color:#63766c}', '.employee-contract-list button{display:grid;gap:3px;padding:11px 13px;border:1px solid #dce9e2;border-radius:12px;background:#fff;text-align:left;color:inherit;cursor:pointer}.employee-contract-list button:hover,.employee-contract-list button:focus-visible{border-color:#0b684c;background:#f1f8f4;outline:none}.employee-contract-list button span,.employee-contract-list button small{color:#63766c}.employee-contract-list p{margin:0;color:#63766c}.employee-contract-pagination{display:flex;justify-content:center;align-items:center;flex-wrap:wrap;gap:6px;padding:0 18px 18px}.employee-contract-pagination button{min-width:34px;height:34px;border:1px solid #d1dfd7;border-radius:9px;background:#fff;color:#315545;font-weight:800;cursor:pointer}.employee-contract-pagination button.active{border-color:#0b684c;background:#0b684c;color:#fff}.employee-contract-pagination button:disabled{opacity:.45;cursor:not-allowed}')
employees_path.write_text(text)

shell_path = Path('components/admin/AdminShell.tsx')
shell = shell_path.read_text()
shell = shell.replace('      <main className="studio-main">{children}</main>\n', '''      <main className="studio-main">{children}</main>\n      <style jsx global>{`\n        .studio-rail>nav a{display:grid!important;grid-template-columns:32px minmax(0,1fr);align-items:center;min-height:44px;gap:10px}\n        .studio-rail>nav a>span{display:grid!important;place-items:center;width:32px;height:32px;line-height:1;text-align:center;align-self:center;justify-self:center}\n      `}</style>\n''')
shell_path.write_text(shell)

check_path = Path('scripts/validate-employee-contract-ux.mjs')
check_path.write_text('''import assert from "node:assert/strict";\nimport { readFileSync } from "node:fs";\nconst employees = readFileSync("app/admin/employees/page.tsx", "utf8");\nconst shell = readFileSync("components/admin/AdminShell.tsx", "utf8");\nassert.match(employees, /CONTRACTS_PER_PAGE = 18/);\nassert.match(employees, /expandedIds/);\nassert.match(employees, /localStorage\.setItem/);\nassert.match(employees, /pageContracts/);\nassert.match(employees, /router\.push\(`\\\/admin\\\/customers\\\/\$\{contract\.customerId\}`\)/);\nassert.match(shell, /grid-template-columns:32px minmax\(0,1fr\)/);\nconsole.log("PASS Employee contract UX contract");\n''')

package_path = Path('package.json')
package = package_path.read_text()
package = package.replace('"test:employee-contract-routing": "node scripts/validate-employee-contract-routing.mjs",', '"test:employee-contract-routing": "node scripts/validate-employee-contract-routing.mjs",\n    "test:employee-contract-ux": "node scripts/validate-employee-contract-ux.mjs",')
package = package.replace('pnpm test:employee-contract-routing &&', 'pnpm test:employee-contract-routing && pnpm test:employee-contract-ux &&')
package_path.write_text(package)
