"use client";
import {ChangeEvent,useEffect,useMemo,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileCustomerNav} from "@/components/mobile/MobileCustomerNav";
import {Estimate,finalizeEstimate,getEstimates,getLeads} from "@/lib/storage";
import {useCustomerBilling} from "@/lib/hooks/useCustomerBilling";
import {useCustomerWallet} from "@/lib/hooks/useCustomerWallet";
import {loadCustomerPortal} from "@/lib/services/customerPortalService";
import {getPropertyPhotoHistory,uploadPropertyProfilePhoto,type PropertyPhotoHistory} from "@/lib/services/propertyPhotoService";
import type {CustomerPortalBoard} from "@/lib/repositories/customerPortalRepository";
const empty:CustomerPortalBoard={property:null,visits:[],tasks:[],requests:[],quotes:[],feedback:[]};
const config:Record<string,{title:string;subtitle:string;eyebrow:string;icon:string}>={services:{title:"My Services",subtitle:"Appointments and active work",eyebrow:"PROPERTY CARE",icon:"✦"},history:{title:"History",subtitle:"Completed services",eyebrow:"SERVICE RECORD",icon:"↶"},estimates:{title:"Estimates",subtitle:"Review and approve",eyebrow:"QUOTES",icon:"▤"},invoices:{title:"Invoices",subtitle:"Billing documents",eyebrow:"BILLING",icon:"≡"},payments:{title:"Payments",subtitle:"Balance and preferences",eyebrow:"WALLET",icon:"$"},feedback:{title:"Feedback",subtitle:"Reviews and follow-up",eyebrow:"YOUR EXPERIENCE",icon:"★"},profile:{title:"My Property",subtitle:"Home and access details",eyebrow:"PROPERTY PROFILE",icon:"○"},issues:{title:"Return Visits",subtitle:"Service issues",eyebrow:"FOLLOW-UP",icon:"!"},more:{title:"More",subtitle:"Customer tools",eyebrow:"MY ACCOUNT",icon:"•••"}};
export default function MobileCustomerSection(){
 const section=String(useParams().section||"more");const page=config[section]||config.more;const router=useRouter();const[board,setBoard]=useState<CustomerPortalBoard>(empty);const[photoHistory,setPhotoHistory]=useState<PropertyPhotoHistory|null>(null);const[estimates,setEstimates]=useState<Estimate[]>([]);const[open,setOpen]=useState("");const[message,setMessage]=useState("");
 const{invoices,source:billingSource,loading:billingLoading,message:billingMessage,payingId,summary:billingSummary,checkout,clearMessage:clearBillingMessage}=useCustomerBilling();
 const wallet=useCustomerWallet();const{balanceCredits,transactions:walletTransactions,loading:walletLoading,openingCredits,message:walletMessage,topUp,clearMessage:clearWalletMessage}=wallet;
 function refresh(){void loadCustomerPortal().then(setBoard).catch(()=>setMessage("Your customer information is temporarily unavailable. Please try again shortly."));setEstimates(getEstimates().filter(item=>item.status!=="draft"))}
 useEffect(()=>refresh(),[]);
 useEffect(()=>{if(board.property?.propertyId)void getPropertyPhotoHistory(board.property.propertyId).then(setPhotoHistory).catch(()=>setPhotoHistory(null))},[board.property?.propertyId]);
 const next=useMemo(()=>board.visits.filter(item=>!["completed","cancelled"].includes(item.status)).sort((a,b)=>String(a.scheduledDate).localeCompare(String(b.scheduledDate)))[0],[board.visits]);const history=board.visits.filter(item=>item.status==="completed").sort((a,b)=>String(b.scheduledDate).localeCompare(String(a.scheduledDate)));const activeIssues=board.tasks.filter(item=>!["completed","resolved"].includes(item.status));const due=billingSummary.due;const lead=getLeads()[0];
 function decide(item:Estimate,status:"approved"|"declined"){if(!window.confirm(status==="approved"?"Approve this estimate and create its invoice?":"Decline this estimate?"))return;const result=finalizeEstimate(item.id,status);setMessage(result.message);refresh();if(result.ok&&status==="approved")router.push("/mobile/customer/payments")}
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];const propertyId=board.property?.propertyId;if(!file||!propertyId)return;try{setMessage("Uploading property photo...");const url=await uploadPropertyProfilePhoto(propertyId,file);setPhotoHistory(current=>({...current||{visits:[]},profilePhotoUrl:url}));setMessage("Official property photo updated for Admin and the crew.")}catch(error){setMessage(error instanceof Error?error.message:"Property photo could not be uploaded.")}finally{event.target.value=""}}
 const activeNav=section==="services"||section==="history"?"services":section==="payments"||section==="invoices"||section==="estimates"?"billing":"more";
 const visibleMessage=message||billingMessage||walletMessage;
 return <MobileRoleGuard allowed={["customer"]}><main className="mobile-app-shell role-mobile-shell mobile-customer-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/customer"/><div><strong>{page.title}</strong><span>{page.subtitle}</span></div><span className="role-mobile-avatar">{page.icon}</span></header><section className={`customer-native-hero ${section}`}><span>{page.eyebrow}</span><h1>{section==="services"?(next?"Your next visit is scheduled.":"Scheduling your next visit."):section==="payments"?`${balanceCredits.toFixed(0)} credits available.`:section==="issues"?`${activeIssues.length} active follow-up${activeIssues.length===1?"":"s"}.`:page.title}</h1><p>{lead?.address||board.property?.address||"Your customer account"}</p></section>{visibleMessage&&<div className="customer-native-message">{visibleMessage}<button onClick={()=>{setMessage("");clearBillingMessage();clearWalletMessage()}}>×</button></div>}
 {section==="services"&&<section className="customer-service-stack">{next?<article className="customer-next-card"><span>Next appointment</span><strong>{niceDate(next.scheduledDate)}</strong><p>{next.serviceName} · {next.crewName||"Crew pending"}</p><div><b>{next.status}</b><small>No fixed arrival hour is promised.</small></div></article>:<Empty icon="◷" title="Waiting for scheduling" text="The company will publish your next visit here."/>}<h2>Recent services</h2>{history.slice(0,3).map(item=><CustomerRow key={item.id} icon="✓" title={item.serviceName} subtitle={niceDate(item.scheduledDate)} status="Completed" onClick={()=>router.push("/mobile/customer/history")}/>)}</section>}
 {section==="history"&&<section className="customer-native-list customer-service-history">{history.map(item=>{const detail=photoHistory?.visits.find(visit=>visit.id===item.id);const review=board.feedback.find(value=>value.visitId===item.id);return <article key={item.id} className={open===item.id?"open":""}><button onClick={()=>setOpen(open===item.id?"":item.id)}><i>✓</i><div><strong>{item.serviceName}</strong><span>{niceDate(item.scheduledDate)} · {item.crewName||"Crew"}</span></div><b>›</b></button>{open===item.id&&<div className="customer-row-detail"><div className="customer-history-times"><span>Started<strong>{item.startedAt?new Date(item.startedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</strong></span><span>Finished<strong>{item.finishedAt?new Date(item.finishedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</strong></span><span>Duration<strong>{item.durationSeconds?`${Math.round(item.durationSeconds/60)} min`:"—"}</strong></span></div><p>{item.customerVisibleSummary||item.employeeNotes||"Service completed."}</p>{detail?.photos.length?<div className="customer-history-photos">{detail.photos.map(photo=><figure key={photo.id}><img src={photo.url} alt={photo.caption||photo.type}/><figcaption>{photo.caption||photo.type}</figcaption></figure>)}</div>:<span>No service photos were published for this visit.</span>}<div className="customer-history-review"><strong>{review?.rating?`${review.rating} ★`:"Not reviewed"}</strong><span>{review?.comment||"Your evaluation will appear here."}</span></div></div>}</article>})}{!history.length&&<Empty icon="↶" title="No completed services" text="Completed visits will appear here."/>}</section>}
 {section==="estimates"&&<section className="customer-document-list">{estimates.map(item=><article key={item.id}><header><div><span>{item.number}</span><strong>{item.title}</strong><small>{item.status}</small></div><b>${item.total.toFixed(2)}</b></header><p>{item.description}</p>{!["approved","declined"].includes(item.status)&&<div><button onClick={()=>decide(item,"declined")}>Decline</button><button className="primary" onClick={()=>decide(item,"approved")}>Approve</button></div>}</article>)}{!estimates.length&&<Empty icon="▤" title="No estimates" text="Quotes sent by the company will appear here."/>}</section>}
 {section==="invoices"&&<section className="customer-document-list">{invoices.map(item=><article key={item.id}><header><div><span>{item.number}</span><strong>{item.service}</strong><small>{new Date(item.createdAt).toLocaleDateString("en-CA")}</small></div><b>${item.total.toFixed(2)}</b></header><div className="customer-invoice-status"><span>{item.status.replaceAll("_"," ")}</span><small>{item.status==="paid"?"Confirmed":"Awaiting payment"}</small></div>{item.status!=="paid"&&<button className="customer-pay-button" disabled={payingId===item.id||billingSource!=="live"} onClick={()=>void checkout(item.id)}>{payingId===item.id?"Opening Stripe...":"Pay securely"}</button>}</article>)}{billingLoading?<Empty icon="…" title="Loading invoices" text="Checking your connected billing records."/>:!invoices.length&&<Empty icon="≡" title="No invoices" text="Approved work will appear here."/>}</section>}
 {section==="payments"&&<section className="customer-payment-native"><div className="customer-balance-grid"><article><span>Wallet credits</span><strong>{walletLoading?"…":balanceCredits.toFixed(0)}</strong><small>1 credit = $1</small></article><article><span>Amount due</span><strong>${due.toFixed(2)}</strong><small>{billingSummary.paidCount} paid invoices</small></article></div><h2>Add credits</h2><div className="customer-wallet-topups">{[1,5,10,25,50].map(credits=><button key={credits} disabled={openingCredits>0} onClick={()=>void topUp(credits)}><strong>{credits}</strong><span>{openingCredits===credits?"Opening Stripe...":`$${credits}`}</span></button>)}</div><p className="customer-wallet-note">Credits stay on your account and can be used for future services or tips.</p><h2>Secure checkout</h2><button className="selected" disabled><i>▣</i><span><strong>Card / bank with Stripe</strong><small>Encrypted payment. Card details stay with Stripe.</small></span><b>✓</b></button><div className="customer-mobile-pay-list">{invoices.filter(item=>item.status!=="paid").map(item=><article key={item.id}><div><span>{item.number}</span><strong>{item.service}</strong></div><b>${item.total.toFixed(2)}</b><button disabled={payingId===item.id||billingSource!=="live"} onClick={()=>void checkout(item.id)}>{payingId===item.id?"Opening...":"Pay"}</button></article>)}{!billingLoading&&billingSummary.openCount===0&&<Empty icon="✓" title="Nothing due" text="Your account has no open invoices."/>}</div>{walletTransactions.length>0&&<><h2>Credit history</h2><div className="customer-wallet-history">{walletTransactions.slice(0,5).map(item=><article key={item.id}><div><strong>{item.description||item.type}</strong><span>{new Date(item.createdAt).toLocaleDateString("en-CA")}</span></div><b>{item.credits>0?"+":""}{item.credits.toFixed(0)}</b></article>)}</div></>}</section>}
 {section==="issues"&&<section className="customer-native-list">{[...activeIssues,...board.tasks.filter(item=>["completed","resolved"].includes(item.status))].map(item=><article key={item.id}><button onClick={()=>setOpen(open===item.id?"":item.id)}><i>↺</i><div><strong>{item.title}</strong><span>{item.status} · {niceDate(item.scheduledDate)}</span></div><b>›</b></button>{open===item.id&&<div className="customer-row-detail"><p>{item.customerIssue}</p>{item.completionSummary&&<span>{item.completionSummary}</span>}</div>}</article>)}{!board.tasks.length&&<Empty icon="✓" title="No return visits" text="Your service follow-up list is clear."/>}</section>}
 {section==="profile"&&<section className="customer-profile-native"><div className="customer-property-photo">{photoHistory?.profilePhotoUrl?<img src={photoHistory.profilePhotoUrl} alt="Property"/>:<span>🏠</span>}</div><label>Official property photo<input type="file" accept="image/*" onChange={upload}/></label><dl><div><dt>Name</dt><dd>{board.property?.customerName||lead?.name||"Customer"}</dd></div><div><dt>Address</dt><dd>{board.property?.address||lead?.address||"Not available"}</dd></div><div><dt>Lot size</dt><dd>{board.property?.lotSize||"Not set"}</dd></div><div><dt>Access notes</dt><dd>{board.property?.accessNotes||"No special access note"}</dd></div></dl></section>}
 {section==="feedback"&&<section className="customer-native-list">{history.map(item=>{const review=board.feedback.find(value=>value.visitId===item.id);return <CustomerRow key={item.id} icon={review?"✓":"★"} title={item.serviceName} subtitle={review?`${review.rating} stars · ${review.comment||"Reviewed"}`:"Waiting for your review"} status={niceDate(item.scheduledDate)} onClick={()=>router.push("/mobile/customer")}/>})}{!history.length&&<Empty icon="★" title="Nothing to review" text="Completed services will appear here."/>}</section>}
 {section==="more"&&<section className="customer-more-grid">{[["History","↶","history"],["Estimates","▤","estimates"],["Invoices","≡","invoices"],["Feedback","★","feedback"],["Return Visits","!","issues"],["Profile","○","profile"]].map(([label,icon,path])=><button key={path} onClick={()=>router.push(`/mobile/customer/${path}`)}><i>{icon}</i><strong>{label}</strong><span>Open ›</span></button>)}</section>}
 <MobileCustomerNav active={activeNav}/></main></MobileRoleGuard>
}
function niceDate(value?:string|null){return value?new Date(`${value}T12:00:00`).toLocaleDateString("en-CA",{weekday:"short",month:"short",day:"numeric"}):"Pending"}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="customer-native-empty"><i>{icon}</i><strong>{title}</strong><p>{text}</p></div>}
function CustomerRow({icon,title,subtitle,status,onClick}:{icon:string;title:string;subtitle:string;status:string;onClick:()=>void}){return <article><button onClick={onClick}><i>{icon}</i><div><strong>{title}</strong><span>{subtitle}</span></div><em>{status}</em></button></article>}
