"use client";
import {ChangeEvent,useEffect,useMemo,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {MobileRoleGuard} from "@/components/mobile/MobileRoleGuard";
import {MobileBackButton} from "@/components/mobile/MobileBackButton";
import {MobileCustomerNav} from "@/components/mobile/MobileCustomerNav";
import {CustomerPaymentProfile,Estimate,Invoice,finalizeEstimate,getCustomerPaymentProfile,getEstimates,getInvoices,getLeads,saveCustomerPaymentProfile,setPropertyPhoto} from "@/lib/storage";
import {loadCustomerPortal} from "@/lib/services/customerPortalService";
import type {CustomerPortalBoard} from "@/lib/repositories/customerPortalRepository";
const empty:CustomerPortalBoard={property:null,visits:[],tasks:[],requests:[],quotes:[],feedback:[]};
const config:Record<string,{title:string;subtitle:string;eyebrow:string;icon:string}>={services:{title:"My Services",subtitle:"Appointments and active work",eyebrow:"PROPERTY CARE",icon:"✦"},history:{title:"History",subtitle:"Completed services",eyebrow:"SERVICE RECORD",icon:"↶"},estimates:{title:"Estimates",subtitle:"Review and approve",eyebrow:"QUOTES",icon:"▤"},invoices:{title:"Invoices",subtitle:"Billing documents",eyebrow:"BILLING",icon:"≡"},payments:{title:"Payments",subtitle:"Balance and preferences",eyebrow:"WALLET",icon:"$"},feedback:{title:"Feedback",subtitle:"Reviews and follow-up",eyebrow:"YOUR EXPERIENCE",icon:"★"},profile:{title:"My Property",subtitle:"Home and access details",eyebrow:"PROPERTY PROFILE",icon:"○"},issues:{title:"Return Visits",subtitle:"Service issues",eyebrow:"FOLLOW-UP",icon:"!"},more:{title:"More",subtitle:"Customer tools",eyebrow:"MY ACCOUNT",icon:"•••"}};
export default function MobileCustomerSection(){
 const section=String(useParams().section||"more");const page=config[section]||config.more;const router=useRouter();const[board,setBoard]=useState<CustomerPortalBoard>(empty);const[estimates,setEstimates]=useState<Estimate[]>([]);const[invoices,setInvoices]=useState<Invoice[]>([]);const[payment,setPayment]=useState<CustomerPaymentProfile|null>(null);const[open,setOpen]=useState("");const[message,setMessage]=useState("");
 function refresh(){void loadCustomerPortal().then(setBoard).catch(error=>setMessage(error instanceof Error?error.message:"Customer information could not be loaded."));setEstimates(getEstimates().filter(item=>item.status!=="draft"));setInvoices(getInvoices());setPayment(getCustomerPaymentProfile())}
 useEffect(()=>refresh(),[]);
 const next=useMemo(()=>board.visits.filter(item=>!["completed","cancelled"].includes(item.status)).sort((a,b)=>String(a.scheduledDate).localeCompare(String(b.scheduledDate)))[0],[board.visits]);const history=board.visits.filter(item=>item.status==="completed").sort((a,b)=>String(b.scheduledDate).localeCompare(String(a.scheduledDate)));const activeIssues=board.tasks.filter(item=>!["completed","resolved"].includes(item.status));const due=invoices.filter(item=>item.status!=="paid").reduce((sum,item)=>sum+item.total,0);const lead=getLeads()[0];
 function decide(item:Estimate,status:"approved"|"declined"){if(!window.confirm(status==="approved"?"Approve this estimate and create its invoice?":"Decline this estimate?"))return;const result=finalizeEstimate(item.id,status);setMessage(result.message);refresh();if(result.ok&&status==="approved")router.push("/mobile/customer/payments")}
 function savePayment(patch:Partial<CustomerPaymentProfile>){setPayment(saveCustomerPaymentProfile(patch));setMessage("Payment preference saved.")}
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file||!lead)return;const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});setPropertyPhoto(lead.id,data);setMessage("Official property photo updated.")}
 const activeNav=section==="services"||section==="history"?"services":section==="payments"||section==="invoices"||section==="estimates"?"billing":"more";
 return <MobileRoleGuard allowed={["customer"]}><main className="mobile-app-shell role-mobile-shell mobile-customer-subpage"><header className="role-mobile-topbar"><MobileBackButton fallback="/mobile/customer"/><div><strong>{page.title}</strong><span>{page.subtitle}</span></div><span className="role-mobile-avatar">{page.icon}</span></header><section className={`customer-native-hero ${section}`}><span>{page.eyebrow}</span><h1>{section==="services"?(next?"Your next visit is scheduled.":"Scheduling your next visit."):section==="payments"?`$${due.toFixed(2)} currently due.`:section==="issues"?`${activeIssues.length} active follow-up${activeIssues.length===1?"":"s"}.`:page.title}</h1><p>{lead?.address||board.property?.address||"Your customer account"}</p></section>{message&&<div className="customer-native-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 {section==="services"&&<section className="customer-service-stack">{next?<article className="customer-next-card"><span>Next appointment</span><strong>{niceDate(next.scheduledDate)}</strong><p>{next.serviceName} · {next.crewName||"Crew pending"}</p><div><b>{next.status}</b><small>No fixed arrival hour is promised.</small></div></article>:<Empty icon="◷" title="Waiting for scheduling" text="The company will publish your next visit here."/>}<h2>Recent services</h2>{history.slice(0,3).map(item=><CustomerRow key={item.id} icon="✓" title={item.serviceName} subtitle={niceDate(item.scheduledDate)} status="Completed" onClick={()=>router.push("/mobile/customer/history")}/>)}</section>}
 {section==="history"&&<section className="customer-native-list">{history.map(item=><article key={item.id} className={open===item.id?"open":""}><button onClick={()=>setOpen(open===item.id?"":item.id)}><i>✓</i><div><strong>{item.serviceName}</strong><span>{niceDate(item.scheduledDate)} · {item.crewName||"Crew"}</span></div><b>›</b></button>{open===item.id&&<div className="customer-row-detail"><p>{item.customerVisibleSummary||item.employeeNotes||"Service completed."}</p><span>Duration: {item.durationSeconds?`${Math.round(item.durationSeconds/60)} min`:"Not recorded"}</span></div>}</article>)}{!history.length&&<Empty icon="↶" title="No completed services" text="Completed visits will appear here."/>}</section>}
 {section==="estimates"&&<section className="customer-document-list">{estimates.map(item=><article key={item.id}><header><div><span>{item.number}</span><strong>{item.title}</strong><small>{item.status}</small></div><b>${item.total.toFixed(2)}</b></header><p>{item.description}</p>{!["approved","declined"].includes(item.status)&&<div><button onClick={()=>decide(item,"declined")}>Decline</button><button className="primary" onClick={()=>decide(item,"approved")}>Approve</button></div>}</article>)}{!estimates.length&&<Empty icon="▤" title="No estimates" text="Quotes sent by the company will appear here."/>}</section>}
 {section==="invoices"&&<section className="customer-document-list">{invoices.map(item=><article key={item.id}><header><div><span>{item.number}</span><strong>{item.service}</strong><small>{new Date(item.createdAt).toLocaleDateString("en-CA")}</small></div><b>${item.total.toFixed(2)}</b></header><div className="customer-invoice-status"><span>{item.status.replace("_"," ")}</span>{item.paymentMethod&&<small>{item.paymentMethod}</small>}</div>{item.status!=="paid"&&<button className="customer-pay-button" onClick={()=>router.push("/mobile/customer/payments")}>Payment options</button>}</article>)}{!invoices.length&&<Empty icon="≡" title="No invoices" text="Approved work will appear here."/>}</section>}
 {section==="payments"&&payment&&<section className="customer-payment-native"><div className="customer-balance-grid"><article><span>Open invoices</span><strong>${due.toFixed(2)}</strong></article><article><span>Account balance</span><strong>${payment.balance.toFixed(2)}</strong></article></div><h2>Preferred payment source</h2><button className={payment.primaryMethod==="stripe"?"selected":""} onClick={()=>savePayment({primaryMethod:"stripe"})}><i>▣</i><span><strong>Card / bank with Stripe</strong><small>Secure checkout when enabled</small></span><b>✓</b></button><button className={payment.primaryMethod==="account_balance"?"selected":""} onClick={()=>savePayment({primaryMethod:"account_balance"})}><i>$</i><span><strong>Account balance</strong><small>Use verified funds first</small></span><b>✓</b></button><label className="customer-auto-pay"><span><strong>Automatic payments</strong><small>Save preference only; charging remains disabled.</small></span><input type="checkbox" checked={payment.automaticPayments} onChange={event=>savePayment({automaticPayments:event.target.checked})}/></label></section>}
 {section==="issues"&&<section className="customer-native-list">{[...activeIssues,...board.tasks.filter(item=>["completed","resolved"].includes(item.status))].map(item=><article key={item.id}><button onClick={()=>setOpen(open===item.id?"":item.id)}><i>↺</i><div><strong>{item.title}</strong><span>{item.status} · {niceDate(item.scheduledDate)}</span></div><b>›</b></button>{open===item.id&&<div className="customer-row-detail"><p>{item.customerIssue}</p>{item.completionSummary&&<span>{item.completionSummary}</span>}</div>}</article>)}{!board.tasks.length&&<Empty icon="✓" title="No return visits" text="Your service follow-up list is clear."/>}</section>}
 {section==="profile"&&<section className="customer-profile-native"><div className="customer-property-photo">{lead?.propertyPhoto?<img src={lead.propertyPhoto} alt="Property"/>:<span>🏠</span>}</div><label>Official property photo<input type="file" accept="image/*" onChange={upload}/></label><dl><div><dt>Name</dt><dd>{lead?.name||"Customer"}</dd></div><div><dt>Address</dt><dd>{lead?.address||board.property?.address||"Not available"}</dd></div><div><dt>Access notes</dt><dd>{lead?.propertyDetails?.accessNotes||board.property?.accessNotes||"No special access note"}</dd></div></dl></section>}
 {section==="feedback"&&<section className="customer-native-list">{history.map(item=>{const review=board.feedback.find(value=>value.visitId===item.id);return <CustomerRow key={item.id} icon={review?"✓":"★"} title={item.serviceName} subtitle={review?`${review.rating} stars · ${review.comment||"Reviewed"}`:"Waiting for your review"} status={niceDate(item.scheduledDate)} onClick={()=>router.push("/mobile/customer")}/>})}{!history.length&&<Empty icon="★" title="Nothing to review" text="Completed services will appear here."/>}</section>}
 {section==="more"&&<section className="customer-more-grid">{[["History","↶","history"],["Estimates","▤","estimates"],["Invoices","≡","invoices"],["Feedback","★","feedback"],["Return Visits","!","issues"],["Profile","○","profile"]].map(([label,icon,path])=><button key={path} onClick={()=>router.push(`/mobile/customer/${path}`)}><i>{icon}</i><strong>{label}</strong><span>Open ›</span></button>)}</section>}
 <MobileCustomerNav active={activeNav}/></main></MobileRoleGuard>
}
function niceDate(value?:string|null){return value?new Date(`${value}T12:00:00`).toLocaleDateString("en-CA",{weekday:"short",month:"short",day:"numeric"}):"Pending"}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="customer-native-empty"><i>{icon}</i><strong>{title}</strong><p>{text}</p></div>}
function CustomerRow({icon,title,subtitle,status,onClick}:{icon:string;title:string;subtitle:string;status:string;onClick:()=>void}){return <article><button onClick={onClick}><i>{icon}</i><div><strong>{title}</strong><span>{subtitle}</span></div><em>{status}</em></button></article>}
