"use client";

import Link from "next/link";
import { Fragment, useEffect, useMemo, useState } from "react";
import { AdminShell } from "@/components/admin/AdminShell";
import { CompactFilter } from "@/components/admin/CompactFilter";
import { useCustomerProperties } from "@/lib/hooks/useCustomerProperties";
import { deleteCustomers } from "@/lib/services/customerPropertyService";
import { loadSchedulingDispatchBoard } from "@/lib/services/schedulingService";

const lawnOrder:Record<string,number>={xs:1,small:2,legacy:3,oversize:4};

export default function Customers(){
  const { records, loading, error, refresh } = useCustomerProperties();
  const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");const [city,setCity]=useState("all");const [sort,setSort]=useState("city");const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [today,setToday]=useState({homes:0,completed:0,tasks:0,tasksCompleted:0});
  useEffect(()=>{let alive=true;async function sync(){try{const board=await loadSchedulingDispatchBoard({force:true});const date=new Date();const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;const visits=board.visits.filter(v=>v.scheduledDate===key&&!['cancelled','missed'].includes(v.status));const tasks=board.tasks.filter(t=>t.scheduledDate===key);if(alive)setToday({homes:visits.length,completed:visits.filter(v=>v.status==='completed').length,tasks:tasks.length,tasksCompleted:tasks.filter(t=>['completed','resolved'].includes(t.status)).length});}catch{}}void sync();const timer=setInterval(sync,20000);const onSync=()=>void sync();window.addEventListener('damasio:operations-changed',onSync);return()=>{alive=false;clearInterval(timer);window.removeEventListener('damasio:operations-changed',onSync)}},[]);
  const cities=useMemo(()=>[...new Set(records.map(r=>r.city).filter(Boolean))].sort(),[records]);
  const visible=useMemo(()=>records.filter(r=>{const hay=`${r.fullName} ${r.addressLine1} ${r.city} ${r.phone||""} ${r.email||""} ${r.lotSize||""} ${r.grassHeight||""}`.toLowerCase();if(query&&!hay.includes(query.toLowerCase()))return false;if(city!=="all"&&r.city!==city)return false;if(filter==="platform")return r.lockedByPlatform;if(filter==="company")return !r.lockedByPlatform;if(filter==="missing-phone")return !r.phone;if(filter==="missing-email")return !r.email;if(filter==="access")return Boolean(r.accessNotes||r.gate||r.dog);if(filter==="big-lawn")return r.lotSize==="legacy"||r.lotSize==="oversize";if(filter==="high-grass")return r.grassHeight==="4in"||r.grassHeight==="5in";if(filter==="with-notes")return Boolean(r.customerNotes||r.accessNotes||r.propertyNotes);return true;}).sort((a,b)=>sort==="lawn"?(lawnOrder[a.lotSize||""]||9)-(lawnOrder[b.lotSize||""]||9)||a.city.localeCompare(b.city):sort==="grass"?String(a.grassHeight||"").localeCompare(String(b.grassHeight||""))||a.city.localeCompare(b.city):a.city.localeCompare(b.city)||a.addressLine1.localeCompare(b.addressLine1)),[records,query,filter,city,sort]);
  const grouped=useMemo(()=>visible.reduce<Record<string,typeof visible>>((acc,r)=>{const k=r.city||"No city";(acc[k] ||= []).push(r);return acc;},{}),[visible]);
  const editableIds=useMemo(()=>[...new Set(visible.filter(r=>!r.lockedByPlatform).map(r=>r.customerId))],[visible]);const allVisibleSelected=editableIds.length>0&&editableIds.every(id=>selected.includes(id));
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])}function toggleAll(){setSelected(current=>allVisibleSelected?current.filter(id=>!editableIds.includes(id)):[...new Set([...current,...editableIds])])}
  async function remove(ids:string[],label:string){if(!ids.length)return;if(!window.confirm(`Remove ${label} from active customers?`))return;setBusy(true);setMessage("");try{const total=await deleteCustomers(ids);setSelected(current=>current.filter(id=>!ids.includes(id)));await refresh();setMessage(`${total} customer(s) removed.`)}catch(error){setMessage(error instanceof Error?error.message:"Customers could not be removed.")}finally{setBusy(false)}}

  return <AdminShell active="Customers"><div className="app-top"><div><span className="eyebrow">CUSTOMER OWNERSHIP CONTROL</span><h1>Customers</h1><p className="section-intro">Company customers are editable. Platform-assigned customers remain visible but locked.</p></div><div className="toolbar-inline"><input className="input" placeholder="Search customer, city, lawn..." value={query} onChange={e=>setQuery(e.target.value)} /><CompactFilter label="Useful filters"><label><input type="radio" checked={filter==="all"} onChange={()=>setFilter("all")}/> All</label><label><input type="radio" checked={filter==="company"} onChange={()=>setFilter("company")}/> Company-owned</label><label><input type="radio" checked={filter==="platform"} onChange={()=>setFilter("platform")}/> Locked by Platform</label><label><input type="radio" checked={filter==="big-lawn"} onChange={()=>setFilter("big-lawn")}/> Big lawns</label><label><input type="radio" checked={filter==="high-grass"} onChange={()=>setFilter("high-grass")}/> High grass</label><label><input type="radio" checked={filter==="access"} onChange={()=>setFilter("access")}/> Gate / dog / access</label><label><input type="radio" checked={filter==="missing-phone"} onChange={()=>setFilter("missing-phone")}/> Missing phone</label><label><input type="radio" checked={filter==="missing-email"} onChange={()=>setFilter("missing-email")}/> Missing email</label><label><input type="radio" checked={filter==="with-notes"} onChange={()=>setFilter("with-notes")}/> Has notes</label><hr/><label>City<select className="input" value={city} onChange={e=>setCity(e.target.value)}><option value="all">All cities</option>{cities.map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>Order<select className="input" value={sort} onChange={e=>setSort(e.target.value)}><option value="city">City / address</option><option value="lawn">Lawn size</option><option value="grass">Grass height</option></select></label></CompactFilter><Link className="btn btn-primary" href="/admin/add-client">＋ Add Customer</Link><button className="btn btn-danger" disabled={busy||selected.length===0} onClick={()=>void remove(selected,`${selected.length} selected customer(s)`)}>Delete Selected ({selected.length})</button><button className="btn btn-primary" onClick={refresh}>Refresh</button></div></div>
    <div className="stats v19-stats"><div className="card dash-card"><div className="mini-label">Today's homes</div><div className="mini-value">{today.completed}/{today.homes}</div></div><div className="card dash-card"><div className="mini-label">Today's tasks</div><div className="mini-value">{today.tasksCompleted}/{today.tasks}</div></div><div className="card dash-card"><div className="mini-label">Company-owned</div><div className="mini-value">{records.filter(r=>!r.lockedByPlatform).length}</div></div><div className="card dash-card"><div className="mini-label">Platform locked</div><div className="mini-value">{records.filter(r=>r.lockedByPlatform).length}</div></div><div className="card dash-card"><div className="mini-label">Total Synced</div><div className="mini-value">{records.length}</div></div></div>
    {error&&<div className="payment-message" style={{marginBottom:16}}>{error}</div>}{message&&<div className="payment-message" style={{marginBottom:16}}>{message}</div>}
    <section className="card table-card"><div className="table-head"><div><h2>Customer Directory</h2><p className="section-intro">Platform ownership is preserved after company assignment.</p></div><span className="sync-note">{filter} · {city} · {sort}</span></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={allVisibleSelected} onChange={toggleAll} aria-label="Select all editable customers"/></th><th>Customer</th><th>Property</th><th>Contact</th><th>Ownership</th><th>Lawn</th><th>Actions</th></tr></thead><tbody>{loading&&<tr><td colSpan={7}>Loading synced records...</td></tr>}{!loading&&visible.length===0&&<tr><td colSpan={7}>No customers match this filter.</td></tr>}{!loading&&Object.entries(grouped).map(([group,rows])=><Fragment key={group}><tr><td colSpan={7}><strong>{group}</strong> · {rows.length} customer(s)</td></tr>{rows.map(r=><tr key={r.propertyId}><td><input type="checkbox" disabled={r.lockedByPlatform} checked={selected.includes(r.customerId)} onChange={()=>toggle(r.customerId)} /></td><td><div className="customer-directory-person"><div>{r.officialPhotoUrl?<img src={r.officialPhotoUrl} alt={r.fullName}/>:<span>⌂</span>}</div><p><strong>{r.fullName}</strong><small>{r.customerNotes||"No customer notes"}</small></p></div></td><td>{r.addressLine1}, {r.city}<br/><small>{r.province} {r.postalCode||""}</small></td><td>{r.phone||"—"}<br/><small>{r.email||"—"}</small></td><td>{r.lockedByPlatform?<span className="pill">🔒 Locked by Platform</span>:<span className="pill">Company-owned</span>}<br/><small>{r.acquisitionSource.replaceAll("_"," ")}</small></td><td>{r.lotSize||"—"}<br/><small>{r.grassHeight||"—"}</small></td><td><div className="row">{r.lockedByPlatform?<><Link className="btn btn-small btn-outline" href={`/admin/customers/${r.propertyId}?tab=service`}>Open</Link><button className="btn btn-small" disabled title="Only Platform Master can edit">Locked</button></>:<><Link className="btn btn-small btn-primary" href={`/admin/customers/${r.propertyId}/edit`}>Edit</Link><Link className="btn btn-small btn-outline" href={`/admin/customers/${r.propertyId}?tab=property`}>History</Link><button className="btn btn-small btn-danger" disabled={busy} onClick={()=>void remove([r.customerId],r.fullName)}>Delete</button></>}</div></td></tr>)}</Fragment>)}</tbody></table></div></section>
  </AdminShell>;
}
