"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getSupabaseBrowserClient,isSupabaseConfigured,setSessionPersistencePreference} from "@/lib/supabase/client";

function roleHome(role:string){if(role==="master")return"/master";if(role==="admin"||role==="manager")return"/mobile/admin";if(role==="employee")return"/mobile/employee";return"/mobile/customer"}

export default function MobileLogin(){
  const router=useRouter();const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[rememberEmail,setRememberEmail]=useState(false);const[keepConnected,setKeepConnected]=useState(true);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  useEffect(()=>{const savedEmail=window.localStorage.getItem("damasio_login_email")||"";const savedKeep=window.localStorage.getItem("damasio_keep_connected");if(savedEmail){setEmail(savedEmail);setRememberEmail(true)}if(savedKeep)setKeepConnected(savedKeep==="true")},[]);
  async function login(){if(!isSupabaseConfigured()){setMessage("The secure server connection is not configured.");return}setBusy(true);setMessage("Signing in…");try{setSessionPersistencePreference(keepConnected);const client=getSupabaseBrowserClient() as any;const{data,error}=await client.auth.signInWithPassword({email:email.trim(),password});if(error)throw new Error(error.message);const{data:profile,error:profileError}=await client.from("profiles").select("role,active").eq("id",data.user.id).single();if(profileError||!profile)throw new Error("This account has no platform role yet.");if(!profile.active){await client.auth.signOut();throw new Error("This account is inactive. Contact the company Admin.")}if(rememberEmail)window.localStorage.setItem("damasio_login_email",email.trim());else window.localStorage.removeItem("damasio_login_email");router.replace(roleHome(profile.role))}catch(error){setMessage(error instanceof Error?error.message:"Sign-in failed.");setBusy(false)}}
  return <main className="mobile-app-shell mobile-login-page"><section className="mobile-hero-card"><div className="mobile-brand-row"><div className="mobile-brand-mark">4</div><div><strong>4Ever Seasons</strong><span>Secure mobile access</span></div></div><h1>Sign in</h1><p>Your live account automatically opens the correct mobile area.</p></section><section className="mobile-login-card"><label>Email<input className="input" type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@company.com"/></label><label>Password<input className="input" type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Your password"/></label><div className="auth-login-options mobile"><label><input type="checkbox" checked={rememberEmail} onChange={event=>setRememberEmail(event.target.checked)}/><span>Remember email</span></label><label><input type="checkbox" checked={keepConnected} onChange={event=>setKeepConnected(event.target.checked)}/><span>Keep me signed in</span></label></div><button className="mobile-primary" disabled={busy||!email||!password} onClick={()=>void login()}>{busy?"Signing in…":"Sign in securely"}</button>{message&&<p className="mobile-message mobile-error">{message}</p>}<a href="/login">Need help with your account?</a></section></main>
}
