"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AddressAutocomplete } from "@/components/home/AddressAutocomplete";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";

type Form={fullName:string;phone:string;addressLine1:string;city:string;province:string;postalCode:string;routeStartAddress:string;avatarUrl:string};
const blank:Form={fullName:"",phone:"",addressLine1:"",city:"",province:"ON",postalCode:"",routeStartAddress:"",avatarUrl:""};
async function token(){const client=getSupabaseBrowserClient()as any;const{data}=await client.auth.getSession();if(!data.session?.access_token)throw new Error("Sign in as Employee.");return data.session.access_token}

export default function EmployeeProfilePage(){
  const[form,setForm]=useState<Form>(blank);const[message,setMessage]=useState("Loading profile...");const[busy,setBusy]=useState(false);
  async function load(){try{const response=await fetch("/api/employee/profile",{headers:{authorization:`Bearer ${await token()}`},cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error);const profile=result.profile;setForm({fullName:profile.full_name||"",phone:profile.phone||"",addressLine1:profile.address_line1||"",city:profile.city||"",province:profile.province||"ON",postalCode:profile.postal_code||"",routeStartAddress:profile.route_start_address||profile.address_line1||"",avatarUrl:profile.avatar_url||""});setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Profile could not be loaded.")}}
  useEffect(()=>{void load()},[]);
  async function upload(file:File){const client=getSupabaseBrowserClient()as any;const ext=file.name.split(".").pop()||"jpg";const path=`${crypto.randomUUID()}.${ext}`;const{error}=await client.storage.from("employee-avatars").upload(path,file);if(error)throw new Error(error.message);const{data}=client.storage.from("employee-avatars").getPublicUrl(path);setForm(current=>({...current,avatarUrl:data.publicUrl}))}
  async function save(){setBusy(true);try{const response=await fetch("/api/employee/profile",{method:"PATCH",headers:{"content-type":"application/json",authorization:`Bearer ${await token()}`},body:JSON.stringify({...form,phone:form.phone||null,addressLine1:form.addressLine1||null,city:form.city||null,postalCode:form.postalCode||null,routeStartAddress:form.routeStartAddress||form.addressLine1||null,avatarUrl:form.avatarUrl||null})});const result=await response.json();if(!response.ok)throw new Error(result.error);setMessage(result.message||"Profile saved.")}catch(error){setMessage(error instanceof Error?error.message:"Profile could not be saved.")}finally{setBusy(false)}}
  return <main className="employee-profile-page"><section className="card profile-card"><div className="table-head employee-profile-head"><div><span className="eyebrow">MY PROFILE</span><h1>Employee profile</h1><p className="section-intro">Your saved route start address is used as the default origin for your routes.</p></div><Link className="btn btn-outline" href="/employee/route">Back to route</Link></div>{message&&<div className="payment-message" style={{marginBottom:16}}>{message}</div>}<div style={{display:"flex",alignItems:"center",gap:16,marginBottom:20}}><div style={{width:88,height:88,borderRadius:"50%",overflow:"hidden",background:"#e9f4ef",display:"grid",placeItems:"center",fontSize:32}}>{form.avatarUrl?<img src={form.avatarUrl} alt={form.fullName} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<span>{form.fullName.slice(0,1)||"+"}</span>}</div><label>Profile photo<input type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file).catch(error=>setMessage(error.message))}}/></label></div><div className="form-grid"><div className="field"><label>Name</label><input className="input" value={form.fullName} onChange={event=>setForm({...form,fullName:event.target.value})}/></div><div className="field"><label>Phone</label><input className="input" value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></div><div className="field"><label>Home address</label><AddressAutocomplete value={form.addressLine1} onChange={value=>setForm({...form,addressLine1:value})} placeholder="Home address"/></div><div className="field"><label>City</label><input className="input" value={form.city} onChange={event=>setForm({...form,city:event.target.value})}/></div><div className="field"><label>Province</label><input className="input" value={form.province} onChange={event=>setForm({...form,province:event.target.value})}/></div><div className="field"><label>Postal code</label><input className="input" value={form.postalCode} onChange={event=>setForm({...form,postalCode:event.target.value})}/></div><div className="field" style={{gridColumn:"1/-1"}}><label>Default route start address</label><AddressAutocomplete value={form.routeStartAddress} onChange={value=>setForm({...form,routeStartAddress:value})} placeholder="Where you normally start the workday"/></div></div><div style={{display:"flex",justifyContent:"flex-end",marginTop:18}}><button className="btn btn-primary" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save profile"}</button></div></section><style jsx>{`.employee-profile-page{max-width:900px;margin:0 auto;padding:24px}.employee-profile-head{align-items:flex-start;gap:16px}.employee-profile-head a{align-self:flex-start;white-space:nowrap}@media(max-width:720px){.employee-profile-page{padding:14px}.employee-profile-head{align-items:stretch;flex-direction:column}.employee-profile-head a{width:100%;justify-content:center}}`}</style></main>;
}
